scalameta/scalafmt

build.sbt
project/build.properties
scalafmt/src/main/resources/logback.xml
scalafmt/src/main/scala/org/scalafmt/ScalaFmt.scala
scalafmt/src/main/scala/org/scalafmt/ScalaFmtLogger.scala
scalafmt/src/main/scala/org/scalafmt/ScalaStyle.scala
scalafmt/src/test/resources/basic.test
scalafmt/src/test/scala/org/scalafmt/DiffUtil.scala
scalafmt/src/test/scala/org/scalafmt/FilesUtil.scala
scalafmt/src/test/scala/org/scalafmt/FormatTest.scala
scalafmt/src/test/scala/org/scalafmt/ProjectTest.scala

This commit adds:
- Formatter implementation based on Dijkstra's shortest path search
algorithm.  This way, we reduce the formatting problem to assigning a
weight to each formatting option between any two non-whitespace
tokens.
- dartfmt inspired testing via FormatTest, see
https://github.com/dart-lang/dart_style/tree/2fdfe08b92b0ee90492832df60d1eee9e47afcb5/test/splitting
- logging using logback + scala-logging via ScalaFmtLogger.

Format using shortest path search.

---

.travis.yml
build.sbt
project/plugins.sbt

sbt-coveralls doesn't seem to fully support multi-builds yet.

Downgrade Coveralls.

---

scalafmt/src/main/scala/org/scalafmt/FormatToken.scala
scalafmt/src/main/scala/org/scalafmt/Formatter.scala
scalafmt/src/main/scala/org/scalafmt/ScalaFmt.scala
scalafmt/src/main/scala/org/scalafmt/ScalaStyle.scala
scalafmt/src/main/scala/org/scalafmt/Split.scala
scalafmt/src/main/scala/org/scalafmt/State.scala
scalafmt/src/main/scala/org/scalafmt/package.scala
scalafmt/src/test/resources/basic.test
scalafmt/src/test/scala/org/scalafmt/FormatTest.scala

The column limit penalty, if any, is added to each split cost.
A split can attach a strategy to itself to limit/enchance future splits,
for example if we want to do a one-line block we don't want to allow
splits inside the block. The current implementation has limitations
shown in basic.test.

Add column-limit with basic strategies.

---

src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala
src/main/scala/org/scalafmt/package.scala
src/test/resources/basic.test

Policies replace strategies to enforcenon-local decisions. Policies are
applied to Splits before being saved to a state. This way you can for
example increase costs or remove illegal splits.

Introduce policy, fixes #15.

---

src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/Indent.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala

This eliminates the most popular use case for policies. Fixes #43.
To find expire tokens, we precompute all matching parens. Fixes #17.

Add expire field to Indent.

---

src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala
src/main/scala/org/scalafmt/package.scala
src/test/resources/standard/Apply.stat
src/test/resources/standard/Class.stat
src/test/resources/standard/Select.stat
src/test/resources/standard/Val.stat
src/test/resources/unit/Case.stat
src/test/resources/unit/If.stat
src/test/resources/unit/TermApply.stat
src/test/resources/unit/UnaryApply.stat
src/test/scala/org/scalafmt/FormatTest.scala
src/test/scala/org/scalafmt/ManualTests.scala
src/test/scala/org/scalafmt/UnitTests.scala

* Fix output for remaining ugliest parts of Formatter.scala, including
* sequences of select/apply: a.b(c.d).e(f).g. PROBLEM: this again causes
formatter to choke.
* Await for 20 seconds to submit results if running on Travis.
* Treat blocks inside arguments as 1 character width.  Not sure if this
makes sense in all cases, but gives nice results in my tests.

More polish.

---

build.sbt
project/plugins.sbt
src/main/scala/org/scalafmt/Cli.scala
src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/standard/Case.stat
src/test/resources/standard/If.stat
src/test/resources/standard/Select.stat
src/test/resources/unit/Case.stat
src/test/resources/unit/If.stat
src/test/resources/unit/TermApply.stat
src/test/scala/org/scalafmt/FormatTest.scala
src/test/scala/org/scalafmt/ProjectTest.scala
src/test/scala/org/scalafmt/Report.scala

We must key by column to prevent bugs like in test unit/TermApply
optimalAt memoization.
* Fix cost of newline before if in cond.
* Make compare report green when shrinking state.
* Demo CLI interface for vim integration.
* Fixed bug in partial functions.

OptimalAt keyed by state.column -> format token.

---

benchmarks/src/main/scala/org/scalafmt/benchmarks/FormatBenchmark.scala
benchmarks/src/test/scala/org/scalafmt/BenchmarkOK.scala
build.sbt
core/src/main/scala/org/scalafmt/ScalaStyle.scala
core/src/main/scala/org/scalafmt/internal/Decision.scala
core/src/main/scala/org/scalafmt/internal/GraphSearch.scala
core/src/main/scala/org/scalafmt/internal/Policy.scala
core/src/main/scala/org/scalafmt/internal/PolicySummary.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/internal/State.scala
core/src/main/scala/org/scalafmt/internal/package.scala
core/src/test/resources/standard/Apply.stat
core/src/test/resources/standard/Case.stat
core/src/test/scala/org/scalafmt/CliTest.scala
core/src/test/scala/org/scalafmt/FormatTests.scala
core/src/test/scala/org/scalafmt/IntegrityTest.scala
core/src/test/scala/org/scalafmt/RangeTest.scala
core/src/test/scala/org/scalafmt/util/DiffAssertions.scala
core/src/test/scala/org/scalafmt/util/ErrorTest.scala
core/src/test/scala/org/scalafmt/util/FormatAssertions.scala
readme.md
run-benchmarks.sh

* use longs as keys instead of tokens with custom hash function.
* IntegrityTest to verify formatter doesn't break code
* WARNING: can't format formatter.scala, deeply nested trees.
* Create Policy and PolicySummary case classes.
* {Format,Diff}Assertions.
Benchmark                        Mode  Cnt     Score      Error  Units
BaseLinker.scalafmt              avgt    3  2425.039 ± 1571.470  ms/op
BaseLinker.scalametaParser       avgt    3     7.863 ±   10.407  ms/op
BaseLinker.scalariform           avgt    3    14.838 ±    5.643  ms/op
Basic.scalafmt                   avgt    3    24.927 ±   22.778  ms/op
Basic.scalametaParser            avgt    3    18.943 ±   19.701  ms/op
Basic.scalariform                avgt    3     0.569 ±    1.327  ms/op
Division.scalafmt                avgt    3 …

Prepare for optimisations.

---

core/src/main/scala/org/scalafmt/ScalaStyle.scala
core/src/main/scala/org/scalafmt/internal/GraphSearch.scala
core/src/main/scala/org/scalafmt/internal/State.scala
core/src/test/scala/org/scalafmt/FormatExperiment.scala
core/src/test/scala/org/scalafmt/util/DiffAssertions.scala
core/src/test/scala/org/scalafmt/util/FormatAssertions.scala
readme.md

Still, expected more gains.
```
[info] Benchmark                        Mode  Cnt     Score     Error  Units
[info] BaseLinker.scalafmt              avgt    3   707.864 ±  87.023  ms/op
[info] BaseLinker.scalametaParser       avgt    3    10.876 ±  49.694  ms/op
[info] BaseLinker.scalariform           avgt    3    15.764 ±   3.908  ms/op
[info] Basic.scalafmt                   avgt    3    25.363 ±  46.914  ms/op
[info] Basic.scalametaParser            avgt    3    19.608 ±  18.905  ms/op
[info] Basic.scalariform                avgt    3     0.659 ±   1.250  ms/op
[info] Division.scalafmt                avgt    3  2253.869 ± 556.383  ms/op
[info] Division.scalametaParser         avgt    3    16.818 ±  11.662  ms/op
[info] Division.scalariform             avgt    3    35.331 ±  42.856 …
```

Find optimal tokens 3x faster, pay with memory.

---

build.sbt
core/src/main/scala/org/scalafmt/Error.scala
core/src/main/scala/org/scalafmt/ScalaFmt.scala
core/src/main/scala/org/scalafmt/ScalaStyle.scala
core/src/main/scala/org/scalafmt/cli/Cli.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/FormatToken.scala
core/src/main/scala/org/scalafmt/internal/Policy.scala
core/src/main/scala/org/scalafmt/internal/PolicySummary.scala
core/src/main/scala/org/scalafmt/internal/Split.scala
core/src/main/scala/org/scalafmt/internal/State.scala
core/src/main/scala/org/scalafmt/internal/package.scala
core/src/test/resources/standard/Case.case
core/src/test/resources/standard/Case.stat
core/src/test/resources/standard/Router.scala
core/src/test/resources/standard/Select.stat
core/src/test/resources/standard/Val.stat
core/src/test/resources/unit/If.stat
core/src/test/resources/unit/Interpolate.stat
core/src/test/scala/org/scalafmt/CliTest.scala
core/src/test/scala/org/scalafmt/FidelityTest.scala
core/src/test/scala/org/scalafmt/FormatExperiment.scala
core/src/test/scala/org/scalafmt/FormatTests.scala
core/src/test/scala/org/scalafmt/ManualTests.scala
core/src/test/scala/org/scalafmt/RangeTest.scala
core/src/test/scala/org/scalafmt/stats/TestStats.scala
core/src/test/scala/org/scalafmt/util/FormatAssertions.scala
core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala
readme.md

* add test for bug in var assignment to underscore
* add test for bug in interpolate with expr
* add router.scala to integrity test, no more surprises!
* fix bug in expiring indents
* apply policies in correct order.
* rename GraphSearch to BestFirstSearch because it's more correct.
* improve (?) newline handling in case statements.
* Revert hashCode because of collision, use HashToken until
https://github.com/scalameta/scalameta/issues/332 gets response.
* Fix bug in state column keys.

Fix output bugs, find new ones.

---

core/src/main/scala/org/scalafmt/ScalaFmt.scala
core/src/main/scala/org/scalafmt/cli/Cli.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/FormatToken.scala
core/src/test/scala/org/scalafmt/CliTest.scala
core/src/test/scala/org/scalafmt/FormatExperiment.scala
core/src/test/scala/org/scalafmt/RangeTest.scala

See https://github.com/scalameta/scalameta/issues/334.
The there is no need to format a range of lines then we call
position.end.line.
Scala.js
========
Unknown Failures: 62
Timeout Failures: 9
Parse exceptions: 19
Format successes: 830
Benchmark
=========
```
[info] Benchmark                        Mode  Cnt     Score    Error  Units
[info] BaseLinker.scalafmt              avgt    5   538.260 ± 86.656  ms/op
[info] BaseLinker.scalametaParser       avgt    5     6.433 ±  2.844  ms/op
[info] BaseLinker.scalariform           avgt    5    14.185 ±  1.416  ms/op
[info] Basic.scalafmt                   avgt    5    21.574 ±  3.126  ms/op
[info] Basic.scalametaParser            avgt    5    17.294 ±  2.465  ms/op
[info] Basic.scalariform                avgt    5     0.486 ±  0.094  ms/op
[info] …
```

Limit calls to token.position.end.line.

---

benchmarks/src/main/scala/org/scalafmt/benchmarks/FormatBenchmark.scala
benchmarks/src/test/scala/org/scalafmt/BenchmarkOK.scala
build.sbt
core/src/main/scala/org/scalafmt/internal/FormatToken.scala
core/src/main/scala/org/scalafmt/internal/PolicySummary.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/internal/State.scala
core/src/main/scala/org/scalafmt/internal/package.scala
core/src/test/resources/standard/Apply.stat
core/src/test/resources/standard/TestingClassNameDoNotEdit.scalafmt
core/src/test/resources/unit/TermApply.stat
core/src/test/scala/org/scalafmt/FidelityTest.scala
core/src/test/scala/org/scalafmt/util/HasTests.scala
core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala
run-benchmarks.sh

* custom hashcode for Token and FormatToken
* Expire policies, suprisingly little improvement.
```
[info] Benchmark                 Mode  Cnt     Score    Error  Units
[info] BaseLinker.scalafmt       avgt   10   415.639 ± 11.092  ms/op
[info] Division.scalafmt         avgt   10  1811.321 ± 43.431  ms/op
[info] SourceMapWriter.scalafmt  avgt   10   158.080 ±  3.959  ms/op
```

Minor optimizations.

---

build.sbt
core/src/main/scala/org/scalafmt/Error.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/Test.manual
core/src/test/resources/standard/Fidelity.stat
core/src/test/resources/unit/If.stat
core/src/test/resources/unit/Import.source
core/src/test/resources/unit/Symbol.stat
core/src/test/resources/unit/Type.stat
core/src/test/scala/org/scalafmt/ParseExperiment.scala
core/src/test/scala/org/scalafmt/util/ExperimentResult.scala
core/src/test/scala/org/scalafmt/util/FormatAssertions.scala
core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala

* Fix cases where formatter produces unformattable code.
* Handle curly brace starting new block.
* Fixes #25.
* Space after non-alphanumeric character identifiers.
* Eliminate spaces after inline comments.
* Fix type compounds and declarations
* Fix spaces around orphan (
ParserExperiment
Formatter timed out: 41
org.scalafmt.Error$FormatterChangedAST$: 7
java.lang.ClassCastException: 11
org.scalafmt.Error$CantFormatFile$: 8
Success: 853
Total: 920
+------------+--------+--------------+----------+---------+----------+----------+
|         Max|     Min|           Sum|      Mean|       Q1|        Q2|        Q3|
+------------+--------+--------------+----------+---------+----------+----------+
|9.946,107 ms|1,072 ms|811.343,078 ms|951,164 ms|50,666 ms|213,938 ms|876,157 ms| …

Fix multiple output bugs from FormatExperiment.

---

benchmarks/src/main/scala/org/scalafmt/benchmarks/FormatBenchmark.scala
benchmarks/src/test/scala/org/scalafmt/BenchmarkOK.scala
build.sbt
core/src/main/scala/org/scalafmt/Error.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/FormatToken.scala
core/src/main/scala/org/scalafmt/internal/Policy.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/internal/ScalaFmtLogger.scala
core/src/main/scala/org/scalafmt/internal/Split.scala
core/src/main/scala/org/scalafmt/internal/State.scala
core/src/main/scala/org/scalafmt/internal/package.scala
core/src/test/resources/standard/Fidelity.source
core/src/test/scala/org/scalafmt/ManualTests.scala
core/src/test/scala/org/scalafmt/util/ExperimentResult.scala
core/src/test/scala/org/scalafmt/util/FilesUtil.scala
core/src/test/scala/org/scalafmt/util/FormatAssertions.scala
core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala
project/Deps.scala

Instead of memoization we dequeue all states when we enter a new
statement *after* a newline. After spaces, we are likely inside a single
line block which has long-distance effects.
JMH Benchmarks
==============
Benchmark                  Mode  Cnt     Score   Error    Units
BaseLinker.scalafmt        avgt   10    65.884 ± 2.074    ms/op
Division.scalafmt          avgt   10   134.656 ± 3.048    ms/op
SourceMapWriter.scalafmt   avgt   10    31.851 ± 0.989    ms/op
OptimizerCore.scalafmt     avgt   10  1045.331 ± 236.486  ms/op
OptimizerCore.scalariform  avgt   10   230.654 ± 8.470    ms/op
NOTE. OptimizerCore was unformattable before.
Scala.js results
================
Formatter timed out: 10
org.scalafmt.Error$FormatterChangedAST: 1
java.lang.ClassCastException: 11
Success: 891 …

Remove memoization, ~100x speed improvement.

---

core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/internal/State.scala

* no optimizations zones is now Set[Token] instead of Set[Range]
* Replaced mutable.{Set,Map} with their respective builders.
* changed State.compare from tuple comparison to if/else tree of
Integer.compare.
```
JMH
===
Benchmark                    Mode  Cnt     Score    Error  Units
BaseLinker.scalafmt          avgt   10    72.014 ±  2.236  ms/op
BaseLinker.scalariform       avgt   10    13.491 ±  0.468  ms/op
Division.scalafmt            avgt   10   127.424 ±  4.343  ms/op
Division.scalariform         avgt   10    36.947 ±  5.346  ms/op
OptimizerCore.scalafmt       avgt   10   968.754 ± 53.008  ms/op
OptimizerCore.scalariform    avgt   10   253.146 ± 84.824  ms/op
SourceMapWriter.scalariform  avgt   10     7.059 ±  0.168  ms/op
Observe that ~400ms were shaved off OptimizerCore compared …
```

Up to ~30% performance improvements.

---

benchmarks/src/main/scala/org/scalafmt/benchmarks/FormatBenchmark.scala
benchmarks/src/resources/scala-js/JavaLangString.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/test/resources/Test.manual
core/src/test/scala/org/scalafmt/FormatExperiment.scala
core/src/test/scala/org/scalafmt/util/ExperimentResult.scala

This change is potentially dangerous but appears to work.
[info] # Run complete. Total time: 00:03:24
[info]
[info] Benchmark                        Mode  Cnt     Score     Error  Units
[info] GenJsCode.scalafmt               avgt   10  1375.404 ± 203.097  ms/op
[info] GenJsCode.scalariform            avgt   10   238.604 ±  10.338  ms/op
[info] JavaLangString.scalafmt          avgt   10   181.791 ±   3.683  ms/op
[info] JavaLangString.scalariform       avgt   10     6.878 ±   0.769  ms/op
[info] OptimizerCore.scalafmt           avgt   10  1330.836 ±  74.754  ms/op
[info] OptimizerCore.scalariform        avgt   10   235.918 ±  10.049  ms/op
[info] ScalaJSClassEmitter.scalafmt     avgt   10   305.206 ±  44.357  ms/op
[info] ScalaJSClassEmitter.scalariform  avgt   10    37.935 ±   4.010 …

Optimization: limit queue size even inside no opt zones.

---

core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/main/scala/org/scalafmt/internal/FormatToken.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/util/TreeOps.scala
core/src/test/scala/org/scalafmt/FormatExperiment.scala
core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala

According to JMH micro benchmarks
```
Before:
[info] GenJsCode.scalafmt  avgt   10  1625.856 ± 100.811  ms/op
After:
[info] GenJsCode.scalafmt  avgt   10  1358.511 ± 74.241  ms/op
```

Optimizations: roughly 17% improvement

---

readme/Readme.scalatex
scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalaFmtPlugin.scala

`sourceDirectories in hasScalafmt` is currently initialized with
`List(scalaSource.value)` which means that scalafmt only looks into
one source directory per project. But a typical Scala.js cross
project has at least two source directories js/ and shared/ or
jvm/ and shared/. Sometimes there are also multiple source
directories for different Scala versions.
This change initializes `sourceDirectories in hasScalafmt` with
`unmanagedSourceDirectories` which contains all source directories
with manually created sources. In my tests
`unmanagedSourceDirectories` always includes `scalaSource`.
Here are for example both settings for typelevel/cats:
> coreJVM/scalaSource
[info] cats/core/.jvm/src/main/scala
> coreJVM/unmanagedSourceDirectories
[info] List(
cats/core/.jvm/src/main/scala-2.11, …

Use unmanagedSourceDirectories for sourceDirectories

---

readme/Readme.scalatex

Sbt plugins aren't cross built, see:
* https://github.com/sbt/sbt/blob/v0.13.11/main/src/main/scala/sbt/Defaults.scala#L1948-L1953
* https://github.com/sbt/sbt/blob/v0.13.11/main/src/main/scala/sbt/Defaults.scala#L899-L900
crossVersion is disabled

Drop %% in addSbtPlugin

---

intellij/src/org/scalafmt/intellij/ScalafmtAction.scala

https://github.com/olafurpg/scalafmt/issues/239
This will fallback to `.scalafmt` config file in home directory in case of no such file in project directory.
* Been able to compile & run the plugin but wasn't able to test it.

fallback to config file in home dir

---

readme.md

I didn't realise the mistake was repeated.

Correct all other mentions of "paretheses"

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/Test.manual
core/src/test/resources/default/Advanced.stat
core/src/test/resources/default/DefDef.stat
core/src/test/resources/scalajs/DefDef.stat

A post-0.2.5 commit moved the case for non-statement starting blocks
further down in the Router. This commit moves that space back for defs.
The new Scala.js test case hightlights the need for a soft column limit,
as suggested by @spiewak in #317.

No newline between = {, fixes #328.

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/test/resources/noIndentOperators/Indent.stat
core/src/test/scala/org/scalafmt/util/HasTests.scala

This commit adds three new flags to control how infix operators play
with indentation.

Increase control over infix operator indentation, fixes #367.

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/spacesBeforeContextBound/Type.stat
core/src/test/scala/org/scalafmt/util/HasTests.scala

Context bound constraints are often written with spaces surrounding the `:` , for example:
```scala
def f[T : Numeric](t: T) = ???
```
, which is consistent with other type constraint usages such as `[T <: AnyRef]`.
https://github.com/olafurpg/scalafmt/issues/180 dealt with this and explicitly dropped spaces before, but I think an option to have it (off by default) is still useful
This PR adds the `spaceBeforeContextBoundColon ` option to allow inserting a space before the `:`.

Add spaceBeforeContextBoundColon option

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/internal/FormatWriter.scala
core/src/test/resources/align/AlignTokens.stat
core/src/test/scala/org/scalafmt/util/HasTests.scala

Once #172 is implemented, we can add more powerful configuration
for which tokens can align together.

Allow limited mixed owner alignment, fixes #184

---

scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalaFmtPlugin.scala

This addresses to fix #405. Note that this is a "cheap" solution, the better solution would be to read the `scalaFmtConfig` file, read the `formatSbtFiles` config option and then adjust the filter depending on whether we need to read SBT files or not.
I can add this functionality if asked

Make SBT plugin pick up .sbt files

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/util/FileOps.scala

Adds a `--exclude` flag to the CLI utility to ignore certain files.

Exclude files with a CLI option

---

core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/internal/FormatWriter.scala
core/src/test/resources/align/AlignTokens.stat
core/src/test/resources/alignNoSpace/AlignTokens.stat
core/src/test/scala/org/scalafmt/util/HasTests.scala

Add support to align by tokens that have no space before them

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/Scalafmt.scala
core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/test/scala/org/scalafmt/LineEndingsTest.scala
readme/Configuration.scalatex

Related to: https://github.com/olafurpg/scalafmt/issues/365#issuecomment-243346157

#356 Code with windows line endings after formatting still has windows endings

---

.scalafmt
build.sbt
cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/LineEndings.scala
core/src/main/scala/org/scalafmt/Scalafmt.scala
core/src/main/scala/org/scalafmt/ScalafmtRunner.scala
core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/Settings.scala
core/src/main/scala/org/scalafmt/config/RedundantBracesSettings.scala
core/src/main/scala/org/scalafmt/config/RewriteSettings.scala
core/src/main/scala/org/scalafmt/rewrite/Patch.scala
core/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
core/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
core/src/main/scala/org/scalafmt/rewrite/SortImports.scala
core/src/main/scala/org/scalafmt/util/LoggerOps.scala
core/src/main/scala/org/scalafmt/util/TokenTraverser.scala
core/src/main/scala/org/scalafmt/util/TreeOps.scala
core/src/main/scala/org/scalafmt/util/logger.scala
core/src/test/resources/rewrite/RedundantBraces.stat
core/src/test/resources/rewrite/RedundantBraces2.stat
core/src/test/resources/rewrite/SortImports.stat
core/src/test/scala/org/scalafmt/Debug.scala
core/src/test/scala/org/scalafmt/FormatTests.scala
core/src/test/scala/org/scalafmt/util/HasTests.scala
metaconfig/src/main/scala/metaconfig/Reader.scala
project/plugins.sbt

This commit adds a new feature to scalafmt so that the input is
rewritten before formatting.
Rewrite rules
-------------
The commit implements these rewrite rules:
- Sort imports within curly braces, fixes #304
- Strip away curlies for single statement blocks in defs, fixes #432
See this diff on Kafka from running sort imports and strip away curlies:
https://github.com/olafurpg/scala-repos/pull/7/files
Performance
-----------
This commit does not implement any specific optimizations, the main
concern is to have a proof-of-concept. I haven't benchmarked this implementation yet.
My wild guess is that this new features adds 1-10ms overhead to the
total running time depending on the size of the source file.
Caveats
-------
There are some funky corner cases where the current implementation may …

Semantics preserving rewrites before formatting.

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/spaces/Spaces.source

This PR is a proposed fix for #424.
An important note would be that the proposed solution splits the "left brace" case into two to help distinguish between an _import_ brace and a _string interpolation_ one. The existing code contemplated both cases within the same block, creating multiple "inner" boolean checks to distinguish between the two cases. Keeping them separate allows for more fine tuning in the future and IMHO, simpler code to reason about due to less branching logic.
I'm not quite sure if this is the right way to solve it, please let me know (tests in particular!)

Distinction between Import braces and string interpolation braces #424

---

bin/issue492.scala
bin/issue492.sh
bin/testAll.sh
build.sbt
core/src/test/scala/org/scalafmt/FidelityTest.scala

Once https://github.com/scalameta/scalameta/issues/502 is fixed, we can
remove scala-reflect.
Crazy enough, I wasn't able to reproduce the error via SBT so now I have
a bash script to ensure the same doesn't happen again.

Add scala-reflect back, fixes #492.

---

core/src/main/scala/org/scalafmt/internal/FormatWriter.scala
core/src/main/scala/org/scalafmt/util/TreeOps.scala
core/src/test/resources/align/AlignTokens.stat

This minimizes false positives. Fixes #521 and fixes #513.

Only align tokens with same distance to root node.

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
cli/src/test/scala/org/scalafmt/cli/FakeGitOps.scala
cli/src/test/scala/org/scalafmt/cli/FileTestOps.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/util/AbsoluteFile.scala
core/src/main/scala/org/scalafmt/util/FileOps.scala
core/src/main/scala/org/scalafmt/util/GitOps.scala
core/src/test/scala/org/scalafmt/util/GitOpsTest.scala

java.io.File is dangerous as it hard to keep track of which files have
relative paths and which have absolute paths.  The reason I don't use
ammonite ops (which already contains absolute paths) is that scalafmt
needs to work with Java 6, which means no java.nio.
Fixes #551.

Replace java.io.File with custom AbsoluteFile.

---

.scalafmt.conf
intellij/resources/META-INF/plugin.xml
intellij/src/org/scalafmt/intellij/FileDocument.scala
intellij/src/org/scalafmt/intellij/IdeaSettings.scala
intellij/src/org/scalafmt/intellij/IdeaUtils.scala
intellij/src/org/scalafmt/intellij/OnFileSaveComponent.scala
intellij/src/org/scalafmt/intellij/ScalafmtAction.scala
intellij/src/org/scalafmt/intellij/SettingsGui.scala
readme/Installation.scalatex

Update IDEA plugin

---

core/src/main/scala/org/scalafmt/config/Newlines.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/default/Select.stat

Although the change itself is small, this commit changes the
formatted output for a significant amount of code. An example
diff can be seen here: https://github.com/olafurpg/scala-repos/pull/14
Fixes #599.

Bump penalty for select chains of length 1.

---

core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/util/TreeClasses.scala
core/src/main/scala/org/scalafmt/util/TreeExtractors.scala
core/src/main/scala/org/scalafmt/util/TreeOps.scala
core/src/test/resources/align/AlignTokens.stat
core/src/test/resources/default/Lambda.stat
core/src/test/resources/default/TypeWith.stat
project/Deps.scala

1.3 introduced a new encoding for Type.Compound which complicated things
quite a bit. This commit tried to remap the new encoding into the old
encoding. The scala-repos diff is here: https://github.com/olafurpg/scala-repos/commit/c00c1bd6da91d2aec92f6d15933795f09d98ec2a
The diff comes from a quirky bug in
optimizer.recurseOnBlocks, see https://github.com/olafurpg/scalafmt/issues/614, which I think is a scalafmt bug and not scala.meta 1.3 bug.

Upgrade to scala.meta 1.3.

---

bin/scalafmt_auto

Not very familiar with this project, but I think this will fix cut issues where when tag name contains 
"-RC2". Current script is not considering -RC2 and is failing. 
Replaced with cut for simplicity.

fixing regex for latest version

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/util/TokenOps.scala
core/src/test/resources/default/SearchState.stat

The trick is to handle symbolic operators differently for select chains. This eliminates a branch on every `<.` selection.
Before:
After:

Improve search state for reactjs style DSLs. Fixes #458

---

readme/Installation.scalatex

Thanks for reviving the sbt plugin, by the way. It's really useful!

Fix link URL in the sbt docs

---

bin/scalafmt.bat
cli/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
cli/src/test/scala/org/scalafmt/cli/FileTestOps.scala
core/src/main/scala/org/scalafmt/Scalafmt.scala
core/src/test/scala/org/scalafmt/BestEffortTest.scala
core/src/test/scala/org/scalafmt/ContinuationIndentTests.scala
core/src/test/scala/org/scalafmt/EmptyFileTest.scala
core/src/test/scala/org/scalafmt/FidelityTest.scala
core/src/test/scala/org/scalafmt/FormatTests.scala
core/src/test/scala/org/scalafmt/StripMarginTests.scala
core/src/test/scala/org/scalafmt/util/GitOpsTest.scala
core/src/test/scala/org/scalafmt/util/HasTests.scala
utils/src/main/scala/org/scalafmt/util/FileOps.scala
utils/src/main/scala/org/scalafmt/util/GitOps.scala
utils/src/main/scala/org/scalafmt/util/OsSpecific.scala

On Windows it's needed to set SBT_OPTS=-Dfile.encoding=UTF8
The changes are a bit tricky. One could easily make change where all compared line endings will be converted to the same form but, in fact, then we could miss cases where the tested code itself could change line endings in the unexpected way.
`sbt test` passed.
```
[info] Run completed in 29 seconds, 619 milliseconds.
[info] Total number of tests run: 798
[info] Suites: completed 14, aborted 0
[info] Tests: succeeded 798, failed 0, canceled 0, ignored 33, pending 0
[info] All tests passed.
```
Other than that:
- `scripted` still fails on Windows:
```
[info] java.lang.Exception: File: target\src_managed\Generated.scala
[info] Obtained output:
[info] object DontFormatMe { println(1) }
[info] Expected:
[info] object …
```

Fix path separators and line endings to make most of tests passing on Windows

---

readme.md

The name of the file starts with `T` so it didn't work with `t`. By the way I changed the strange wording. ;)

Fix links to Tutorial.md

---

appveyor.yml
cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/config/ProjectFiles.scala
readme.md
utils/src/main/scala/org/scalafmt/util/OsSpecific.scala

Now paths like target/foo are accepted also on Windows.
The existing unit test has been extended to verify such cases.
By the way this fixed the `scripted` task when running on Windows.
In fact it was possible to use \\ e.g. in paths passed via --exclude,
but it isn't very helpful and convenient in case of projects built on
various platforms.

Make nested path exclusions working on Windows

---

.scalafmt.conf
bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala
bootstrap/src/test/scala/org/scalafmt/bootstrap/BootstrapTest.scala
build.sbt
cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
project/Deps.scala
project/plugins.sbt
scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala
scalafmtSbt/src/sbt-test/scalafmt-sbt/helloworld/build.sbt

Context: https://github.com/sbt/sbt/issues/2879
Pros:
- Fixes #654
- Fixes #653
- Fixes #641
- No min sbt version required.
Cons:
- Might break build if it's using an older version of sbt-courser.

Ditch synthetic project in favor of coursier.

---

cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala

I'm not sure if this is intended, but I noticed that the formatted code is written to stdout using println. This makes redirecting the stdout to a file incorrect as it adds an extra new line character.

Remove extra newline from stdout

---

core/src/main/scala/org/scalafmt/config/ContinuationIndent.scala
core/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/test/ContinuationIndent.stat

This setting sets the indentation at extends/with site. By default is it four (4) (in order to not break current), but the Scala Style Guide (http://docs.scala-lang.org/style/declarations.html#classes) recommends two (2).

New ContinuationIndent: extendSite

---

core/src/main/scala/org/scalafmt/config/hocon/Hocon2Class.scala
readme.md

Hi.
I am trying to structure the scalafmt config into multiple files, providing a default set of options with the ability to change / adjust some of the values inside of a project. That is why I am trying to use substitutions for example to add entries to the `project.excludeFilters`.
When using substitutions in HOCON, you need to call `resolve()` at some point in order to substitute the references. Otherwise _bad things_ happen:
```
com.typesafe.config.ConfigException$NotResolved: called unwrapped() on value with unresolved substitutions, need to Config#resolve() first, see API docs
at com.typesafe.config.impl.ConfigDelayedMerge.unwrapped(ConfigDelayedMerge.java:52)
at com.typesafe.config.impl.SimpleConfigObject.unwrapped(SimpleConfigObject.java:210)
at …
```

Resolve config

---

readme/src/main/scala/org/scalafmt/readme/Readme.scala

In https://olafurpg.github.io/scalafmt/#0.5.2 /r/therewasanattempt/ to link to https://github.com/olafurpg/scalafmt/pull/658, but instead it links to https://github.com/olafurpg/scalafmt/pulls/658. This fixes that.

Fix "pr" helper method in docs gen

---

core/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/test/ImprivataDefStyle.stat
core/src/test/resources/test/VericalMultiline.stat

This is a style that we are currently using and would like to keep using. It formats:
```scala
// maxColumn = 80
// this function is 98 chars long
def format_![T <: Tree](code: String, foo: Int)(f: A => B)(implicit ev: Parse[T], ev2: EC): String
```
to this:
```scala
def format_![T <: Tree](
code: String,
foo: Int
)(f: A => B
)(implicit ev: Parse[T],
ev2: EC
): String
```
This format will only apply if the function would go over the maxColumn is single-lined. If it is under, it will be singled line.

Adds a new style for function defs

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/test/VerticalMultiline.stat

Yet another bug fix for `verticalMultilineAtDefinitionSite`. I suspect this should be the last one though. 
Fixes an issue where `verticalMultilineAtDefinitionSite` would incorrectly split defaulted parameters that called a method.
ie:
```
def someFunc(
code: String = Defaults.getCode(a)(b)
): RT
```

Another fix for `verticalMultilineAtDefinitionSite`

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/test/VerticalMultiline.stat

Fix a bug where `verticalMultilineAtDefinitionSite` would fail to format
correctly if there existed an empty param-group at the beginning of the
definition.

Fix #731: empty-param group with verical style

---

utils/src/main/scala/org/scalafmt/util/GitOps.scala

helps to solve: #720
This should help scalafmt --diff to catch all uncommitted changes that differ from 'branch' along with committed changes.

Remove 'HEAD' from git diff, to include all uncommitted changes aswell

---

readme/Configuration.scalatex

Present the examples of the configurations in a more explicit, clarified
and format-consistent (oh the irony!) way.
As an example the comments "// ScalaDoc" and "// JavaDoc" weren't clear
if they were just giving an examples of ScalaDoc vs JavaDoc style, or if
they were the valid values to pass to "docstrings".

Clarify config values & examples some

---

core/src/main/scala/org/scalafmt/internal/Decision.scala
core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/main/scala/org/scalafmt/internal/FormatWriter.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
core/src/main/scala/org/scalafmt/util/TokenOps.scala
core/src/test/resources/align/comment-wrapping.source

Fixes #762
And rename InlineComment to SingleLineComment, aka "//"

Handle comment breaking wrapping

---

core/src/main/scala/org/scalafmt/config/IndentConfig.scala
core/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/main/scala/org/scalafmt/util/TokenOps.scala
core/src/test/resources/default/ApplyInfix.stat
core/src/test/resources/unit/Type.stat

There is a difference how left and right associative infix operators are parsed:
```scala
@ q"a :: b :: c".structure
Term.ApplyInfix(Term.Name("a"), Term.Name("::"), Nil, Seq(Term.ApplyInfix(Term.Name("b"), Term.Name("::"), Nil, Seq(Term.Name("c")))))
@ q"a + b + c".structure
Term.ApplyInfix(Term.ApplyInfix(Term.Name("a"), Term.Name("+"), Nil, Seq(Term.Name("b"))), Term.Name("+"), Nil, Seq(Term.Name("c")))
```
This commit adds an option to indent right associative operators just
like left-associative operators.

Fix #728, infix indent for ::

---

readme/Configuration.scalatex

.. and bring consistency to the rest: i.e make them also bold.

Fix newlines.alwaysBeforeTopLevelStatements doc

---

bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala
build.sbt

Addreses #807, I'm unable to reproduce the reported error so I can't say
if this commit fixes it or not. The reporter error indicates there's
some race condition with the default ivy resolver in ~/.ivy2/local,
I I'm hoping that this change avoids that error.

Don't resolve from ivy2local in ScalafmtBotstrap.

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/test/VerticalMultilineDefnSite.stat

Makes `verticalMultilineDefnSite` respect `continuationIndent.defnSite`.
Parameters are now indented by `continuationIndent.defnSite`, while
parameter separators are indented by `continuationIndent.defnSite - 2`,
with `0` being the minimum.
`continuationIndent.defnSite` is defaulted to `4`, so this won't affect
how `verticalMultilineDefnSite` currently works.

Fix issue #816: Makes verticalMultilineDefnSite respect continuationIndent.defnSite

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/test/VerticalMultiline.stat

Makes `verticalMultilineAtDefinitionSite` apply to classes too. Fixes issue #736

Fix #736: Make verticalMultiline apply to classes too

---

bin/scalafmt_auto

Updated `latest_version` URL from `https://api.github.com/repos/olafurpg/scalafmt/releases/latest` to `https://api.github.com/repos/scalameta/scalafmt/releases/latest`.

Updated latest_version in scalafmt_auto

---

core/src/main/scala/org/scalafmt/config/Newlines.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/newlines/afterCurlyLambdaAlways.stat
core/src/test/resources/newlines/afterCurlyLambdaNever.stat
core/src/test/resources/newlines/afterCurlyLambdaPreserve.stat

Fixes issue #808 by introducing a new setting: `newlines.afterCurlyLambda`
This option can have one of three settings: never (default), always and
preserve.
* `never`(default) removes all lines. Before this commit, this is what was happening
* `always` inserts one line if there is non and removes extra lines if
there are more. This means there is always one (1) line
* `preserve` is a combination of `never` and `always`. If the user does
not have an extra line, there it will not add an extra line (like
`never`). If there user has one or more lines, it will replaces it
with one line (like `always`).

Fix #808: newlines after curly lambda

---

core/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
core/src/main/scala/org/scalafmt/rewrite/SortImports.scala
core/src/test/resources/rewrite/AsciiSortImports.stat
readme/Configuration.scalatex
readme/src/main/scala/org/scalafmt/readme/Readme.scala

Adds a new rewrite.rule: `AsciiSortImports`. This rules works exactly as
SortImports but sorts in the traditional ASCII form.
This is wanted since many editors (ie: IntelliJ) use the ASCII sorting
when sorting their imports. Having this option allows people to better
transition to Scalafmt from existing codebases and decreases tension
between Scalafmt and most editors (users can use a mix of Scalafmt and
their editors at will).
NOTE: This setting is incompatible with `SortImports`

Fix #799 Allow ASCII sorting of imports

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala

scalafmt already filters files to format with canFormat for standard invocation.
This brings the '--diff' option into line with this behaviour

Fix #880, filter diff files with canFormat

---

core/src/main/scala/org/scalafmt/config/Newlines.scala
core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/test/resources/newlines/afterImplicitKWInVerticalMultiline.stat
core/src/test/resources/newlines/beforeImplicitKWInVerticalMultiline.stat

This introduces 2 new settings: `newlines.beforeImplicitKWInVerticalMultiline` and `newlines.afterImplicitKWInVerticalMultiline`. Both are set to `false` by default.

Fix #735. newlines before and after implicit keyword

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/FileFetchMode.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/WriteMode.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/AbsoluteFile.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/FakeGitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/DiffAssertions.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala

Implement #875: Remake scalafmt's CLI
* Remove --files
* Instead, files are take in as arguments (like a normal cli)
* If no arguments are passed, `./` is assumed
* Remake how we handle write-modes
* Write modes can either be `Override` (in-place) or `Stdout` (--stdout)
* `-i/--in-place` is now the default all of the time
* `--stdout` will print to stdout the formatted files
* Implement a `--git=[true|flase]` flag that will override `.scalafmt.conf`
* Fix an issue where the default `includeFilters` accepted more than just `scala` and `sbt`
* [Internal] Simplify how we fetch files (now it all goes through one function)
* [Internal] Simplify how we use CliOptions

Remake the CLI interface

---

readme/Installation.scalatex

in "Create a standalone executable" as it's installed in `/usr/local/bin/scalafmt` not current directory.

Replace `./scalafmt` with `scalafmt`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat

I ran AvoidInfix on ornicar/lila and found a bunch of errors.
- Don't remove critical parens in nested infix.
- Handle eta expansion in lhs infix application.

Harden AvoidInfix.

---

readme/Configuration.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeElseAfterCurlyIf.stat

```scala
// newlines.alwaysBeforeElseAfterCurlyIf = true
if(someCond) {
foo()
}
else {
bar()
}
// newlines.alwaysBeforeElseAfterCurlyIf = false
if(someCond) {
foo()
} else {
bar()
}
```

Add support for inserting a line break between a curly if and an else.

---

readme/Configuration.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/spaces/AfterKeywordBeforeParen.stat

Default: `true`
```scala
// spaces.afterKeywordBeforeParen = false
if(a) foo()
while(a) foo()
for(a <- as) foo()
// spaces.afterKeywordBeforeParen = true
if (a) foo()
while (a) foo()
for (a <- as) foo()
```

Implement option for discarding whitespace between a keyword and left-paren

---

scalafmt-intellij/readme.md
scalafmt-intellij/src/main/scala/org/scalafmt/intellij/FileDocument.scala
scalafmt-intellij/src/main/scala/org/scalafmt/intellij/IdeaUtils.scala
scalafmt-intellij/src/main/scala/org/scalafmt/intellij/OnFileSaveComponent.scala

Currently if the IntelliJ "project directory" is not located under the root of the repository for a project, two issues occur:
1. Because the plugin was determining the project for a file by comparing `project.getBasePath` to the file path, no project would be detected, and so there was nowhere to look for a scalafmt.conf other than the HOME directory.
1. Because the Project was not located under the root of the repository, even after successfully finding a project, we would not find a relevant config in the project directory.
This change fixes the first issue by using the ProjectFileIndex (as recommended [here](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/project_model/project.html#checking-if-a-file-belongs-to-a-project)), and the second issue by using the Project to …

Use the VCS root as a potential config path in the IntelliJ plugin

---

appveyor.yml
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

`./scalafmt` would fall back to the default style if .scalafmt.conf
had a typo. Now it fails fast.

Fail fast on invalid .scalafmt.conf when running with no args.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newdefault/ColumnWidth.stat

Reported here
https://github.com/scala-native/scala-native/pull/927#issuecomment-321223163
Ran sanity check on scala-native https://github.com/olafurpg/scala-native/commit/ec0efb94384c8c67809ca36cbcfeb2d3616c2aa6

Hacky hacks to fix off-by-one errors

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/FileTestOps.scala

Return non-zero exit code in ./scalafmt if no files match filter

---

project/Mima.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala

This PR fixes:
#962 by introducing a small testing framework for git and expand GitOpsTest
#1000 and #1010 by changing from `git ls-tree` to `git ls-files`
I remember reading somewhere that ls-tree is better, but I can't recall where or why. All I know is that the tests pass with `ls-files` but not `ls-trees`. 
Please point out any tests that I may have missed.

Git testing framework and fix for some git-file-fetching issues

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/optIn/SelectChains.stat

This option makes it possible to control line breaks around select
chains. Fixes #988.
Review @xerial @LMnet

Add optIn.breaksInsideChains = true

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/FileOps.scala

We don't want to change the file encoding during formatting.

Use the encoding option when writing files, too.

---

readme/Configuration.scalatex

Document that RedundantBraces may cause non-idempotent formatting.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/spaces/InByNameTypes.stat
scalafmt-tests/src/test/resources/spaces/NoSpaceInByNameParam.stat

Fixing https://github.com/scalameta/scalafmt/issues/1067

No space in by-name params

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala

Closes #1086 
* Add back --full-name when invoking Git 
* Add a test

Fix file not found errors when running from a subdirectory w/ project.git = true

---

readme/Installation.scalatex

Add  -r bintray:scalameta/maven to Coursier install commands because
the version resolves to the latest commit hash on master, which is
auto-published to bintray, but *not* to Maven Central.

Add  -r bintray:scalameta/maven to Coursier install commands

---

build.sbt
readme/Installation.scalatex

After replacing + with - in #1082 then the website started showing the
pre-release version instead of the stable release. This commit
adds a new section under the installation docs explaining how to consume
pre-releases.
FYI @lloydmeta

Fix version number in website and document pre-release.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala

This will allow users to override the current config via a comment and then set
it back to what it was. Something like:
```
// scalafmt: { indentOperator = spray }
get {
path("hey) {
complete("yeah!")
} ~
path("oh") {
complete("oh oh")
}
}
// scalafmt: { indentOperator = default }
```
I've reused an existing test but instead of `indentOperator = spray`, I used the new one: `indentOperator = default` to make sure it works. I'm not entirely sure the test is valuable, let me know otherwise.
Also, if I follow the contributing guidelines, I should be adding stuff to the documentation. IndentOperator are only found, AFAIK, in the `Other` section of the configuration. This section seems to be generated from `default.fields` and I can't figure out where this variable comes from.
There is also a …

Introduce "default", "akka" and "akka-http" as IndentOperator config

---

.github/ISSUE_TEMPLATE.md

This way it's clear what the state of the code was before running scalafmt, so it's clear what scalafmt did, compared to what you expected it to do.
See https://github.com/scalameta/scalafmt/issues/913#issuecomment-351806982 for an example of how the previous template can be misleading.

Add an "original code" section the issue template

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

An empty input (no matching input files) should not throw an error if `--diff` or `--stdin` is specified.
Previously discussed in #876.
Are there any additional exceptions?

Empty input with `--diff` and `--stdin` is okay

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/optIn/blankLineBeforeDocstring.stat

Previously, scalafmt always forced a blank line before docstrings. There
was no good reason for this, it was just a random decision I made before
v0.1 that no one has questioned until now. This behavior has in fact bugged
myself.
I think this setting is a good candidate to become default at some
point, but I'd like to receive a bit more feedback before making the
switch.
Review @alexandru

Add optIn.blankLineBeforeDocstring setting

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtRunnerTest.scala

Fixes #1098
Please review mercilessly, I'm happy to iterate.

Support trailing commas in sbt files

---

readme/Configuration.scalatex

`openParenDefnSite` is no longer a top level section

Fix openParenDefnSite docs

---

bin/_scalafmt

I'm not sure the best place for installation instructions to go.
Essentially, they're going to be exactly the same as those added to the
README, here:
https://github.com/coursier/coursier/pull/756/files
If someone tells me the best place for them to go, I'll add them.

Include ZSH tab-completion file to bin/_scalafmt

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala
scalafmt-tests/src/test/resources/default/TypeWith.stat
scalafmt-tests/src/test/resources/unit/Type.stat

This fixes #1125 to handle wrapping of "with-chains".
For example, a long chain of
```scala
Foo with Bar with Baz
```
can be wrapped as
```scala
Foo
with Bar
with Baz
```
This was already implemented for self-types (`trait Xyz { self: Foo with Bar with Baz => `). This PR expands the behavior to handle type definitions (`type MyType = Foo with Bar with Baz`) and function return types (`def xyz: Foo with Bar with Baz`).

Generalize with-chain wrapping for defs and type definitions

---

readme/Configuration.scalatex
readme/src/main/scala/org/scalafmt/readme/Readme.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/test/arityThreshold.source

This is a proof of concept for #1142. I'm opening a PR so I can ask questions about the code 😄

Arity threshold

---

readme/Configuration.scalatex
readme/src/main/scala/org/scalafmt/readme/Readme.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ReaderUtil.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/SortSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala
scalafmt-tests/src/test/resources/rewrite/SortModifiers.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiers1.source
scalafmt-tests/src/test/resources/rewrite/SortModifiers_Default.source
scalafmt-tests/src/test/resources/rewrite/SortModifiers_Mod_With_No_Token.source

Closes #1138 
Later edit:
I decided to add docs even before feedback.
TODO:
This rewrite rule will sort the modifiers applied to the following language constructs:
- Defn.Def
- Defn.Val
- Defn.Var
- Defn.Type
- Defn.Class
- Defn.Object
- Defn.Trait
- Term.Param
Example config:
```
rewrite {
rules = [SortModifiers]
sortModifiers {
order = ["implicit", "final", "sealed", "abstract", "override", "private", "protected", "lazy"]
}
}
```
Later edit — example with config:
```
maxColumn = 200
rewrite {
rules = [SortModifiers]
}
```
Before:
```
package test
sealed private[test] trait Test {
protected def name: String
}
final private[test] object Tests {
private final type T1 = Int
final private type T2 = String
final private implicit case object Test1 extends Test { def name: String = "Test1" } …
```

Implement SortModifiers rewrite rule

---

readme/Intro.scalatex
readme/Readme.scalatex
readme/resources/custom.css
readme/src/main/scala/org/scalafmt/readme/Readme.scala

If merged the site will look like this:

Style the page using the colors from the scalameta logo

---

readme/Configuration.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala
scalafmt-tests/src/test/resources/rewrite/SortModifiers_bug_1148.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiers_bug_1148_implicit_first_in_order.stat

Closes #1148 (bug), #1149 (docs)
There is one super weird corner case that is not handled properly by the fix. There's also a test for it:
If you have a sort order where `implicit` has lower order than the rest, then the following code gets formatted weirdly.
Config:
```
rewrite {
rules = [SortModifiers]
sortModifiers {
order = ["private", "protected" , "abstract", "final", "sealed", "implicit", "override", "lazy"]
}
}
```
Original code:
```
class X(private final val x: Int)(
implicit final private val i1: Int,
implicit final private var i2: Int
)
```
Formatted code:
```
class X(private final val x: Int)(
implicit private final val i1: Int,
private final implicit var i2: Int
)
```
But this is a super weird corner case where the `implicit` keyword is duplicated, and honestly until I wrote …

SortModifiers rewrite fixes + doc prettyfying

---

readme/resources/custom.css
readme/src/main/scala/org/scalafmt/readme/Readme.scala

Fix the full-width example styling

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Pattern.scala

The issue I'm trying to resolve is:
```
runningJobs should have size 0
```
reformated to:
```
(runningJobs should have).size(0)
```
This might be an issue with other similarly named functions like:
```
Seq() size
```
will not be reformated to:
```
Seq() size
```
Let me know what you think.

Add size to AvoidInfix

---

readme/Changelog04.scalatex
readme/Configuration.scalatex
readme/resources/custom.css
readme/src/main/scala/org/scalafmt/readme/Readme.scala

I find the existing flat list to be a bit overwhelming so I tried to
group the relevant settings together a bit.
I realise the docs site might be rewritten in the near future but I
still find it valuable to explore how best to group the configuration
options.

Reorganise the documentation for configuration options

---

readme/Readme.scalatex
readme/resources/custom.css
readme/resources/custom.js
readme/src/main/scala/org/scalafmt/readme/Readme.scala

Render the used config values as part of formatting examples

---

readme/Changelog05.scalatex
readme/Changelog07.scalatex
readme/Changelog10.scalatex
readme/Configuration.scalatex
readme/resources/custom.css
readme/src/main/scala/org/scalafmt/readme/Readme.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/VerticalMultiline.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/arityThreshold.source
scalafmt-tests/src/test/resources/vertical-multiline/VerticalMultilineDefnSite.stat
scalafmt-tests/src/test/resources/vertical-multiline/afterImplicitKW.stat
scalafmt-tests/src/test/resources/vertical-multiline/beforeImplicitKW.stat
scalafmt-tests/src/test/resources/vertical-multiline/newlineAfterOpenParen.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultilineDangling.source

The configuration defaults to the previous behavior.

Make it configurable when to exclude dangling parens for vertical

---

readme/Installation.scalatex

This PR adds section in documentation site about scalafmt support in [mill](http://www.lihaoyi.com/mill/) build tool.

Add section about scalafmt support in mill

---

readme/Installation.scalatex

replaced un-maintained maven plugin with the more current one
Alternatively we can keep both, but the `old` one is too old to keep if you ask me -  `Current version of the embedded Scalafmt is 0.2.11`

updated maven settings

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/unit/If.stat
scalafmt-tests/src/test/resources/unit/Lambda.stat

These are bundled together since I worked on them during a flight. See individual commits

Fix 3 bugs

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Case.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Literals.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/LitUnchanged.stat
scalafmt-tests/src/test/resources/unit/Lit.stat

```
1l => 1L
1F => 1f
1D => 1d
```
Fixes #293

Add support to force upper/lower case literal suffixes

---

build.sbt
scalafmt-cli-sbt/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ExitCode.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Previously, scalafmt --test failed on the first error.
Now it runs on all files and prints all violation errors and returns a
custom exit code for --test failure.
Fixes #912

Print out unified diff on --test failure.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Advanced.stat
scalafmt-tests/src/test/resources/default/Try.stat

A possible fix for https://github.com/scalameta/scalafmt/issues/1002
It extends the rule prohibiting single line blocks for `if` blocks to try-catch blocks as well

Try / finally formatted on a single line

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

This commit reverts the change that a non-zero exit code is reported for
parse errors. Instead, users must enable runner.fatalWarnings to get a
failing exit code for parse errors or other unexpected errors.
Fixes #815 
Fixes #349

Clean up handling of exit codes in the cli

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/test/IndentOperator.stat

Fixes #848.
Manually tested against https://github.com/hseeberger/akka-http-json and
it introduces no diff.

Indent body of vals when unindentTopLevelOperators=true.

---

readme/Configuration.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/spaces/AfterSymbolicDefs.stat
scalafmt-tests/src/test/resources/unit/UnaryApply.stat

A possible fix for https://github.com/scalameta/scalafmt/issues/915
It reuses existing `isSymbolicName` to decide if method name is an operator or not.

Added a rule for space after an operator method

---

build.sbt
project/Dependencies.scala
project/build.properties
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNeverComments.stat

Upgrading scalameta resulted in a "ClassNotFoundException" for a
scalacheck class that was fixed by adding a dependency on scalacheck in
the tests.
Fixes #1182

Unskip trailing commas tests, fixes #1174

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

Avoid lookup up match for non-Token.Left{Brace,Paren}

---

readme/Configuration.scalatex
readme/src/main/scala/org/scalafmt/readme/Readme.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/align/duplicateAlign.stat

Instead of making rules more complicated to support
```
align = more
align.openParenCallSite = true
```
We make it easier to override `align.tokens` by supporting
```
align.tokens = more
align.openParenCallSite = true
```
Fixes #1202

Support `align.tokens={none,some,more,most}`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysVerticalMultilineAtDefnSite.stat

Fixes https://github.com/scalameta/scalafmt/issues/1224
In the original issue, the expected formatted code is something like the below one. (doesn't put newline in the first empty parentheses). However, whether putting a newline in the empty parentheses is an issue of the verticalMultiline.
This PR fixes trailingCommas=always not to break compilation by checking the target formatToken is surrounded by empty parentheses
```scala
case class Test()(a1: Int,
a2: Int,
a3: Int,
a4: Int,
a5: Int,
a6: Int,
a7: Int,
a8: Int,
a9: Int)
```

Fix combination of trailingCommas=always and verticalMultilineAtDefnSite=true

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

While playing around with the trailing commas logic, I've noticed that the fix introduced in #1239 includes a redundant check.
Essentially this PR simplifies `!(A & B) & B` to `!A & B`,
since `!(A & B) && B === (!A || !B) && B`, so `!B` doesn't contribute
anything to the check.
Existing tests still pass.

Cleanup empty parentheses check

---

.travis.yml
build.sbt
project/plugins.sbt

This release fixes some bugs related to CI publishing.
This commit also removes the `big` module since it's better to fetch the
jars with coursier for sbt.

Upgrade to sbt-docusaurus v0.2

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-core/js/src/main/scala/org/scalafmt/internal/package.scala
scalafmt-core/jvm/src/main/scala/org/scalafmt/internal/PriorityQueue.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

This change enables Scalafmt to be built as a `native-image` with GraalVM from the scalafmt-cli jar.
This achieves one of the goals of #1172, namely, avoiding the JVM warm-up time.
For the scalafmt repo, I got a speed-up of **2.5x** in my computer. Also, since this method creates a binary just like the current recommended way using coursier and nailgun-ng in the console, it allows for much easier integration with editors such as emacs or vim and other script-based tooling (such as pre-commit hooks).
For building the test native-image I used [GraalVM CE 1..00-RC5](https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc5) under Fedora 28, and I just used `native-image -jar scalafmt.jar`.
This is the test I performed:
```bash
[ssaavedra@proton] scalafmt % $(which time) ~/tmp/scalafmt.jar …
```

Enable builds under GraalVM

---

scalafmt-tests/src/test/resources/default/Unicode.stat

Close https://github.com/scalameta/scalafmt/issues/1176
Thanks to  https://github.com/scalameta/scalafmt/pull/1283, scalameta has been upgraded to v4.0.0 :tada: and the issue has been fixed as of scalameta v4.0.0-M6
https://github.com/scalameta/scalameta/releases/tag/v4.0.0-M6
https://github.com/scalameta/scalameta/pull/1627

Add test for https://github.com/scalameta/scalafmt/issues/1176

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

Addresses https://github.com/scalameta/scalafmt/issues/1242
The reason why scalafmt doesn't align the adjacent single line of comments which appears in method chains or parameters with `align=more` is that [columnsMatch](https://github.com/scalameta/scalafmt/blob/bcfe2b296144e6bf6fac1c253b8c12fc7031ca12/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L277-L294) in `FormatWriter.scala` doesn't matches the two adjacent `//`s.
There are mainly two factors that makes `columnsMatch` doesn't match two `//`s.
---
The first one is that [vAlignDepth(row1Owner) == vAlignDepth(row2Owner)](https://github.com/scalameta/scalafmt/blob/bcfe2b296144e6bf6fac1c253b8c12fc7031ca12/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L285-L286
) become …

Vertical align adjacent single lines of comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysAlignMore.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNever.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNeverCommentsAlignMore.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Fixes https://github.com/scalameta/scalafmt/issues/1254
This PR is based on https://github.com/scalameta/scalafmt/pull/1260 because the commit https://github.com/tanishiking/scalafmt/commit/61eec1d301acc35948be011a1ac7d86fba6ad447 which fixes #1254 will break the alignment of leading comments which is done by  https://github.com/scalameta/scalafmt/pull/1260. And this PR contains the commit (https://github.com/tanishiking/scalafmt/commit/47356126eca00704631937ce163320fdde442a8e) that fixes the breakage.
---
For instance, without https://github.com/tanishiking/scalafmt/commit/47356126eca00704631937ce163320fdde442a8e
Given setting
```
trailingCommas = always
align = more
```
Given code like this:
```scala
def method (
x: String, // comment
yyy: String // comment
)
```
Scalafmt formats code …

Fix trailing commas always/never not to put/delete trailing comma on incorrect location

---

build.sbt

This makes the `downloadIdea` command work again.

Enable sbt-idea-plugin in intellij project

---

docs/configuration.md

We may want the config example for `continuationIndent.callSite` to explicitly set
`continuationIndent.callSite` instead of `continutionIndent.defnSite` (although this example is correct because `continuationIndent.callSite` is `2` by default).

Fix configuration example for continuationIndent.callSite in document

---

scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNeverComments.stat

see https://github.com/scalameta/scalafmt/issues/1231
This idempotency violation has been fixed as of https://github.com/scalameta/scalafmt/pull/1262

Add test for preserving location of comment when removing trailing comma

---

docs/configuration.md
readme/Configuration.scalatex

Mention vertical alignment mitigation strategies, so that users can
better decide whether they want to align and use the strategies, or not
align and therefore not need them.

Expand on the align=none protip

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultilineDefnSiteNoDangling.stat

#966 
The suggested fix in the ticket is a rewrite rule. While I think that would be reasonable, it's more complex. This patch is the absolute minimal version that fixes the invalid code generation. If you want the code formatted as suggested in the linked issue, scalafmt will preserve that style as long as you do the edit (move the parenthesis) yourself.

avoid generating invalid scala code

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/test/includeNoParensInSelectChains.stat

This introduces an option `includeNoParensInSelectChains` (any better naming ideas? was going for consistency with `includeCurlyBraceInSelectChains`) which, in conjunction with `optIn.breakChainOnFirstMethodDot`, treats applications without parens the same as those with parens.
For example, this:
```
List(1).toIterator.buffered
.map(_ + 2)
.filter(_ > 2)
```
is reformatted as:
```
List(1)
.toIterator
.buffered
.map(_ + 2)
.filter(_ > 2)
```
This partially addresses #1042.

 Add includeNoParensInSelectChains

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/FileOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Turns out that the old crappy file read/write code was buggy so that
Scalafmt sometimes didn't insert a newline at the end of files. Now,
Scalafmt uses nio.Files and it correctly writes a newline at
the end of the file if it's missing.
Fixes #1317

Fix the mysterious case of missing newline at end of file.

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ContinuationIndent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/ContinuationIndentNoDanglingParens.stat

This particular change modifies formatting for definition sites when `danglingParentheses` config is set to false. 
As exercised in the tests, 
```scala
def doAThingFunction(extremelyLongNamedParameterNumberOne: Int, extremelyLongNamedParameterNumberTwo: Int): ExtremelyLongNameForAReturnValueType
```
becomes: 
```scala
def doAThingFunction(
extremelyLongNamedParameterNumberOne: Int,
extremelyLongNamedParameterNumberTwo: Int)
: ExtremelyLongNameForAReturnValueType 
```
Whereas before, it would have always been indented to 2 spaces: 
```scala
def doAThingFunction(
extremelyLongNamedParameterNumberOne: Int,
extremelyLongNamedParameterNumberTwo: Int)
: ExtremelyLongNameForAReturnValueType 
```
The default value for this new parameter is set such to match the existing formatting.

Add Continuation Indentation for Type Annotation Site

---

build.sbt
docs/installation.md
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/test/scala/tests/DynamicSuite.scala
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/Scalafmt.java

Scalafmt has historically been published from com.geirsson to avoid
breaking changes. Now that we're releasing v2 and scalafmt-dynamic
can take care of adjusting the organization it's time to bite the bullet
and switch.

Change publish organization to org.scalameta from com.geirsson

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/test/scala/tests/DynamicSuite.scala
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtReporter.java

Clients may want custom error handling in this case so it deserves a
custom endpoint.

Add custom reporter endpoint for missing scalafmt version

---

docs/installation.md

I created Arch Linux scalafmt [package](https://aur.archlinux.org/packages/scalafmt-native) built with GraalVM and going to maintain it. Do you think installation instructions should be presented on the site? Or is it excessively for one Linux distro?

Added Arch Linux installation instruction on website

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-dynamic/src/test/scala/tests/DynamicSuite.scala

Close https://github.com/scalameta/scalafmt/issues/1360
For the details, please see the issue above.
This change is required to install scalafmt-dynamic to scalafmt-cli, because `scalafmt-cli <filename>` format the specified file no matter what the filename is, and it is necessary to ignore the project filter (format any inputs) to preserve the behavior.

Make ScalafmtReflect format any files if respectProjectFilters=false

---

readme.md

Rikito has been actively helping out in both Scalafmt and Scalafix. He is the maintainer of [scalaunfmt](https://github.com/tanishiking/scalaunfmt), a tool to automatically generate .scalafmt.conf that most closely matches an existing codebase's formatting conventions.  I am happy to welcome him as a Scalafmt collaborator so he can merge PRs and cut new releases.

Welcome Rikito Taniguchi to the team!

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/test/UnindentTopLevelOperatorsOperatorSpray.stat

This builds ontop of vanilla tests https://github.com/scalameta/scalafmt/pull/1371 to show the desired behavior changes.  The updated code makes the `unindentTopLevelOperators` consistent with the `style.indentOperator .includeRegexp` and `style. indentOperator.excludeRegExp`

Indent Operator Fix

---

build.sbt
scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/FileTestOps.scala

This PR makes scalafmt-cli to use `scalafmt-dynamic` and enable it to switch scalafmt version using `version` setting in a `.scalafmt.conf`.
https://github.com/scalameta/scalafmt/issues/1318
Since `scalafmt-interface#format` receive the config as `Path`, we cannot parse the config on the client side as long as we use `scalafmt-dynamic` as a backend.
If scalafmt couldn't find `.scalafmt.conf` the following message will appear repeatedly.
```
file does not exist: /home/tanishiking/dev/src/github.com/scalacenter/scalafix/.scalafmt.conf
```
If `.scalafmt.conf` doesn't contain `version` setting, scalafmt will tell the following message repeatedly. ( this warning will appear every time scalafmt-cli try to format a file)
```
missing setting 'version'. To fix this problem, add the following line …
```

Make scalafmt-cli to use scalafmt-dynamic module instead of depending on specific version of scalafmt-core.

---

docs/installation.md

sbt-scalafmt v2.0.0-RC5 is out
https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.0.0-RC5

Update website for sbt-scalafmt 2.0.0-RC5

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Unindent.stat
scalafmt-tests/src/test/resources/test/IndentYieldKeyword.stat
scalafmt-tests/src/test/resources/unit/For.stat

```scala
// Before
for (a <- as)
yield
Future {
// ...
}
// After
for (a <- as)
yield Future {
// ...
}
```
It's possible to get the old behavior with `newlines.avoidAfterYield = false`.
While working on this change, I observed that
`style.indentYieldKeyword=true` (default) has undesirable (and
unexpected) behavior for val definitions.
```scala
// Before
val x = for (a <- as)
yield a
// After
val x =
for (a <- as)
yield a
```
The new behavior is more consistent with how we handle other val
definition bodies. By forcing a line break before `for`, we make
it easier to associate the `for` keyword with its accompanying `yield`.

Avoid newlines after yield keyword.

---

appveyor.yml
scalafmt-core/shared/src/main/scala/org/scalafmt/util/OsSpecific.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtConfigTest.scala

Fixes #1404
I tested this on AppVeyor.
```
[info] ScalafmtConfigTest:
[info] - project.matcher *** FAILED ***
[info]   java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 50
[info] (scalafmt-benchmarks\src\resources|\sbt-test\|bin\issue)
[info]                                                   ^
[info]   at java.util.regex.Pattern.error(Pattern.java:1957)
[info]   at java.util.regex.Pattern.escape(Pattern.java:2473)
[info]   at java.util.regex.Pattern.atom(Pattern.java:2200)
[info]   at java.util.regex.Pattern.sequence(Pattern.java:2132)
[info]   at java.util.regex.Pattern.expr(Pattern.java:1998)
[info]   at java.util.regex.Pattern.group0(Pattern.java:2907)
[info]   at java.util.regex.Pattern.sequence(Pattern.java:2053)
[info]   at …
```

Replace slash with two backslashes on Windows

---

bin/_scalafmt
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/FileFetchMode.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/AbsoluteFile.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/FakeGitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala

The premise is the desire to reduce testing/reformatting time by limiting the workload surface.
While working as part of the team on the same repo the master's head could go quite significantly farther potentially enlarging the `diff` which causes the formatting slowdown. The impact is quite dramatic if the `scalafmt --diff --test` is used as part of pre-commit hook.
Current PR revisits the `--diff` option turning it into `--mode [diff/changed]` to switch between two modes.
While `--mode diff` preserves the behaviour of `scalafmt --diff` the `--mode changed` utilises the `git status` to fetch the files for formatting limiting the surface down to the very minimum of the recent changes.

Add the CLI option to fetch only recently changed files for formating.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/spaces/BeforeContextBoundColonIfMultipleBounds.stat

Fixed spaces.beforeContextBoundColon=IfMultipleBounds behavior for case with subtyping

---

docs/configuration.md

Noticed that there was a disclaimer of `assumeStandardLibraryStripMargin` not being idempotent in some cases, and linking to an issue that has since been fixed. Figured I'd take the liberty of removing that disclaimer from the docs since it's now obsolete.
Thanks for building and maintaining this tool! It's been hugely helpful for maintaining consistent formatting in Scala projects I maintain.

Remove closed issue from Scalafmt documentation

---

build.sbt
scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala

That's a minor change I've used to debug few cases locally. Thought it could come in handy for the broader audience.
P.S. Sorry for the typos in the commit message.

 Prints out the paths of files subjected to formating before the beginning of formatting in debug mode

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/VerticalMultiline.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/excludeDanglingInDef.stat

This PR adds new configuration flag to avoid dangling parens in method definitions
`verticalMultiline.excludeDanglingParens = [ def ]`
Example:
```scala
def getListing(a: String, b: String, c: String, d: String)(implicit e: String): Future[String] = {
a + b + c + d + e
}
```
Without flag formats to:
```scala
def getListing(
a: String, 
b: String, 
c: String, 
d: String
)(implicit e: String
): Future[String] = {
a + b + c + d + e
}
```
With new flag:
```scala
def getListing(
a: String, 
b: String, 
c: String, 
d: String
)(implicit e: String): Future[String] = {
a + b + c + d + e
}
```

exclude dangling parens in methods with enabled verticalMultiline

---

.gitignore

Just updated .gitignore for metals based on
http://scalameta.org/metals/docs/editors/sublime.html#gitignore-metals-and-bloop
Merging after CI passes.

Update .gitignore for metals and bloop

---

bin/test-release.sh
docs/contributing-scalafmt.md
website/package.json

- Remove a process for checking whether the versions of scalafmt and sbt-scalafmt match, because after scalafmt 2.0.0, scalafmt-core and sbt-scalafmt have different versioning.
- Update docusaurus to the latest.

Update the release process document, and upgrade docusaurus

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala

This PR introduces option for cli: `--list` which would:
* Print full path for files that are different from `scalafmt` formatting without changing them
* Disable `info` in order to hide fancy one (and not fancy another) progress bar
#1459

Add --list cli option #1459

---

.travis.yml

> oraclejdk8 is not preinstalled on Xenial anymore, and cannot be
retrieved from Oracle itself anymore. We'd suggest using either openjdk,
or the currently supported Oracle JDK.
https://github.com/travis-ci/travis-ci/issues/10290

Use openjdk8 instead of oraclejdk8

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/unit/Lit.stat

When uppercasing hex long literals take care not to change the 0x.
```
0x123l    # this
0X123L   # shouldnt become this
0x123L   # it should be this
```
resolves https://github.com/scalameta/scalafmt/issues/1437

dont uppercase long hex literal 0x prefix

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

https://github.com/scalameta/scalafmt/issues/1459
Follow up for https://github.com/scalameta/scalafmt/pull/1466
This PR make `--list` option to
- Return exit code 1 for `scalafmt --list` if there are any files that require re-formatting
- Print the relative path for the files (instead of absolute paths)
This behavior is pretty similar to [prettier's --check option](https://prettier.io/docs/en/cli.html#check)

Return exit code 1 for `scalafmt --list` if there are any files that require re-formatting

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/test/i1439.stat

Fixes (#1439)
I discovered that fix in https://github.com/scalameta/scalafmt/pull/1372 works fine only with `indentOperator = spray` configuration. Otherwise it breaks correct code.
I **don't like** this solution, it looks hacky. Any ideas how to do it better?
Also I don't use `unindentTopLevelOperator` configuration in my codebase. Can anyone provide more test cases for it? I am afraid that my fix can break anything else :smile:

Fixed unindentTopLevelOperator behavior without indentOperator=spray

---

docs/installation.md
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala

`ConfigFactory.parseFile` is able to resolve relative includes of the form `include "my/dir/my-defaults.conf"`. However, Scalafmt sticks to reading the main config and then parses it as text—without resolving includes.
This PR alters how config files are parsed. `ConfigFactory.parseFile` is used, followed by `.root.render()` to obtain configuration text with fully resolved includes.
Note that caching consideration within `ScalafmtDynamic` have not yet been addressed—configuration modification date will have to be obtained from all included configuration files. (this can be achieved by using a custom `ConfigIncluder`).

fix include resolution for cli and sbt plugin

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala

Allow for multiple `--exclude` flags and improve the description shown with the `--help`.
This will allow me to better organize some git hooks I'm writing.

Allow for multiple --exclude flags

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat

Fixes #1464. This PR makes the code simply ignore these weird cases as opposed to trying to remove them. I think this means that no code will suddenly fail `scalafmtCheck` after this change, but people will have to manually remove any of those weird commas.
Thanks for the great software!

Don't treat commas in lambda bodies as "trailing commas"

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala

I think this fixes https://github.com/scalameta/scalafmt/issues/1456
Sorry I have not been able to test it manually yet.

fix running with the diff branch file filter

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

Fixes (#1491, #1383)
Current last brace search algorithm is too "greedy" and captures non-constructor modifiers

Fixed bug with private[x] after class definitions (#1491)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.stat
scalafmt-tests/src/test/resources/spaces/Hacking.stat

Fixes #618 which, although closed due to inactivity, describes an improvement to spacing after constructor annotations - specifically, it'd be nice to retain a space between the constructor annotation and the first parameter list of the constructor. The desired spacing looks like:
```scala
class Foo @Inject() (bar: Bar) {
```
Whereas, currently, we'd remove the space, producing:
```scala
class Foo @Inject()(bar: Bar) {
```

Add a space between constructor annotations and their parameter lists

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala

This is another crack at https://github.com/scalameta/scalafmt/pull/1436 which I think is a bit easier now we've got the Coursier interface on board.
I believe that fetching Coursier's default repositories also prompts Couriser to check COURSIER_REPOSITORIES env var and `couriser.repositories` property - so by using defaults here we get COURSIER_REPOSITORIES compatibility
Previously the default repositories were being totally overwritten by the hard coded repository list
I believe this fulfils https://github.com/scalameta/scalafmt/issues/1521

Use Coursier defaults, which also adds support for COURSIER_REPOSITORIES

---

.travis.yml
build.sbt
project/Dependencies.scala
project/build.properties
project/plugins.sbt
scalafmt-benchmarks/src/main/scala-2.12/benchmarks/MacroBenchmark.scala
scalafmt-benchmarks/src/main/scala/org/scalafmt/benchmarks/FormatBenchmark.scala
scalafmt-benchmarks/src/main/scala/org/scalafmt/benchmarks/MicroBenchmark.scala
scalafmt-benchmarks/src/test/scala-2.12/org/scalafmt/benchmarks/BenchmarkOK.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CompatParCollections.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfDecoders.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Patch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtVersion.scala
scalafmt-dynamic/src/test/scala/tests/ScalafmtVersionSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Fixes #1434 
Aaaand now pipeline is green :rocket: 
1. Please take a look at [ScalafmtVersion](https://github.com/scalameta/scalafmt/pull/1522/files#diff-03988867feb59caad531803ea8b69f21) introduced in this PR. Now it's difficult to compare scalafmt versions in `ScalafmtDynamicDownloader` only with manual string parsing (e.g. `.startsWith("0.1")`).
2. Hard-coded scalafmt version with Scala 2.13 in `ScalafmtDynamicDownloader` is 2.2.0. Is it ok? **UPD: 2.1.2**
3. There are a lot of garbage commits in my branch. I don't like to force push into already published branches, so squash it on merge, please :smile:

Update Scala to 2.13

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/spaces/Constructor.stat
scalafmt-tests/src/test/resources/spaces/Hacking.stat

This PR is follow up of https://github.com/scalameta/scalafmt/pull/1516 that fixes https://github.com/scalameta/scalafmt/issues/1528 (the regression from 2.1.1)

Do not add space between constructor parameters

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/withSpacesInParentheses.stat

- **Configuration**:
```
version = 2.1.0
spaces.inParentheses = true
maxColumn = 40
verticalMultiline.atDefnSite = true
```
Given code like this:
```scala
def x(foo: Int) = 2
```
Scalafmt formats code like this:
```scala
def x(foo: Int ) = 2
```
I would like the formatted output to look like this:
```scala
def x( foo: Int ) = 2
```

Fix inconsistent spaces with verticalMultiline and spaces.inParentheses

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/resources/newlines/avoidEmptyLinesAroundBlock.stat

Followup from https://github.com/scalameta/scalafmt/pull/1431. This setting is already covered by the `edition` option. 
An important aspect of editions is that users will not be able to pick and choose individual changes to the default formatting behavior. The motivation for this restriction is to
* make the project more maintainable: it's difficult to reason how all possible combinations of off-by-default settings work in practice
* improve the user experience: currently, users can mix and match individual settings that hit on bugs such as #1539.

Remove `avoidEmptyLinesAroundBlock` option

---

readme.md

I think that discord is more handy than gitter. It's not good that scalameta server is not marked on the README.

Discord label in README

---

build.sbt
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtVersion.scala
scalafmt-dynamic/src/test/scala/tests/DynamicSuite.scala
scalafmt-dynamic/src/test/scala/tests/ScalafmtVersionSuite.scala

While I tried to test https://github.com/scalameta/scalafmt/pull/1549 locally, I found that scalafmt has mainly two things that make it cumbersome to test locally.
- Before this commit, `sbt publishLocal` publish the build to local ivy with the version something like `2.1.0+xxxx-SNAPSHOT` (if people didn't fetch the latest tags to local)
- when scalafmt-dynamic tries to download scalafmt-core whose version was `2.1.0+xxxx-SNAPSHOT`, it looks for scalafmt built with 2.12 (see: https://github.com/scalameta/scalafmt/blob/778c75f728a7a039fa63499ae3f97c69b4a018f0/scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala#L68-L71)
- However, the default scala version is now 2.13 (as of https://github.com/scalameta/scalafmt/pull/1522) and `sbt publishLocal` would build …

Make it easier to test scalafmt local snapshot build

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

Example diffs: https://github.com/kitbellew/scala-repos/commits/scalafmt-1549

RedundantBraces: remove nested braces in lambda

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/FileOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/DeleteTree.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala

Currently, if you run with `project.git = true` on a repository with symbolic links, we get an `IOException`.
No idea how to write a unit test for this (can't find any coverage for `ScalafmtRunner`). If it's OK to move this behavior into `GitOps::lsTree`, then it becomes easier to test. Please let me know!
Full stack trace when running with version 2.2.2:
```
Exception in thread "main" java.io.IOException: Is a directory
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:197)
at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
at …
```

Remove irregular files, including symbolic links, from `git ls-files`.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/align/ArrayIndexOutOfBounds800.source
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/SearchState.stat
scalafmt-tests/src/test/resources/newdefault/SearchState.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat
scalafmt-tests/src/test/resources/unit/Lambda.stat

N.B. fork of `scala-repos` showing the difference: https://github.com/kitbellew/scala-repos/commits/scalafmt-1551
Fixes #667
It is desirable to have an option to format paren lambda in calls just
like a curly-brace lambda. For instance, currently:
```
call { parameter =>
long_body
}
```
but
```
call(
parameter =>
long_body
)
```
instead of the similar (and more compact)
```
call(parameter =>
long_body
)
```
Obviously, when the call refers to multiple arguments (which is never
the case with curly-brace lambda), this formatting wouldn't make sense
and would continue to be
```
call(
parameter =>
long_body,
another_argument
)
```
N.B. Using the existing `alwaysBeforeCurlyBraceLambdaParams` configuration parameter is also possible but it magically fixed an error with …

Router: format lambda in 1-arg call as with braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

Fixes #1069
This commit produces no diffs on `scala-repos`.

FormatWriter: insert newline after packages #1069

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeMultilineDef.stat

Fixes #1240 
NB: this change produces no diffs on `scala-repos`.

Router: fix def body indent with a comment #1240

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Try.stat

Instead of maintaining exceptions to an otherwise mandated line break,
let's specify explicitly when this could happen. That is, rather than
break always except when followed by a parenthesis, we should break
only if followed by the finally clause.
Follow-on to #1554.

Router: fix split rule after catch in try

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Incorporates changes from #1386 and makes them compile on 2.11/2.12/2.13. The performance improvements are small but noticeable!
```
[info] Benchmark                          Mode  Cnt     Score     Error  Units
[info] Micro.ExtraLarge.scalafmtAfter     avgt   10   826.260 ± 139.865  ms/op
[info] Micro.ExtraLarge.scalafmtBefore    avgt   10   960.471 ± 157.597  ms/op
```

Performance improvements

---

project/Dependencies.scala

This release removes the awful usage of the global
`PlatformTokenizerCache` cache, which caused both correctness and
performance issues.

Upgrade to the latest Scalameta

---

.scalafmt.conf
project/plugins.sbt
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Edition.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ExpandImportSelectors.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-tests/src/test/scala/org/scalafmt/FidelityTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/Tabulator.scala

Formatter upgraded to 2.3.0-RC1

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/newlineBetweenCurlyAndCatchFinally.stat

Use the setting for 'else' after curly 'if' to determine whether to add
newlines before 'catch' and 'finally'.
Those who prefer
```
if (a) {
b
}
else c
```
over
```
if (a) {
b
} else c
```
likely also prefer
```
try {
a
}
finally b
```
over
```
try {
a
} finally b
```

Router: break between curly and catch, like else

---

bin/install-scalafmt-native.sh
docs/installation.md

Previously, the website did not document how to install the new GraalVM
native images that are automatically built by the CI. Now, the docs
highlight this feature and make it easy to install them into `$PATH` by
providing a copy-paste friendly `curl` command.
Users who don't trust curl can use the script as a starting point to
write their own custom install scripts.

Add installation instructions for scalafmt-native.

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/Scalafmt.java

I'm kind of lost in tests. I would need help with writing a test for ScalafmtDynamicDownloader, if necessary (I haven't found any).
I'm also struggling with sbt-scalafmt part. I can't find a way how to map resolvers configuration into list of string urls. Any ideas?

adding possibility to specify custom repositories for coursier (#1521)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

This PR fixes https://github.com/scalameta/scalafmt/issues/1593

Do not add a new line in multilevel chained package clause

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Scalafmt210.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/spaces/NeverAroundInfixTypes.stat
scalafmt-tests/src/test/resources/test/Dangling.stat
scalafmt-tests/src/test/scala/org/scalafmt/FidelityTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

This fix improves some formatting and also removes some idempotency issues while fixing the larger assign break.
* break after assign in infixSplit: https://github.com/kitbellew/scala-repos/commit/a318836fe35b44f62892d23c3aff6ba9bb0057a2?w=1
* handle split after "while ()": https://github.com/kitbellew/scala-repos/commit/bed9ada263f79577063aa60880579ae81f1c6ca3?w=1

FormatOps: allow break after assign in infixSplit

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat

Follow-on to #1551 
Diffs on `scala-repos`:
* fold lambda paren after matching delim: https://github.com/kitbellew/scala-repos/commit/2053d6754d2a62b9e65a6175ad32a43d87f09043?w=1
* get lambda if called in ApplyInfix: https://github.com/kitbellew/scala-repos/commit/04a7c21b5a72fdc90e686f1815c8f86816190204?w=1
* functionExpire for ApplyInfix: https://github.com/kitbellew/scala-repos/commit/7e791affa14beb02db9f741196bdcc842082879c?w=1
* functionExpire with case comment: https://github.com/kitbellew/scala-repos/commit/b199e6b3e2255c6c2a773e916dbbeb28f2bed508?w=1
* NB: scalafmt simply couldn't format one of the files before this change
* fix lambda block determination: https://github.com/kitbellew/scala-repos/commit/8114f8d8dd000907b9f3973ce5864a6cfb83a923?w=1
No `scala-repos` diffs on other …

Various bugfixes for single-arg apply of a lambda

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/FormatEvent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

They seem to bring about 5-10% speedup while running on `scala-repos`.
P.S. `bin/run_benchmarks.sh` doesn't seem to work, because `sbt test` keeps failing.

Some performance optimizations for FormatToken

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala

When using `stdin` as a command line flag the output is sent to stdout, in this
case the output should not be silenced as it is the formatting output. All other
output stays silenced as it goes to stderr.

Don't silence stdout when it is the only output

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/SearchState.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/optIn/SelectChains.stat
scalafmt-tests/src/test/resources/test/Dangling.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/src/test/resources/unit/Lambda.stat
scalafmt-tests/src/test/resources/unit/TermApply.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

We are also moving the optimal break point to before a close parenthesis
if a comment follows it and doesn't fit.
Since we don't break just before a comment, it occasionally led to very
long lines. While this change can't guarantee the lines won't be longer
than maxColumn either, they will be shorter because we will induce a
break before the close parenthesis:
instead of
```
a(b) // comment
```
we'll format as
```
a(
b
) // comment
```
An unexpectedly related (through failing idempotency checks) but somewhat different problem is with breaking on assign in apply; it's follow-on change to the feature introduced 2.3, and modifies
```
a(b = c) // comment
```
to (if the original form exceeds `maxColumn`)
```
a(b =
c
) // comment
```
or (if the previous form exceeds `maxColumn`)
```
a(
b = c
) …
```

FormatOps: consider comment for RHS optimal token

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/default/Advanced.stat
scalafmt-tests/src/test/resources/default/Try.stat
scalafmt-tests/src/test/resources/unit/If.stat

Fixes #271 #1002 #1043.
Follow-on to #1554.
The diffs on `scala-repos` (obtained by running 2.3.0-rc2 and this build independently on the original, never before formatted base code, and then comparing): https://github.com/kitbellew/scala-repos/commit/73a76cb8dc9e97be06497ece131b0131586ffaaa?w=1

Router: preserve single-line formatting for if/try

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

* If the block is part of an infix expression, rewrite only if it also contains an infix expression
* do not rewrite infix block if its closing brace is the first non-whitespace character on the line
* don't apply the special if-within-if logic when the nested expression is not `if`
* change how and when we remove newlines after a brace is removed
Fixes #1631.
Fixes #1633.

RedundantBraces: fix various bugs with general expressions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala
scalafmt-tests/src/test/resources/rewrite/SortModifiers.stat

Whether a bug or a feature, but for Mod.Annotation, syntax loses all NL tokens. So instead of tree.syntax, let's use tree.tokens.syntax which doesn't have that problem.
Fixes #1506.

SortModifiers: Use .syntax on tokens, not tree

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Without it, errors are reported with the wrong line (albeit without the
source file anyway).

Policy: always pass sourcecode.Line implicitly

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Case.stat
scalafmt-tests/src/test/resources/default/If.stat

We generally don't break on "} else"; however, if the closing brace does
not enclose the "if" block but is unrelated, we should include it.
Fixes #1413.
* find breakable else terms correctly
* https://github.com/kitbellew/scala-repos/commit/b20655f80996aa1ce1387cbd26fba4977c670477?w=1
* indentation for block within case
* https://github.com/kitbellew/scala-repos/commit/467d4f262d0b5963eff3a1742871d6942c035818

Router bugfix: break on else, indent for block within case

---

scalafmt-benchmarks/src/main/scala-2.12/benchmarks/MacroBenchmark.scala
scalafmt-benchmarks/src/main/scala/org/scalafmt/benchmarks/FormatBenchmark.scala
scalafmt-benchmarks/src/main/scala/org/scalafmt/benchmarks/MicroBenchmark.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/Scalafmt210.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/FidelityTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Create a new, package-private method `.formatCode` with the implementation based on the existing .format.
Make sure not to modify the existing interfaces of `.format` overloads, as they are externally expected (via reflection).
The bug was introduced in #1608 and removed the 3-parameter version of the `.format` overload as "unnecessary".
Fixes #1628.

Scalafmt bugfix: restore .format signatures while passing filename

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtVersion.scala
scalafmt-dynamic/src/test/scala/tests/ScalafmtVersionSuite.scala

Close https://github.com/scalameta/scalafmt/issues/1655
As described in the issue, before this PR, scalafmt-dynamic (and so scalafmt-cli, sbt-scalafmt, every module that depends on scalafmt-dynamic) couldn't resolve the SNAPSHOT version of scalafmt-core.
- Run `sbt publishLocal` and publish the snapshot version (e.g. `2.2.2-SNAPSHOT`)
- Set `version` field in `.scalafmt.conf` to `2.2.2-SNAPSHOT`
- Try to run scalafmt using CLI / sbt-scalafmt
got
```
org.scalafmt.cli.FailedToFormat: /Users/tanishiking/dev/src/github.com/tanishiking/scalafmt/scalafmt-tests/src/test/scala/org/scalafmt/util/Tabulator.scala
Caused by: org.scalafmt.dynamic.exceptions.VersionMismatch: Scalafmt version mismatch. Version in .scalafmt.conf is '2.2.2-SNAPSHOT' and running version is '2.2.2'.
at …
```

Enable to download and run snapshot version from dynamic

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/default/Idempotency.stat
scalafmt-tests/src/test/resources/default/If.stat
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/default/Unindent.stat
scalafmt-tests/src/test/resources/default/Val.stat
scalafmt-tests/src/test/resources/newlines/AlwaysBeforeCurlyBraceLambdaParams.stat
scalafmt-tests/src/test/resources/newlines/afterCurlyLambdaAlways.stat
scalafmt-tests/src/test/resources/newlines/afterCurlyLambdaNever.stat
scalafmt-tests/src/test/resources/newlines/afterCurlyLambdaPreserve.stat
scalafmt-tests/src/test/resources/optIn/SelectChain.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix3.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysOwners.stat
scalafmt-tests/src/test/resources/unit/ApplyInfix.stat
scalafmt-tests/src/test/resources/unit/Lambda.stat
scalafmt-tests/src/test/resources/unit/Trait.source

The rule applies only if `newlines.afterCurlyLambda` is either `never`, or `preserve` without a line break, and abides by `newlines.alwaysBeforeCurlyBraceLambdaParams`.
Also, make sure to clarify the other space rule for lambda to break on arrow before breaking on the closing brace, so that it doesn't end up with a lone break at the end.
This is a prerequisite to adding the rewrite rule requested in #1027. Also, fixes #965.
For `alwaysBeforeCurlyBraceLambdaParams = false`:
```
// new
a map { x => x }
// old
a map { x =>
x
}
```
For `alwaysBeforeCurlyBraceLambdaParams = true`:
```
// new
a map {
x => x
}
// old
a map {
x =>
x
}
```
* forbid multiline toks in single-line block: https://github.com/kitbellew/scala-repos/commit/2daf6cae8c63eeaef01ac32f2461d1a7d6c2540b?w=1 …

Router: allow single-line curly lambdas

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

Follow-on to #1660.
* RedundantBraces: treat ctor as a multi-arg apply: https://github.com/kitbellew/scala-repos/commit/431b849b502d3210a9bbfdfbe2351f378b9ad6ac?w=1
* RedundantBraces: rewrite single-line lambdas: https://github.com/kitbellew/scala-repos/commit/10b83aea95471cb7adffa5317472a7f10157776d?w=1
* RedundantBraces: remove block around an (argument): https://github.com/kitbellew/scala-repos/commit/cb746698aa3d2f53826f8df721ad9cbf2b2add57?w=1

RedundantBraces: update method body rewrite rules

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala

* Policy: return just the splits in the partial func
* the point of a policy is to narrow down the set of splits, there's no need to duplicate the logic of building up an object which contains the input format token and can then be fed into another policy
* Policy: make sure to extend expire in andThen
* combining two policies would occasionally fail since the expiration point of the second one was ignored
* Modification: optimize/cache newlines computation
* minor performance

Minor improvements to split, decision and policy logic

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Fixes #1321.
Rewrites `a({ b })` and `(a { b })` as `a { b }` (both are considered a single-arg `Apply` of a `Block`).
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/90e2f8b23ea114c5e15f0c7e8b9b1b2833f58121?w=1

RedundantParens: rewrite single-arg apply of block

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNever.stat

In order to avoid idempotence issues triggered by modified commas at the final stage of formatting, let's remove them in the beginning to have a clean format, and append as necessary.
This rule is only applied if the TrailingCommas configuration takes one of the mutating settings, i.e. always or never.
Fixes #1667.

Trailing commas: add a rewrite rule, remove first

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/AlignToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

That way, we'll preserve ordering and the mapping.
Fixes #1309.

ScalafmtConfig bugfix: read align tokens as seq, not set

---

docs/installation.md

A common formatting extension supporting a wide varity of languages.

Scalafmt is supported by format-all for emacs

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Super.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat

Just like #1551, we need to format ctor/init consistently.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/e5a3562989d7f02f4c348a0b730cc74ca9a1dfa4?w=1

Router: treat single-arg lambda of init like apply

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces2.stat

Output a single-line { a => b } as (a => b), as mentioned in #1027.
`scala-repos` diff: https://github.com/kitbellew/scala-repos/commit/1ba9dbff2ae0c1f977191b64725d3c6f9e180fd4?w=1
NB: We can't easily do the opposite, formatting multi-line paren lambdas using braces, it can sometimes lead to incorrect code:
```
a(x =>
1
+ 2)
```
is the same as
```
a { x =>
1 +
2
}
```
but not
```
a { x =>
1
+2
}
```

RedundantBraces: use () for {} one-line lambdas

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala

One of the patterns was present in both isDefnSite and isCallSite (not
sure why, and which of them should keep the pattern is a separate issue)
so it ended up twice in this class. Remove the second.

RewriteTrailingCommas: trivial, remove duplicate

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ExpandImportSelectors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortImports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala

Also, turn rewrites into sessions with the context instance.

Rewrites: traverse tree once, applying all rules

---

.scalafmt.conf
scalafmt-benchmarks/src/main/scala-2.12/benchmarks/MacroBenchmark.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-dynamic/src/test/scala/tests/DynamicSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Just applied last RC to source code
Is it missing from release notes that «Format single-line curly lambdas using parens» works only with `RedundantBraces` rule?

Self formatting with 2.4.0-RC2

---

scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

I think it's more reliable way to get resources. Should fix issue https://github.com/scalameta/scalafmt/pull/1681#issuecomment-583871622

Resource folder path resolution from classloader

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Let's extract the simple Dot patterns from a more complex select chain rule, as all the run-up ultimately becomes unnecessary and makes it a little less readable.

Router: extract simple T.Dot patterns before chain

---

scalafmt-tests/src/main/scala/org/scalafmt/util/DiffAssertions.scala
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/ManualTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/CanRunTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/DiffTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

While this approach will not make the test case itself clickable, any failures (which Intellij's runner will mark with `ScalaTestFailureLocation` and then parse to provide a clickable `... at (<link>)`) will have a link which will open the test file on the right line.

Tests: determine test's location, provide to Intellij

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

Fixes #1703 
* Router bugfix: split, indent comments consistently https://github.com/kitbellew/scala-repos/commit/93a939860e153783b1e3e6d79005d0ef2381a386
* TreeOps bugfix: find Init param group correctly https://github.com/kitbellew/scala-repos/commit/68cb5977aadcfc68466ebfff49e4e81e966f4987?w=1
* Router bugfix: consistently allow break on "(/**/" https://github.com/kitbellew/scala-repos/commit/3fd4a1a7241282b43aed2615b5383bc0f4588511?w=1

A couple of bugfixes in handling of first arg after "("

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat

Trailing commas bugfix: can't have trailing comma in `preserve` without a break

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/CanRunTests.scala

We can't rewrite a lambda unless it has parens around parameters or one simple parameter without a type.
Fixes #1707.
Fixes #1708.

FormatWriter: {} => (): don't rewrite some lambdas

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat

This case has apparently been deprecated in 2.13. Hopefully, not too many additional special cases remain.
Fixes #1708.

FormatWriter: don't rewrite {} => () in assignment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Lambda.stat

When lambda parameters are themselves functions and contained arrows in their type definitions, the code would locate the wrong arrow and then fail to break after it as no such break is defined in any rules.
Fixes #1714.

Router bugfix: find the correct lambda right arrow

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RedundantBracesSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

By default, it's enabled in edition 2020-01, just as before, but can be
disabled if necessary, as has been requested by several users.

RedundantBraces: add parensForOneLineApply flag

---

docs/configuration.md
docs/installation.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Edition.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/scala/org/scalafmt/EditionTest.scala

Fixes #1659. Fixes #1482. Helps with #1523.
Additionally, implement the `Edition.toString` method so that the automatic documentation which lists all possible options displays this value in a more user-friendly way. Also, implement edition using `java.time.YearMonth`.

Documentation: describe a few important parameters

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/FormatEvent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/Debug.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Removes some unused code or unnecessary complexity. Doesn't change formatting.
Precursor to the algorithm fix which addresses a host of "unable to format due to bug in scalafmt" issues, to be submitted after.

Various cleanup and refactoring changes in BestFirstSearch

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/newlines/afterCurlyLambdaNever.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat
scalafmt-tests/src/test/resources/vertical-multiline/VerticalMultilineDefnSite.stat

Currently, the algorithm would clear the search priority queue when the top candidate points to a new statement. Sometimes this leads to losing a viable path and the dreaded "Unable to format due to bug" error.
Rather than clearing the queue, let's maintain several generations of priority queues and create a new generation on a new statement, thus continuing to process subsequent states just like the old algorithm did but with the previously discarded states available as backup.
Apply this modification to top-level invocations only, so that nested calls will still terminate early; thus the backup candidates are really processed at the very end of the existing logic.
Fixes #448. Fixes #1462. Fixes #1485. Fixes #1599. Fixes #1717.
NB: `scala-repos` diffs, looks like they contain files …

BestFirstSearch: don't give up too soon

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Trait.stat

Prepare for a number of fixes which require a better understanding of a definition.
Also, we can vastly simplify the RewriteTrailingCommas logic immediately, and will be able to improve the FormatOps.getApplyArgs logic later, allowing us to tuck implicit in multi-arg calls or apply trailing commas to calls with a given arity.
No changes to tests or `scala-repos`.

TreeOps: structure the details of defns or calls

---

.github/workflows/release-drafter.yml

> The release drafter service has been discontinued in favor of a custom GitHub action that we haven’t setup in the Scalafmt repo (example https://github.com/scalameta/metals-languageclient/blob/master/.github/workflows/release-drafter.yml).
https://github.com/scalameta/scalafmt/issues/1711#issuecomment-586673599

Release Drafter workflow

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

Fixes #1720.
`scala-repos` diffs consists of one file only which couldn't be formatted previously: https://github.com/kitbellew/scala-repos/commit/3d4fb7b212874069deaf7c73eaf0b0e1d8810ec2?w=1

BestFirstSearch: if failed without a solution, retry without optimization

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala
scalafmt-tests/src/main/scala/org/scalafmt/util/DiffAssertions.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

*  HasTests: fix the line number computation
* DiffAssertions: compute diff once, swap comparands
* LoggerOps: log state and a shorter FormatToken

Various minor fixes to logging and tests

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: don't retry if didn't optimize

---

.github/workflows/ci.yml

openjdk11 tests fails with 
```
java.lang.OutOfMemoryError: Metaspace
[info]   at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[info]   at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[info]   at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[info]   at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[info]   at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
```

SBT_OPTS tuning

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala

Rather than enabling a split using a simple boolean flag, let's allow a split to be enabled in some cases. This will allow us to set up some splits which will not be used unless some policy in a specific context decided to use them (for instance, splits for ", {" that would be triggered only if `OneArgPerLine` policy is used). See #1722, will be used in that PR.
Also, make a few minor cosmetic changes.

Split: switch ignoreIf to tag, allows more control

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat

The `scalafmt` error described in #1599 turns out to be mainly due to the rule which formats multiple method arguments one per line. Router would attempt to format `, {` combination as a newline followed by the entire block on a single line, or a space without additional rules instead.
Two problems with this approach:
* because of some aspect of `BestFirstSearch` algorithm that I don't yet fully understand, having these two possible splits led to the search reaching a dead end before it attempted the space split 
* the expectation was that having additional splits could only lead to a *search state exploded* error, not this)
* removing the newline split (leaving the space split only) solved the problem
* also, in cases when the space split was chosen, the result wasn't guaranteed to have …

FormatOps: in one-arg-per-line, handle lbrace case

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Advanced.stat
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/Case.stat
scalafmt-tests/src/test/resources/default/Idempotency.stat
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/default/Unindent.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat
scalafmt-tests/src/test/resources/unit/Advanced.source
scalafmt-tests/src/test/resources/unit/TermApply.stat

Otherwise, because of the logic ignoring blocks within any argument, we
end up with an unintended bin-pack behaviour.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/96f7a0446bc95af3fe3a886afd4d01d5eb4c17ca?w=1

Router: for multiple args, all or one on a line

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Rather than returning the concatenation of all parameter groups, return the specific one.
With that, we can now definitively determine the number of arguments in the specific parameter group, rather than the total number across all groups as we did before. That is, in
```
def f(a: Int)(b: String, c: Boolean): Unit
```
we used to return 3 in getApplyArgs for both `(`, but would now return 1 and 2, respectively.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/68a90df4556bfa220ac81d57b301e1aecad35ed2?w=1

FormatOps: find the exact param group for each "("

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat

FormatWriter: do not rewrite {} => () around Defn

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

I propose to deprecate `poorMansTrailingCommasInConfigStyle` configuration because it was added before Scala 2.12.2 release with trailing commas support.
I don't know full history about this setting but I think that it isn't actual now.

poorMansTrailingCommasInConfigStyle deprecation

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/VerticalMultiline.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/Class.stat
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiers_bug_1148.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiers_bug_1148_implicit_first_in_order.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysVerticalMultilineAtDefnSite.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNever.stat
scalafmt-tests/src/test/resources/unit/TermApply.stat
scalafmt-tests/src/test/resources/vertical-multiline/afterImplicitKW.stat
scalafmt-tests/src/test/resources/vertical-multiline/beforeImplicitKW.stat

This will format "implicit" on the same line as the opening paren, if possible. It will also break after the "implicit" unless all parameters fit on one line.
Fixes #1362.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/eea2e89051a744b4c13c6e844aaf54ebaa12d64b?w=1

Router: handle implicit in non-vertical-multiline

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/VerticalMultiline.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/afterImplicitKW.stat
scalafmt-tests/src/test/resources/vertical-multiline/excludeDanglingInDef.stat

With the default of empty, this doesn't change any existing formatting. However, just like with `VerticalMultiline`, it will allow users to reduce effect of `danglingParenthese.defnSite = true`.

DanglingParentheses: move `exclude` list from VerticalMultiline

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/afterImplicitKW.stat
scalafmt-tests/src/test/resources/vertical-multiline/excludeDanglingInDef.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

If `optin.configStyleArguments` is set, incorporate the setting into the vertical multiline logic.
For the purposes of this integration, we'll assume that config style means there's a line break after the opening parenthesis (without requiring dangling, or a line break before the closing one), and `optIn.configStyleArguments` is set.
Fixes #1539.

VerticalMultiline: check config style

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

The flag can be:
* _classic_ (unspecified): consistent with the current mixed behaviour
* _keep_: will try to preserve existing line breaks
* _fold_: removes some line breaks, for a more compact look
* _unfold_: inserts line breaks as appropriate, expanding
Also, add empty test suites for each value of this new flag. We will be adding test cases and the code using the flag in the next commits.
Towards #1627.

#1627 [01]: ScalafmtConfig: flag to ignore input line breaks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/Val.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/src/test/resources/unit/ApplyInfix.stat

This approach is better than applying a higher cost to blocks abutting an infix. Fixes a number of line-too-long problems and also avoid line breaks when they are not necessary.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/787fbfa747792b9cf56034bee8f41e3909ac3362?w=1

Router bugfix: extend line break past infix for any block

---

docs/configuration.md
docs/installation.md

Attempt to clarify sbt integration versioning by `.scalafmt.conf` example near to plugin installation section.
Also `rewriteTokens`: incredibly useful config still not presented on the site.
Grammar check, please :)
Related to https://github.com/scalameta/scalafmt/issues/1523

Documentation improvements

---

.github/workflows/ci.yml

It may be a source of incorrect website rendering

Fetch tags on CI

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/Idempotency.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/default/Semicolon.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/src/test/resources/unit/ApplyInfix.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

Follow the post-optimal states on the same line while we get exactly one active split to use; if the line overflows, don't mark optimal as found. This way, we are more likely to fit within the column limit and select a better solution.
Also, now that BestFirstSearch logic dealing with optimal tokens has been improved, the suboptimal special case handling of infix expressions around blocks is no longer needed.
* BestFirstSearch: check optimal tok not to overflow: https://github.com/kitbellew/scala-repos/commit/fd8b18e8d4638c73724a343b343a9e9c83151c00?w=1
* Router: always use optimal token within infix op: https://github.com/kitbellew/scala-repos/commit/5a8132dc0f796690190079d2b8be6fd5d01398c1?w=1

BestFirstSearch: check optimal token not to overflow

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

While previously we were trying to keep blocks without line breaks if that's how they were originally input, now we actively attempt to take a multi-line representation and fold it into a single line (fold), or take a single-line representation and unfold it into multiple lines (unfold). In the [keep] case, we'll keep the line break if it was there before.
Fixes #271 #1002 #1043
Helps with #1627
* _classic_: none
* _keep_: https://github.com/kitbellew/scala-repos/commit/51c4d1e3ad2cdbcdce2ba29aea78cb1209d25f94?w=1
* _fold_: https://github.com/kitbellew/scala-repos/commit/242d091577f73a3e3f3e74c29458e76c79145def?w=1
* _unfold_: https://github.com/kitbellew/scala-repos/commit/0a882e3102bf94c134d5d0e07904076ee0cb2add?w=1

#1627 [02]: Router: ignore line breaks for blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

For semicolons, we can `unfold` by adding a line break. In the `fold` case, we can try to remove a line break but that doesn't really look that good, plus semicolons shouldn't generally be used anyway.
* _unfold_: https://github.com/kitbellew/scala-repos/commit/2ffa7f60a0aaf4443ceb5af8d407112d827af87d?w=1
* others: unchanged
Helps with #1627

#1627 [03]: Router: newlines.source=unfold for semicolons

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/Case.case
scalafmt-tests/src/test/resources/default/Case.stat
scalafmt-tests/src/test/resources/newdefault/CaseNoAlign.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultipleDanglingParens.stat
scalafmt-tests/src/test/resources/unit/ApplyInfix.stat
scalafmt-tests/src/test/resources/unit/Case.case

Fixes #1244. `scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/2877c2cc11ac8f6678023498766614669dfefa44
The existing logic was suppressing case pattern indentation which led to incorrect formatting relative to the end of the pattern.
Specifically, here's a problematic pattern:
```
case pattern(
argument // indent 1: explicitly suppressed
) // closing: clause indentation
infix another( // indent 2: increased to distinguish from "if"
...
) if somethingLong
.methodCalledBySomethingLong =>
body
```
First, we need to restore indent 1. Second, we need to address indent 2 and there are several options:
* we choose NOT to keep it different from `if`, as `if` can be easily determined as the last line at that level of indentation; that way, we don't add extra indentation for …

Router: modify indent of case clauses consistently

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/unit/FormatOff.stat

Fixes https://github.com/scalameta/scalafmt/issues/1424

"// format: off" enabled for comments, literals, etc.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Modify breaks around control expressions (`if-else`, `for`, `while` etc.) and their bodies.
* `classic` and `keep`: unchanged
* `fold`: https://github.com/kitbellew/scala-repos/commit/50420e514f66910d77ed8a549c56ee212350a329?w=1
* `unfold`: https://github.com/kitbellew/scala-repos/commit/f3e2e427ab5b3b5f2ecf29f4d84679bd0061b1e2?w=1

#1627 [04]: Router: ignore line breaks in if-else and bodies

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/default/Advanced.stat
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

For fold/unfold cases, handle 'if' with/without braces consistently.
Also, use alwaysBeforeMultilineDef consistently for `def`; for some reason, it was not applied when def body ended in a closing `}` or used config-style parens.
* Router: use alwaysBeforeMultilineDef consistently: https://github.com/kitbellew/scala-repos/commit/21a7ff6cfbd0ef6faeb5e34f085feb75154f1e34?w=1
* Router: ignore line breaks in def/val assignments
* _classic_: unchanged
* _keep_: https://github.com/kitbellew/scala-repos/commit/c6f7305073e37113589c38f5abc5098f3273663e?w=1
* _fold_: https://github.com/kitbellew/scala-repos/commit/4761e37e253bab868958ab62ccd92bbdc141989f?w=1
* _unfold_: https://github.com/kitbellew/scala-repos/commit/459ab1872163c84013c8b0a8aecb703c8f1a3884?w=1 …

#1627 [05]: Router: ignore line breaks in def/val assignments

---

bin/test-release.sh

I think scalafmt-cli transitively brings in all the publishable
artifacts.  This kind of script is helpful just to sanity check that the
full cross-build released.

Add script to test that a release succeeded

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/AlignByRightName.stat
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

Fixes #1783 
TL;DR
```scala
//before
libraryDependencies ++= Seq(
"a"   % "x" %% "1",
"b" %%% "y"  % "2.2.2.2" % Test,
"c"  %% "z"  % "3" % Test
)
//after
libraryDependencies ++= Seq(
"a"   % "x" %% "1",
"b" %%% "y"  % "2.2.2.2" % Test,
"c"  %% "z"  % "3"       % Test
)

Align lines with different columns count

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtTest.scala
scalafmt-tests/src/test/resources/default/Val.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Actually, line breaks are already ignored in `rhsOptimalToken` except for a couple of bugs:
* TokenOps bugfix: correctly identify a blank line: https://github.com/kitbellew/scala-repos/commit/b89051f7094a0117560431af751b56f9e4faee79
* FormatOps bugfix: relax ")}" in rhsOptimalToken: https://github.com/kitbellew/scala-repos/commit/1e75fbecd3f8e91807aa188956c3a71936a991a2

#1627 [07]: FormatOps: ignore line breaks in rhsOptimalToken

---

bin/install-scalafmt-native.sh
docs/contributing-scalafmt.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Helps with https://github.com/scalameta/scalafmt/issues/1769#issuecomment-599266171
Native Images were broken after 2.3.3 release.
We have GraalVM **build** on CI, but images can fail at runtime. And GraalVM is not completely stable technology, so builds _will_ be broken time to time. Any ideas how to test it?

GraalVM Native Image fix

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Bundling together the annotation modifiers and self-annotations. Helps with #1627.
`scala-repos`:
* `fold`: https://github.com/kitbellew/scala-repos/commit/b8f351c03ae39b5a08e74f2b20f682e9da72dd86
* `unfold`: https://github.com/kitbellew/scala-repos/commit/d5a8edca1d1c7e8f73120483b545db056eca889c
* rest: unchanged

#1627 [08]: Router: ignore line breaks in annotations

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

* `fold`: https://github.com/kitbellew/scala-repos/commit/ad939026abd0c6c0eafeb4845f1d91987ecade4f
* `unfold`: https://github.com/kitbellew/scala-repos/commit/d058de644b623a84da6e1c73892fd524bef468d0
* rest: unchanged

#1627 [09]: Router: ignore line breaks in case clauses

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source.source
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

* _fold_: https://github.com/kitbellew/scala-repos/commit/09d4b43104eafdf9784b3397bc3495bd34ef7218
* _unfold_: https://github.com/kitbellew/scala-repos/commit/15d30f82ad4090d9d68f0c1dfd9cb9e8ae954d70
* _keep_: https://github.com/kitbellew/scala-repos/commit/b3267ad3da764df77385ec4a6ce4df2da47a5aad
* _classic_: unchanged

#1627 [10]: Router: ignore line breaks in select chains

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/align/ArrowEnumeratorGenerator.stat
scalafmt-tests/src/test/resources/scalajs/For.stat
scalafmt-tests/src/test/resources/unit/For.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Fixes #1256
Before:
```scala
for {
myLongBooleanValue <- some.very.very.very.very.very.very.long.option
.map(_ => true)
myResult = if (myLongBooleanValue) compute_one_thing
else compute_another_thing
} yield myResult
```
After:
```scala
for {
myLongBooleanValue <- 
some.very.very.very.very.very.very.long.option.map(_ => true)
myResult = 
if (myLongBooleanValue) compute_one_thing
else compute_another_thing
} yield myResult
```
Especially I don't like current formatting of long `if-else` in for comprehensions. `else` after split located on the same column with left-side identifiers. It makes code reading difficult.
scala-repos vs master: https://github.com/poslegm/scala-repos/commit/0addbc83430c0bb6d30cfc38daa862fb69741ba8

Preserve newlines in for comprehension generators and values 

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

#1627 [11]: Router: relax restrictions on breaks within interpolate

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/align/ArrowEnumeratorGenerator.stat
scalafmt-tests/src/test/resources/default/For.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scalajs/For.stat
scalafmt-tests/src/test/resources/unit/For.stat

Helps with #1627. `scala-repos` diffs:
* _fold_: https://github.com/kitbellew/scala-repos/commit/496e6c6b0d8ec3e8eb1b8d91f618a42a3a3617e4?w=1
* _unfold_: https://github.com/kitbellew/scala-repos/commit/9043367b87139aded36e6b6c1737f70d3c874275?w=1
* _keep_: https://github.com/kitbellew/scala-repos/commit/52486acaa1e141dbc8805d0c57e542c5f2f4a67f?w=1
* _classic_: unchanged
Also, add a follow-up to changes in #1795, diffs at https://github.com/kitbellew/scala-repos/commit/5e73de35b1e365ee2ee17ba273f344ea6b71f1fc
* the closing paren in `ForYield` was unindented late so there was an extra indentation in some cases
* simplify the delayed arrow logic (in case clauses, the rule applies it on `case`, while the enumerator rules is applied just before arrow, hence it can simply be done right after)

#1627 [12]: Router: ignore line breaks in enumerators

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

This enables the alternative formatting rules even if the edition is
before 2020-03. Helps with #1627.

#1627 [13]: Router: ignore line breaks in comma-separated args

---

docs/configuration.md

Current example doesn't illustrate how `danglingParentheses` works:

Fixed unclear example for danglingParentheses in documentation

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/default/If.stat
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/default/Unindent.stat
scalafmt-tests/src/test/resources/default/Val.stat
scalafmt-tests/src/test/resources/newlines/AlwaysBeforeCurlyBraceLambdaParams.stat
scalafmt-tests/src/test/resources/newlines/afterCurlyLambdaNever.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/optIn/SelectChain.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix3.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysOwners.stat
scalafmt-tests/src/test/resources/unit/ApplyInfix.stat
scalafmt-tests/src/test/resources/unit/Lambda.stat
scalafmt-tests/src/test/resources/unit/Trait.source

Should fix #1826 for default behavior
Lambdas don't squash with default config, but «braces to parens» works with `fold`:
```
<<< squash
newlines.source=fold
rewrite.rules=[RedundantBraces]
===
files.test("basic") { name =>
assertEquals(name, "basic-setup")
}
>>>
files.test("basic")(name => assertEquals(name, "basic-setup"))
```
- squash blocks with `fold`:
```
<<< failing now
newlines.source=fold
===
files.test("basic") {
assertEquals(name, "basic-setup")
}
>>>
files.test("basic") { assertEquals(name, "basic-setup") }
```
- note at the website documentation that entire power of `RedundantBraces` can be accessed only with `newlines.source=fold`
@kitbellew what do you think?
Also I really like the idea of keeping newlines configuration in universal formatting style sets like `fold`, …

Hide lambda body squashing under newlines.source=fold

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/unit/Import.source

With `optIn.forceBlankLineBeforeDocstring=true`, in addition to forcing a blank line before docstring, we also mistakenly removed one after it. Fixes #1426.

TokenOps bugfix: logic for newline on docstring

---

docs/configuration.md

Editions are a failed experiment. My original motivation to add editions
was to make it possible to make improvements to the default formatting
behavior without introducing a new configuration option in every PR.
This made sense when Scalafmt was evolving slowly, but lately the
project has been moving much faster thanks to the heroic efforts of
Albert Meltzer and other contributors.
I'm happy that Scalafmt is still evolving and I like many of the new
changes. However, the latest improvements don't respect the `edition`
setting, which is understandable because the changes are large.
I don't want to remove editions because that would break user's
configuration files. Instead, this commit just updates the website to
say that editions are no longer used.

Sunset editions

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/StripMargin.stat

Previously, using `assumeStandardLibraryStripMargin = true` (which means
the `.stripMargin` method was not redefined by the user and thus assigns
no special meaning to indentation preceding the `|` character) resulted
in aligning the pipe character with the end of the opening triple-quote.
Now, one can optionally set `align.stripMargin = false` to use a 2-space 
indentation offset relative to the start of the opening line instead.
```
// With align.stripMargin = true
val x = """
|Hello world!
|""".stripMargin
// With align.stripMargin = false
val x = """
|Hello world!
|""".stripMargin
```
Also, find the string margin char rather than assuming it's always `|` and inspect any parameter to `.stripMargin`.

Align strip margin: allow disabling the alignment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

This is required to introduce infix formatting (because it occasionally starts a statement). This also simplifies the logic of identifying docstrings.

FormatOps: don't start a statement on a comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala

Closer inspection reveals that there's a peculiar inconsistency in how splits are sorted/prioritized (see scaladoc in Split.scala). Changing sorting to make it consistent produces significant changes in formatted output. For now, let's explain this inconsistency in the code.

State: clarify how priority is determined

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source.source
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

* Router: prefer break before than inside ApplyType
* `fold`: https://github.com/kitbellew/scala-repos/commit/748e5c345f4a9677ce82b08f8c6fa2ca90f0b2de?w=1
* `unfold`: https://github.com/kitbellew/scala-repos/commit/c2aea7c7444b9d6f0441548c217a03065a511bdb?w=1
* rest: unchanged
* Router: use "symbolic.xx" rules for source=classic
* `fold`: https://github.com/kitbellew/scala-repos/commit/90a2a3dae89dc3a2420a5e86cbd486cfaba2ad0f?w=1
* `unfold`: https://github.com/kitbellew/scala-repos/commit/9242b4e760b4a0fbac07e1b7fdead75e68377857?w=1
* `keep`: https://github.com/kitbellew/scala-repos/commit/20e2d9517f3fbc412a5166d177826a96242fef84?w=1
* `classic`: unchanged
* Router: fix the 'if' in the body of a case clause
* all unchanged but would fail later, with infix changes

#1627 [17]: Several fixes for ApplyType, symbolic select, if in case clause

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Indent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source.source
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/test/DynamicStyle.stat

Add the `newlines.afterInfix` parameter to allow formatting of infix expressions and optionally breaking lines after an infix operation (which appears to be always safe, unlike before it); enable it for `newlines.source=fold,unfold`. The behaviour and specific parameters/values will be defined in a separate PR containing the documentation.
* Infix bugfix: handle Type.ApplyInfix correctly
* `unfold`: https://github.com/kitbellew/scala-repos/commit/6377998f6d7f4c3b05d7b9dbb8486e5adba8b9a0
* rest unchanged
* FormatOps: ignore line breaks in infix expressions
* `fold`: https://github.com/kitbellew/scala-repos/commit/1a055b5d397d1f745b016813ea5c6f611a74ddaf
* `unfold`: https://github.com/kitbellew/scala-repos/commit/edbae8c98e30637849da986dd281f1d800423887 …

#1627 [18]: FormatOps: ignore line breaks in infix expressions

---

docs/configuration.md

#1627 [19]: Documentation: describe `newlines.afterInfix`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/VerticalMultiline.scala
scalafmt-tests/src/test/resources/vertical-multiline/afterImplicitKW.stat
scalafmt-tests/src/test/resources/vertical-multiline/beforeImplicitKW.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

As these parameters haven't yet been released, let's consolidate these two into a single multi-valued parameter. There are other, unrelated parameters which also follow the same before/after logic.

Newlines: implicitParamListModifier to replace two

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/default/Trait.stat
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

When writing newlines before a token, check whether the previous token ended a multi-line top-level statement and optionally add a double.
Fixes #1653.

Newlines: allow break after top-level statements

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtConfigTest.scala

For instance, we might want to use a slightly different configuration
for `*.sbt` files, or those under `src/test/scala`.

ScalafmtConfig: allow overriding per file pattern

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/DynamicStyle.stat

Fixes #1861 
Fixed for alignment. But global problem is still here:
1. every contributor and code-reviewer can forgot the `styleMap` and look at the `initStyle`;
2. There is no documentation about what configs can't be overridden.
File override looks like more reliable and simple mechanism. What do you think, should we continue to support config overrides for code blocks or deprecate it in favor of file override?

Fixed alignment overriding

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/default/Comment.stat
scalafmt-tests/src/test/resources/test/StripMargin.stat

`align.stripMargin=false` incorrectly handled interpolated strings:
* strip margin character was incorrectly determined (`|` was always assumed);
* strip-margin lines were not indented at all.
As a side effect of this fix, we are also fixing the bug with nested comments which were incorrectly formatted.
Follow-on to #1837.

Router: fix strip margin in interpolated strings

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/WriteMode.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

This will allow returning a non-zero exit code not just for `--test` mode.
Also:
* verify conflicting options aren't used (`--test` or `--check` vs `--list` vs `--in-place`)
* fail fast in core runner when `--check` is used (only dynamic runner used to do it)
Fixes #928 #1291.

CLI: add explicit flag --reportError to exit 1 on malformatted code

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Also rename so it doesn't convey the "memo" meaning anymore.

Router: remove unnecessary splits cache, used once

---

docs/installation.md

install-scalafmt-native.sh is a Bash script and,
besides just having a Bash shebang, contains
```
[ "$(uname)" == "Darwin" ]
```
which is valid Bash, but not valid sh.
(See https://stackoverflow.com/a/2011170/7954504)

[docs] Pipe Bash script to Bash, not sh

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

This doesn't address the newlines.source=classic case as it follows a vastly different execution path. Helps with #1334.

Router: indent comments in the middle of a select

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Fixes bug introduced in #1888.

Router: force indent before comment, not break

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/binPack/TermNameList.stat

Now that we have fileOverride which can be applied to tests, one thing that is frequently needed in tests is setting up a number of instances or parameterized tests with multiple parameters, leading to extremely vertical formatting for what is essentially not code but configuration.
For that case, allow a special form of binpacking which simply formats all literal arguments on one line, even if it overflows maxColumn.

BinPack: allow single-line formatting of literals

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Literals, names, case clause conditions, val/def body (in this latter case, use the partial function to ensure the body wouldn't be amended twice). Also, remove inner parens.
Fixes #1895.

RedundantParens: support additional patterns

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/test/StripMargin.stat

Rather than basing the indent on the `Interpolation.Part` (which might be preceded by an unrelated `Interpolation.Start`), find the containing `Term.Interpolate` instead.

FormatWriter: fix indent for complex interpolation

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/VerticalMultiline.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/vertical-multiline/afterImplicitKW.stat
scalafmt-tests/src/test/resources/vertical-multiline/beforeImplicitKW.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

Rename the current parameter appending _Force_, and add the _Prefer_ parameter as an alternative, to indicate where the break is preferred (rather than required).
`implicitParamListModifierPrefer = after` is equivalent to current `implicitParamListModifier = []`, while `implicitParamListModifierPrefer = before` restores the functionality available in 2.4.2, which was lost while combining with the vertical multiline more aggressive approach.

Newlines: add flexibility to implicitParamListModifier

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/FilterMatcher.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtSession.java
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtSessionFactory.java

- `ScalafmtSession`: add an interface for batch format. If we need to format a number of files using the same exact scalafmt configuration, let's create a session.
- This will also allow us to filter inputs based on the project files which was not available and led to dynamic runner loading and formatting all files, including those not covered by the configuration.
- `ScalafmtDynamicRunner`: pre-filter based on customFiles if specified.
- `ScalafmtDynamicRunner`: try to use `ScalafmtSession` to avoid loading unnecessary files
Fixes #1460.

ScalafmtDynamicRunner: read and format only matching files

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

Until scala 2.13, removing braces around partially enclosed (paren or brace) `try` body isn't supported. See https://github.com/scalameta/scalameta/issues/2031.

RedundantBraces: fix try with partially enclosed expressions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/AlignToken.scala
scalafmt-tests/src/test/resources/align/defaultTokenOwners.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

Fixes #1896
Motivation described in the issue. Now users don't need to copy-paste
token owners from sources to get optimal alignment for dedicated tokens.
It will slightly change the value of user configs so need to be described in release notes.

Usage of default align token owners

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Also, remove unicode matching for space as unnecessary.
Follow-on to #1911, discussion in #1418.

FormatWriter: use `\h` for horizontal whitespace

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/StripMargin.stat

In #1911, by switching to `^` anchors, we introduced a bug.

FormatWriter bugfix: add margin in the middle only

---

docs/configuration.md

Documentation for `newlines.alwaysBeforeMultilineDef`.
The new section clarifies that the new line is added before the def's method body, not the def itself.

Documentation: add newlines.alwaysBeforeMultilineDef

---

docs/configuration.md

It split topLevelStatements and topLevelStatementsMinBreaks.

Documentation: move alwaysBeforeMultilineDef

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/align/AlignByRightName.stat
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/align/TrollAlignment.stat
scalafmt-tests/src/test/resources/align/defaultTokenOwners.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

To avoid aligning unrelated locations, don't compare just the depth from root. Instead, look for specific block/template/etc which logically contains the given expression and any "siblings" to align against.
Also, we'd determine the count of matches between two consecutive lines, only to get the maximum across the block. However, in order to avoid considering non-matching candidates, let's truncate the candidates when they don't match.
Fixes #1921.
Fixes #1896.

FormatWriter: no arbitrary depth to match align

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

To support this, also fix a couple of issues:
* include align gap in width:
* because we sort on the width, we might end up with (width+gap) for the currently widest alignment spot to be less than for another, with a smaller width.
* stop align container search
* there's a different class of containers (currently, "case"), which would only serve as a container for tokens which are formatted below it, and for tokens on the same line, we would continue the search, so that those tokens would align together with the case arrow.
Fixes #1504.
Fixes #1811.
Fixes #1841.

FormatWriter: optionally support multiline align

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/default/Comment.stat
scalafmt-tests/src/test/resources/spaces/TrailingWhiteSpace.stat
scalafmt-tests/src/test/resources/test/StripMargin.stat
scalafmt-tests/src/test/scala/org/scalafmt/CommentTest.scala

* The primary purpose of this PR is simplify two regular expressions
(regexen). One used by `leadingAsteriskSpace` and the other by
`compileStripMarginPattern`.
Discussions about readability are always subjective. I believe
that removing the positive and negative lookaheads makes it
more likely that the next maintainer will be able to read and
comprehend the code.
Discussions about runtime performance improvements without
demonstrable data are worth than useless.  lookaheads are
known to have a high runtime cost. It is believable, but not
asserted by this PR for lack of evidence, that the code of this
PR will have better performance characteristics.
*  Unicode whitespace handling was added, along with test cases.
* This PR supersedes the Work In Progress PR #1924. It has
benefited greatly …

FormatWriter: simplify two regular expressions; fix pipe char bug

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

If there's a newline before the infix operator, parens are required.

RedundantParens: may not be redundant around infix

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-tests/src/test/resources/binPack/ParentConstructors.stat

As it stands, using any dialect with `allowTraitParameters = false` leads to a problem (including Scala211, Scala212 and even Scala213), and only default and Dotty dialects work correctly.
Our code, in multiple places, expects the `extends` keyword to be owned by the `trait` tree whereas for older dialects `scalameta` assigns it to `Name.Anonymous` (which is owned by `Init` and only then the trait).
For formatting purposes, we can leave it to the user's `scalac` to determine whether this specific feature (`allowTraitParameters`) should be supported; enabling for formatting purposes only doesn't change how the code is parsed when this feature _is not used_.

ScalafmtRunner: fix handling of trait "extends"

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

Non-block, even if multiline, definitions are still allowed.

FormatWriter: don't align `Defn` with `Block` as body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

We use this method to determine whether to flush the align block, and it didn't work correctly on a comment following a blank line.

FormatWriter: use getAlignContainer to flush on comments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Fixes #1953.
Helps with #1952.

RedundantBraces: don't rewrite anon infix funcs

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-if.stat

Previously, we'd check only the first if for existence of an else, to see if braces around it can be removed. Now let's traverse the nested ifs to make sure all of them have an else, otherwise don't rewrite.
Fixes #1956.

RedundantBraces bugfix: skip deep if without else

---

docs/installation.md

Documentation: old scalafmt plugin is deprecated

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala

When receiving data via stdIn and printing to stdout don't print info messages to stderr. Stderr output might be used to detect failure, info messages (like "Reformatting..."). The alternative is to use --quiet which also removes valid error messages.
The use-case here is the integration into emacs format-all plugin, which is currently using `--quiet` to silence errors. Ideally it should report the errors on failure, but not show info output on every format.

When using in pipeline don't print info to stderr

---

docs/installation.md

Also, make the coursier examples directly usable via copy-paste, update the installation link and use scala 2.13 in examples.

Documentation: retire Homebrew, point to coursier

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat

Do not force a break there, as that is inconsistent with keep.
Fixes #1518.

#1627 [22]: Router: preserve split after `=>` in source=keep

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/unit/Package.source

Our comment-space-and-asterisk-matching regular expression was modified to avoid lookaround constructs, but that inadvertently introduced a bug.
When the comment line contains just a single asterisk, the character that follows it is the newline; that newline should be included as the last character of one regex match and then as the first character of the next match. Alas, that doesn't happen.
Therefore, restore the positive lookaround constructs to avoid this bug.
While it's not clear how properly used lookaround constructs should affect performance when compared to the same expression being captured, let's also add possessive quantifiers to improve matching performance.

FormatWriter bugfix: comment format on lookaround

---

docs/configuration.md
scalafmt-docs/src/main/scala/docs/ScalafmtModifier.scala

Also, fix bug in mdoc ScalafmtModifier which didn't remove the newline
preceding the code example prior to passing to the formatter. Without
it, `docstrings.oneline` formatting examples didn't work.

Documentation: expand docstrings

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Also, describe `binPack.parentConstructors`. Fixes #1973.

FormatOps: for source=fold, compact extends/with

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/optIn/Annotation.stat

As a follow-up to #1979, allow specifying the entire `extends`/`with` chain on one line using new values of an existing `binPack.parentConstructors` parameter.
The two new options allow specifying the chain on one line if fits, either always or only when the primary constructor also fits on one line. For example:
```
class Foo(a: Int, b: Int)
extends Bar with Baz
```
vs
```
class Foo(
a: Int,
b: Int
) extends Bar
with Baz
```

Router: allow folded `extends` if ctor is folded

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Lambda.stat

FormatOps: fix finding `=>` in lambda without args

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat
scalafmt-tests/src/test/resources/unit/Package.source
scalafmt-tests/src/test/scala/org/scalafmt/CommentTest.scala

* rename to `JavaDoc` to `Asterisk`, and `ScalaDoc` to `SpaceAsterisk`; keep old names for compatibility
* add a new style, `AsteriskSpace`
* clean up text after `*`, adding leading space as needed, removing redundant blank lines
* in `Asterisk` style, to get proper alignment, start text on the second line (what the linked issue called _burning the first line_)
Fixes #891.

Docstrings: rename styles, clean up text after `*`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/unit/Comment.stat

Also, allow formatting text with additional space indentation after the
asterisk.

FormatWriter: fix off-by-one bug in comment wrap

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/unit/Comment.stat

It wouldn't process the first delimiter correctly and end up adding an extra asterisk.

FormatWriter bugfix: comment with empty first line

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

Now that scalameta in 4.3.13 supports parsing of docstrings, let's use that and format.
Fixes #1387.
Fixes #1887.

FormatWriter: format multiline docstrings

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/StripMargin.stat

FormatWriter bugfix: align strip margin in `s"""|`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

We access it frequently, and constructing it is not free. Should help with #1949.

FormatToken: store the syntax of tokens in meta

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/Trait.stat

For traits/classes/method calls etc., the number of type parameters was identified incorrectly, instead using the number of constructor parameters.
The algorithm, as written, distinguishes between "not one" and "not many" (thus covering zero in both cases); so in cases where these flags were different for type parameters and apply/ctor parameters, type parameters were not formatted correctly (when the method had one type and one argument, or multiple types and multiple arguments, formatting worked as expected).
- FormatOps: get TParams correctly, not the Paramss
- https://github.com/kitbellew/scala-repos/commit/ffe29bb89a70e94c918adf608694561aa9b2e43b
- Router: exclude no-arg apply from a split
- https://github.com/kitbellew/scala-repos/commit/5c2644ba026f7bc2bf9537154 …

FormatOps bugfix: get TParams correctly, not the Paramss

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Having a separate, slightly different rule was leading to a number of idempotence issues.
The idea is that if the primary rule produces a config-style formatting, it must follow the same policy as one that had been set by the earlier config-style rule.
Fixes #1798.
Fixes #1801.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/4e21556434e9512246bb44382b0beb651fa1d80f

Router: merge config-style rule into others

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

If this flag is set, we must preserve a break if it's there. Therefore, we can't "tuck" a Newline into a NoSplit as it both violates the flag and leads to non-idempotent formatting.
Fixes #1802. Fixes #1803. Fixes #1804.

Router: idempotence of breakChainOnFirstMethodDot

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/String.stat
scalafmt-tests/src/test/resources/unit/Annotations.stat

Currently, multiline strings are handled inconsistently; computation of state columns also assumes that every line is aligned on the opening quotes, whether or not there is a margin symbol (`|`) and whether various margin-handling flags are set.
Instead, try to estimate the length of each line post-formatting and use that in computing the columns.
Fixes #1640.
- Router: no multiline tokens in extends/with chains
- https://github.com/kitbellew/scala-repos/commit/82307937bca8f88d24b03caa863e2ccdb8c1709e
- Router: no multiline tokens in select chains
- https://github.com/kitbellew/scala-repos/commit/bbf3b988cd3d4a09f7def2b6468db4d0c1bf6ad8
- Router: no multiline tokens in yield
- https://github.com/kitbellew/scala-repos/commit/6324b327d3ea49ca4116a280a8fcfce8fb669d8a
- …

State: fix column positions for multiline strings

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/align/ArrowEnumeratorGenerator.stat
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/newdefault/SearchState.stat
scalafmt-tests/src/test/resources/test/Dangling.stat

When the flag is on, penalize break, to avoid idempotence issues; otherwise, after the break is chosen, the flag prohibits nosplit. Fixes #1799.
*No* changes in `scala-repos`.

Router: penalize NL on breakChainOnFirstMethodDot

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ModExt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/Lambda.stat

Currently, newlines can be optionally replaced with a space or nosplit. However, the problem is that the replacement should not come with the same set of indents (or, rather, add a shorter negative indent).
Also, move handling of the replacement into State, from FormatWriter.
Fixes #1400.

Split: represent a newline alternative differently

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

Upgrade to scalameta 4.3.15 to get the updated scaladoc parser.

Scaladoc: support gaps in code, refs with punctuation

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Previously, if specific files were provided on the command line, they would be formatted regardless of any project filters.
Here we add an option to continue applying project filters in that case.
Fixes #1964.

ScalafmtRunner: respect filters with custom files

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/XmlLiterals.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Indent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ModExt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/unit/Xml.stat

It involves finding the indentation used within the xml literal and then applying it to the scala code within. We will use the ability to ignore previous indents as this indentation is not relative but absolute.
Fixes #1882.

Router: allow relative formatting of spliced XML

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

FormatWriter: fix handling of one-line docstrings

---

docs/installation.md

Document https://github.com/scalameta/scalafmt/blob/v2.6.1/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L94-L97.

clarify how `.scalafix.conf` & the CLI binary versions relate 

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

TokenOps: no blank line for scaladoc in expression

---

docs/configuration.md

There was a remaining reference to this being a boolean which might confuse users trying to configure this setting. Also thought it could be clearer when this changed and what it was in previous versions.

Remove reference to binPack.parentConstructors being a boolean

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/VerticalMultilineDefnSite.stat

Rather than combining policy partial functions and unnecessarily extending token ranges for combined policies, keep each policy clause unchanged and introduce policy containers. This will allow removing inner policies when they reach the end of their range, or based on some other criteria (such as type of policy).
Fixes #2044. Helps with #2042.

Policy: preserve original policies and ranges for control

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/test/includeNoParensInSelectChains.stat

Let's extract the select chain matching logic into a method so that it can be reused within another rule.
Need to add a new parameter as classic chain logic, intentionally or not, forgot to check when chains "break out" of parenthesized expressions, so to avoid massive changes put the corrected logic under a parameter.
Helps with #2042.

FormatOps: method to check classic select chain

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/align/BeforeCommentWithinMethodChain.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/test/JavaDoc.stat

Move this code from FormatWriter. Fixes #2042.

Router: indent comment before first select

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicError.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/exceptions/ScalafmtConfigException.scala
scalafmt-tests/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

Intellij invokes the createSession method directly and doesn't expect the null value we return there, so throw ConfigError instead.
Similarly, in the Runner, change the implementation of MyInstanceSession to verify the config first, so that the config parsing exception is not thrown for every file we are trying to format.

ScalafmtDynamic: throw once if can't resolve config

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/test/JavaDoc.stat

This will apply the same clean indentation logic as for `newlines.source != classic`.
Requires adding support for multiple activation tags within a split; one was used to apply indent to the first break only, and the new one will be used to reduce cost of a split down the chain after the first break and remove the newline penalization policy consistent with the previous rule; this filtering capability was introduced in #2060.
Fixes #1334. Supersedes #1557.

Router: merge classic select chain rule with other

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/default/Select.stat

Otherwise, an attempt to activate a tag leads to deactivation of this split.
Fixes #2070.

BestFirstSearch: make the Provided split active

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: don't rewrite (()), aka Lit.Unit

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflectConfig.scala
scalafmt-tests/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

For processing `.sbt` files, we were explicitly using a specific legacy dialect rather than obtaining (via `.forSbt`) a modified configuration suitable for processing these files.
Fixes #2069.

ScalafmtReflectConfig: invoked .forSbt, not legacy dialect

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

#1627 [24]: FormatOps bugfix: ignore NL before infix for fold/unfold

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

The parameters handling implicit parameter list modifier formatting are
not used currently when binpack.unsafeXXX are in force. Show an error.
Relates to #2078.

ScalafmtConfig: implicit with binpack unsupported

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/scala/org/scalafmt/Debug.scala

Currently, policy expiration is applied narrowly (i.e., unlike indents which can expire _before_ or _after_ the expiration token, all policies expire the same way) and incorrectly (they expire not after the specified token, but after the one which follows).
So, add three expiration strategies (before, on, and after) and remove the current after-the-next buggy expiration.
There is **exactly one** diff in `scala-repos` (and it looks *correct*, judging by formatting of similar code before and after the modified block) and one diff in the unit tests (also, looks right), so the change also appears to fix some rare bugs.
From `scala-repos`:
```
private val _right = new function.Function2[Any, Any, Any]
with ((Any, Any) ⇒ Any) { def apply(l: Any, r: Any) = r }
-  private val _both =
-    new …
```

Policy: introduce more specific expire strategies

---

project/Dependencies.scala

Includes bugfixes to 2.13/dotty parsing (try with any expression and negative numeric type literals).
Fixes #2023.

Dependencies: upgrade scalameta to 4.3.19

---

.github/workflows/ci.yml

Tests need all tags to be fetched but latest tag already pushed to master on release. For this reason git fetch fails on workflows started with git push --tags
Other jobs works correct already.

Don't fail test workflow on release

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Current code is a bit ambiguous about newlines.neverBeforeJsNative and
newlines.alwaysBeforeMultilineDef when it comes to formatting methods
with "js.native" as body.

Router: always keep "= js.native" unbroken

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Also, augment the documentation with explanations. Helps with #1627.

#1627 [25]: FormatOps bugfix: afterCurlyLambda=preserve for [un]fold

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat

In BestFirstSearch, let's only start a new generation on a newline split if all its alternatives were also newlines.
Makes formatting of [partial] function parameters more consistent. Helps with #150. Helps with #2099.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/cbfbeb8d7efbfb8bbc8a64fcad600d44b87ff5c1?w=1

State: indicate if all alternatives were newlines

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/ValidationOps.scala

There are multiple places where a configuration instance is created, and some of them are not really appropriate for validation, such as `StyleMap` where custom configuration copies are created based on comments in the code, or to support `binPack.literalArgumentLists`.
Therefore, let's just validate the initial configuration in the decoder and not the custom adjustments.
Fixes #2098.

ScalafmtConfig: validate once in the decoder only

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ReaderUtil.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/SortSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/Case.stat
scalafmt-tests/src/test/resources/default/Idempotency.stat
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/default/Unindent.stat
scalafmt-tests/src/test/resources/newdefault/SearchState.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/unit/Lambda.stat
scalafmt-tests/src/test/resources/unit/TermApply.stat

Support only a single case clause without conditions.
Fixes #150. Fixes #2099.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/baa0d4f436f1bcb7e6b44f834dafb26fcc9b3bb0?w=1

Router: allow space after "{" in partial functions

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

For consistency with the beforeCurlyLambdaParams parameter.

Newlines: rename afterCurlyLambda{,Params}

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

it's a problem when there is no space between the yield and the
parens because it leaves the code in a broken state (won't compile)
Fixes #2117

Fix a problem where parens are removed after a yield

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-case.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Parens/braces serve as delimiters (such as in "if(x"), so when we remove them, we must ensure that tokens before and after continue to be clearly separated. For that, let's just replace these delimiters with spaces, as formatter will remove any redundant space later.
Generalizes #2118.

Rewrite: replace delimiters with space

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala

The policy itself applies the same filter already, so the additional check is unnecessary.
Now that explicit expire token is no longer needed, provide instead an instance of Policy.End.WithPos, and modify Split invocations to be able to expire differently.

PolicyOps: remove redundant SLB policy end filter

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat

By changing the line associated with the newline split after `=>`, we give higher priority to the State ending in this split compared to the State ending in the space split when cost and depth are the same.

Router: prefer case break after `=>` over `if`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala

Replace disallowSingleLineComments and penaliseNewlinesInsideTokens.

PolicyOps: shorten extra flags (noSyntaxNL, okSLC)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat

A split from a later line has higher preference.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/138ce00b316773b54c87f425c40550328a90761a?w=1

Router: prefer not breaking before lambda params

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/For.stat
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat

`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/5bb32713acf7f80b5710a6432a9671a7d1cd8307
(formatting is applied to the original code, not to the previous state of the branch; it doesn't remove newlines but instead fails to add them, as it had before).

Router: delay break if detached comment follows `{`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

For SingleLineBlock, the left token is checked in the provided exclude range sets; in some cases, say when the end token refers to the closing brace, we might want to make sure the closing brace is not followed by a newline. For that, the end token needs to be excluded from the range.

FormatOps: allow excluding end in exclude ranges

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Fixes #2145. Previously, it was not possible to invoke the Scalafmt
command-line tool with a large number of files as arguments because it
would exceed the operating system limit for argument lengths. Now,
clients can pass in arbitrarily long arguments by writing them
first to a file.
```
$ cat /path/to/arguments
/path/to/File.scala
$ scalafmt @/path/to/arguments
```
The command above is equivalent to running "scalafmt /path/to/file.scala".

Add support to expand command-line arguments with @ symbol

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces2.stat

We failed to take into account the maxLines parameter when determining if the method block as apply arg would be rewritten.
Fixes #2138.

RedundantBraces: fix method block as apply arg

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Previously, we were only looking for a break before an infix op once but we should also recurse into left and right sides.
Fixes #2163.

RedundantParens: look for NL before nested infix ops

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Config.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/default/Advanced.stat
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.stat
scalafmt-tests/src/test/resources/newlines/source.source
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/src/test/resources/spaces/InParentheses.stat
scalafmt-tests/src/test/resources/test/i1527.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultiple.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultipleDanglingParens.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNever.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

Let's try to standardize formatting of the code which follows a def/val/case/if etc using an extended version of `newlines.alwaysBeforeMultilineDef`.
`scala-repos` diffs (for classic case, in which only handling of comments is different):
* Newlines: default alwaysBeforeMultilineDef = false: https://github.com/kitbellew/scala-repos/commit/c06b63b40029b6f4cea2df6fe19af91554f10d23?w=1
* Router: standard rule for body of def/if-else/case: https://github.com/kitbellew/scala-repos/commit/05b9b3e05d939643e937c7b71c930379f04c80df
For the other cases (fold, unfold, keep), unit tests describe the new functionality.
Fixes #2113.

Router: standard rule for body of def/if-else/case

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

That includes keeping the opening paren on the first line and avoiding extra indentation. Fixes #2137.

Router: format ()-enclosed case clause as a block

---

scalafmt-tests/src/test/resources/test/Dialect.source

Actually, the dependency has already been updated by `scala-steward`. Add the test which failed previously.
Improves dotty support in the `scalameta` parser but `scalafmt` formatter doesn't support any new syntax.
Fixes #2104.

Dependencies: upgrade scalameta to 4.3.21

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Follow-on to #2165, fixing a couple of bugs: avoid empty parens, "->" tuple and properly match parens.

FormatOps: improve isCaseBodyEnclosedAsBlock

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/align/ArrowEnumeratorGenerator.stat
scalafmt-tests/src/test/resources/default/For.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/unit/For.stat

Follow-on to #2158. Also partial undo of #1795, since the same functionality is now available by setting `newlines.beforeMultiline = keep`.

FormatOps: use common rules for a generator body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Lambda.stat

This option allows forgoing the break for oneline formatting, which the `always` option doesn't provide.
Fixes #2187.

Newlines: break before params of multiline lambda

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ModExt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Supersedes the special-case handling for aligned indent after the left arrow in generator expressions.

ModExt: use split width with StateColumn indents

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: check if postfix only is allowed

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Lambda.stat

Router: beforeCurlyLambdaParams for paren lambdas

---

docs/installation.md

I found a couple of grammar errors in documentation, so decided to fix them.
Please let me know if I missed anything with regards to contributing guidelines.

Documentation: fix minor grammar error

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Pattern.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: use AvoidInfix matcher correctly

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/newlines/source.source
scalafmt-tests/src/test/resources/test/JavaDoc.stat
scalafmt-tests/src/test/resources/unit/Basic.source
scalafmt-tests/src/test/resources/unit/Import.source
scalafmt-tests/src/test/resources/unit/Package.source

FormatWriter: correct first line of docstrings for `wrap=no`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix3.stat

Router: truncate indent for enclosed select chains

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat

Also, fix closing paren when `spaces.inParentheses` is set. Currently, one case is excluded for the opening paren (`if`/`while`/etc.), but a completely different one (`isDefnOrCallSite`) applies to the closing paren. Let's fix that.
Fixes #2219.

Router: preserve breaks for source.keep in `case`

---

.gitignore
project/Dependencies.scala
project/build.properties
project/plugins.sbt
project/project/plugins.sbt

Current coursier version fails to parse non SemVer version deps.
You cannot build e.g. scalameta SNAPSHOT and test it with scalafmt.
It is fixed in latest coursier.
But latest coursier conflicts with sbt 1.3.x
And latest sbt already contains sbt-coursier.
Fun stuff :)
Previously:
`Ignoring unparsed versions: Vector(4.3.24+30-63c1bd76-SNAPSHOT)`
Now works fine:
`val scalametaV  = "4.3.24+30-63c1bd76-SNAPSHOT"`

Bump deps coursier,sbt

---

.gitignore
project/Dependencies.scala
project/build.properties
project/plugins.sbt
project/project/plugins.sbt

Reverts scalameta/scalafmt#2225
I need to revert it because snapshot release [fails](https://github.com/scalameta/scalafmt/runs/1308100322?check_suite_focus=true) on command `sbt ci-release docs/docusaurusPublishGhpages` 
cc @kpbochenek

Revert "Bump deps coursier,sbt"

---

project/Dependencies.scala

context: I'm trying to get the Scala community build onto a newer version of Scalameta over at https://github.com/scala/community-build/pull/1278
not sure yet if this upgrade would help me, but it's one of the paths I'm exploring, so let's see what CI has to say

upgrade to Scalameta 4.3.24

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

Look at the format token index instead. Covers cases when docstring is the first non-BOF token but is preceded by leading whitespace.

Docstrings fix: first token may not start at 0

---

.github/workflows/release.yml

Something broken after sbt update to 1.4.x https://github.com/scalameta/scalafmt/pull/2272
Looks like it passes invalid scala version to docs generation stage

Dedicated sbt sessions for release and docs publishing

---

.jvmopts
build.sbt
project/Dependencies.scala
project/build.properties
project/plugins.sbt
project/project/plugins.sbt
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Patch.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/Tabulator.scala

* Latest Scala.
* Latest sbt, disable BSP server because it doesn't work well with Metals.
* Latest Scalameta.
* Use only ScalaTest FunSuite because matchers introduce compile errors
in 2.13.3 due to "multiple infix" deprecation warnings.
* Remove unnecessary sbt-coursier dependency because it's included with sbt.

Upgrade dependencies

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/dotty/Enum.stat

#2262 follow-up. In the following PR, I provided implementation and test cases with `EnumCase` constructors missing in the previous one.

Support case with class constructor

---

build.sbt
docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/SortSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala
scalafmt-tests/src/test/resources/dotty/Dialect.stat
scalafmt-tests/src/test/resources/dotty/Enum.stat
scalafmt-tests/src/test/resources/dotty/Macro.stat
scalafmt-tests/src/test/resources/dotty/Open.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiersOpen.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiersOpenMissing.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiers_Default.source
scalafmt-tests/src/test/resources/unit/Dialect.stat
yarn.lock

Builds on top of #2285. See commit history for details.
Scala 3 macros use a new syntax called "quote" `'expr` and "splice" `$expr`.
This PR implements support to format quotes and splices.
This PR includes a commit that requires users to specify `runner.dialect = Scala3` in order to format Scala 3 syntax. This change is related to quote and splice because enabling quote/splice parsing support introduces a regression for Scala 2 users https://github.com/scalameta/scalameta/issues/2191.
Towards #2216.

Scala 3: Implement support for quote and splice

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/dotty/Macro.stat

We recently merged the support for Macros together with an update to scalameta, which caused the master to stop compiling due to removal of two token types in scalameta. This should fix the issue. 
I also needed to fix some tests, since `'identifier` is only allowed within splices or quotes.

Fix Macros after fixes in scalameta

---

.gitattributes
.github/workflows/ci.yml
build.sbt
scalafmt-tests/src/test/scala/org/scalafmt/EmptyFileTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala

Fixes https://github.com/scalameta/scalafmt/issues/2288
Additionally, to help with some [cryptic errors](https://github.com/scalatest/scalatest/issues/556) I got back to munit (reverted https://github.com/scalameta/scalafmt/pull/1697). The support in Intellij is much better now, so I think it's worth keeeping. There was a recent release with some nice changes in Intellij - https://blog.jetbrains.com/scala/2020/12/01/intellij-scala-plugin-2020-3/#munit-support
What do you think?
I commented on parts that are related to windows failures.

Add tests for windows

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/dotty/Using.stat

The next one based on #2216.
The `using` soft keyword in parameter lists seems to be one-to-one with the `implicit`. However, `using` can also be used within argument lists. 
We've discussed with @tgodzik that we can add aliases to `newlines.implicitParamListModifierPrefer` and `newlines.implicitParamListModifierForce`, namely `newlines.usingParamListModifierPrefer` and `newlines.usingParamListModifierForce` (and apply this existing setting to the using argument lists).
Please take a look at the changes in the docs, I put the information about the whole `implicit vs using` matter in one place. In addition, we can update every occurrence of `implicit` that applies to the `using` at the same time and replace it with `implicit or using` for the case of specificity and maybe add some …

Support using soft keyword in parameter and argument lists

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/TreeSyntacticGroup.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/MatchType.stat

Scala 3 allows to specify types using the match clause such as:
```scala
type T = R match{
case Char => String
case Array[t] => t
}
```
Implementing this required mostly copying whatever was done for normal matches.

[Scala 3] Add support for match types

---

scalafmt-tests/src/test/resources/scala3/Macro.stat

It seems that macro patterns work without any changes, so I just added a few tests and also uncommented a fixed issue from scalameta.

Add tests for macro pattern

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Advanced.stat
scalafmt-tests/src/test/resources/unit/Comment.stat

Router: keep a blank between comma and comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/SortSettings.scala
scalafmt-tests/src/test/resources/rewrite/SortModifiersInlineTransparent.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiers_Default.source
scalafmt-tests/src/test/resources/scala3/InlineTransparent.stat

Scala 3 introduced inline and transparent modifiers that can be add to variables or definitions. More info at https://dotty.epfl.ch/docs/reference/metaprogramming/inline.html

[Scala3] Add inline and transparent modifiers

---

docs/configuration.md
project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ContinuationIndent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/ExtendsComma.stat
scalafmt-tests/src/test/resources/test/ContinuationIndent.stat

Scala 3 allows for using `,` instead of `with` when declaring multiple parents.

[Scala 3] Allow to use commas instead of with for multiple parents

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ExpandImportSelectors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortImports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-tests/src/test/resources/scala3/Export.stat

Scala 3 has a complimentary structure to imports, which is the export cluase: https://dotty.epfl.ch/docs/reference/other-new-features/export.html
All of the existing options for import make sense in case of export.
Not sure if it makes sense to add aliases to all of the import options or whether to separate them. I left it as is for now.

[Scala 3] Format export clauses

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/SortSettings.scala
scalafmt-tests/src/test/resources/scala3/OpaqueType.stat

More information about opaque types here: http://dotty.epfl.ch/docs/reference/other-new-features/opaques.html

[Scala 3] Add formatting for opaque types

---

project/Dependencies.scala
scalafmt-tests/src/test/resources/scala3/ExportGivens.stat

It seems that after recent changes in Scala 3, given exports are easily handled by the same logic that does imports.

[Scala 3] Add tests for given exports

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/TreeSyntacticGroup.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/DependentFunction.stat

Dependent functions allow us to use named parameters in function types and base their return types on the type of that parameter.
They are defined here: http://dotty.epfl.ch/docs/reference/new-types/dependent-function-types.html

[Scala 3] Add formatting for dependent function types

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/TreeSyntacticGroup.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/PolyFunction.stat

Polymorphic types are a way to define a function parametrized by a type, complementary to `def method[T]`
More information here: http://dotty.epfl.ch/docs/reference/new-types/polymorphic-function-types.html
I was also looking at fold/unfold, but polymorphic function types cannot have curly braces around their body, so this will not make much sense.

[Scala 3] Add formatting for polymorphic functions

---

scalafmt-tests/src/test/resources/scala3/TypeLambda.stat

More about type lambdas can be found here: http://dotty.epfl.ch/docs/reference/new-types/type-lambdas.html
It seems that it works rather sensibly so I just added some tests.

[Scala 3] Add formatting for type lambdas

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/UnionIntersectionType.stat

Intersection and union types are defined respectively by `&` and `|`, you might read more about it here http://dotty.epfl.ch/docs/reference/new-types/union-types.html and http://dotty.epfl.ch/docs/reference/new-types/intersection-types.html
Since, they both look pretty similar to alternatives, that's what I based my implementation on.

[Scala 3] Add support for union and intersection types

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala

Fixes #2342
Example:
```scala
@ val arg = "@-"
arg: String = "@-"
@ val atFile = arg.stripPrefix("@")
atFile: String = "-"
@ atFile eq "-"    // <---- BUG!
res2: Boolean = false
@ atFile == "-"
res3: Boolean = true
```

Fixed always false conditions

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/MatchType.stat
scalafmt-tests/src/test/resources/scala3/OpaqueType.stat
scalafmt-tests/src/test/resources/scala3/UnionIntersectionType.stat

Previously, we would not split on type bounds which might sometimes be useful especially with the new Scala 3 types. Now, I added a separate case of type bounds in type declarations and definitions.
This also popped up due to the fixes done recently in scalameta. Not super sure about the changes, it is in a way similar to extends now, but none of it looks perfect.
We could remove the case and go back to having type bounds only ever split by space.

Update Scalameta to 4.4.8 and add formatting for type bounds

---

scalafmt-tests/src/test/resources/scala3/InlineTransparent.stat

Inline if and match seem to work out of the box with scalafmt. More info about them here: https://dotty.epfl.ch/docs/reference/metaprogramming/inline.html#inline-conditionals

[Scala 3] Add tests for inline if and match support

---

scalafmt-tests/src/test/resources/scala3/StarImport.stat

It's now possible to use `*` instead of `_` for wildcard imports. More info [here](https://dotty.epfl.ch/docs/reference/changed-features/imports.html)

[Scala 3] Add tests for new wildcard imports

---

scalafmt-tests/src/test/resources/scala3/Extension.stat

Previously, extension methods could not have `using` clauses before the main parameter or type params in definitions, which is now possible.

[Scala 3] Add tests for modified extension methods

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/Vararg.stat

It's now possible specify arguments for vararg parameters by adding `*`:
```scala
def method(a: String, b: String*)
method(arg1, args*)
```
this also works for pattern matches.
More info about the new syntax is available [here](https://dotty.epfl.ch/docs/reference/changed-features/vararg-splices.html)

[Scala 3] Fix formatting for the new vararg splices

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/scala3/RenameImportExport.stat

Previously, renames could only be done using `=>`, now it's also possible to use `as`. This also makes it possible to not use braces when doing a single rename/unimport.
More information can be found [here](https://dotty.epfl.ch/docs/reference/changed-features/imports.html)

[Scala 3] Format import/export when using `as` soft keyword

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/Match.stat

Based on #2376 from @tgodzik:
*In Scala 3 match can be used as any other operator, which means it can chained and can be invoked with an additional `"."`*
*More details here: https://dotty.epfl.ch/docs/reference/changed-features/match-syntax.html*
*I tried to keep most of the changes behind the dialect, so this will only be noticed by Scala 3 dialect users*
This approach applies the formatting rules used for `Term.Select` to appropriate `Term.Match` expressions.

[Scala 3] Add formatting for match used as an operator

---

build.sbt

Scaltags are now published again for 2.11 :tada:

Update scalatags to 0.9.4

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/TypeArguments.stat
scalafmt-tests/src/test/resources/scala3/MatchType.stat
scalafmt-tests/src/test/resources/scala3/OpaqueType.stat
scalafmt-tests/src/test/resources/scala3/UnionIntersectionType.stat

Fixes #1249. Follow-on to #2351.

Newlines: explicit setting for beforeTypeBounds (`:`, `<:`, `>:`, `<%`)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/src/test/resources/rewrite/ExpandImportSelectors.stat
scalafmt-tests/src/test/resources/rewrite/SortImports.stat
scalafmt-tests/src/test/resources/unit/Import.source

Otherwise, we were using an incorrect split which doesn't work outside of the `format:off` area, by losing any policies and indents the original split had.
We now also no longer need the special handling of `{...}`.
In `scala-repos`, only one file is modified, one that `scalafmt` couldn't format before.

BFS: keep policies and indents for provided splits

---

build.sbt

Not sure why it was needed, but it might help us to get scalafmt on native if we remove it.

Remove paiges, which doesn't seem to be used anymore

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Some experimental and slightly convoluted logic remained which lead to an unnecessary indent in rare cases of def/val/case bodies.
P.S. `scala-repos` changes are exactly three expressions, all correctly reducing the unnecessary indent.
```
diff --git a/repos/intellij-scala/src/org/jetbrains/plugins/scala/annotator/importsTracker/ScalaRefC
ountHolder.scala b/repos/intellij-scala/src/org/jetbrains/plugins/scala/annotator/importsTracker/Sca
laRefCountHolder.scala
index cd29801c6f..cf4c05bb40 100644
--- a/repos/intellij-scala/src/org/jetbrains/plugins/scala/annotator/importsTracker/ScalaRefCountHol
der.scala
+++ b/repos/intellij-scala/src/org/jetbrains/plugins/scala/annotator/importsTracker/ScalaRefCountHol
der.scala
@@ -135,7 +135,7 @@ object ScalaRefCountHolder {
def getInstance(file: …
```

FormatOps: fix bug with space indent in ctrl body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/test/Unicode.stat

This logic does not depend on the splits (hence, no state dependency) and requires only access to the tokens.
Also, make sure that `format:off` applies to the split just before it while `format:on` only applies to the split just after it.

State: move format:off detection to FormatToken

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Expand the deprecated `alwaysBeforeMultilineDef` to have more granular control. Also, if the deprecated `beforeMultilineDef` is not explicitly specified, apply the behaviour of `beforeMultiline` parameter instead.
As discussed in #2400, the option to have consistent formatting is desirable. Fixes #2400.

Router: force break before multiline assignments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Using extractors on the entire format token, especially when it includes a match on either left or right token, is inefficient. However, in most cases an extractor match on the meta field is equivalent and allows us to extract the value once instead of twice (once in match and a second time in the case body).

Router: use extractors on meta to get extra values

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Indents.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat

Optional braces are discussed in depth in
https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html
There 4 different ways indentation can start:
- after a keyword token such as:
```
=  =>  ?=>  <-  catch  do  else  finally  for
if  match  return  then  throw  try  while  yield
```
- after `:` at end of line in templates
- after `)` in if or an extension group
- after `with` for given definitions

[Scala 3] Add support for optional braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

These two keywords are not followed by a block, hence the existing logic doesn't work for them.

Router: handle optional braces in this/catch/match/for-do/for-yield

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Indent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/CanRunTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatException.scala

- Indent: slightly modify how expiration is detected
- CanRunTests: print the code which failed parsing
- FormatOps: move traversal methods to FormatTokens
- BestFirstSearch: use stop token position only

Various changes to prepare to rewrite optional braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

The patch being undone is causing changes in `scala-repos`, will be investigated separately.

BestFirstSearch: partially undo the last commit

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

Check the arguments of a Term.Apply (just like Term.ApplyInfix above) looking for a placeholder. Fixes #2426.

Rewrite: fix the placeholder check

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Decodable.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ImportSelectors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/SpaceBeforeContextBound.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-tests/src/test/resources/spaces/BeforeContextBoundColonTrue.stat

It's been a while since we deprecated `binPack = true` in favor of `binPack.preset = true`, since the former always causes confusion if `binPack.parentConstructors` setting is also added. Let's now completely disable this usage.

Decodable: disable top-level presets, error out

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

With optional braces, the body of `if` can be a block but not include a left brace. Let's expire on `{` if it's there, otherwise on the token just before `thenp` part.

FormatOps: fix bug with `{` or `then` in `if`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Actually, they are always optional, so we should fall back to existing rules to handle that.

FormatOps: optional braces in a single-stat block

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

- FormatTokens: allow to look up an ealier token
- FormatOps: get stmt differently in rewritten block
- FormatTokens: move matchingParens from FormatOps
- FormatOps: use tokens from FormatTokens, not tree
- FormatWriter: recognize blk rewrites in `a{} -> a()`

Prepare for scala3 rewrites (new syntax, optional braces)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

The style for an intermediate token between two parentheses would have the same value for `binPack.unsafeCallSite`, so there's no need for a complex logic.

Router: use available style to check binpack

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

The purpose of this change is twofold:
- when tokens are rewritten, the original logic of looking up by a token would stop working, as new tokens wouldn't be registered in the `StyleMap`; instead, we need to use the token position rather than the actual token
- since format overrides are fairly rare, using binary search on a handful of change positions is cheaper than using a hashmap containing hundreds or even thousands of tokens following the first override

StyleMap: use binary search on change positions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-tests/src/test/resources/scala3/TypeLambda.stat

Related to https://github.com/scalameta/scalafmt/issues/2216#issuecomment-823910262
Previously, we would catch the case with Delim being second for `(`.

Fix formatting when Ident is after TypeLambdaArrow

---

.jvmopts
.sbtopts

This has apparently been the default since 2013
(https://bugs.openjdk.java.net/browse/JDK-8000325)
and is no longer available on jdk15

Don't pass CMSClassUnloading to sbt

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scalajs/Apply.stat

Instead of indenting for each level of "()" nesting, add a flag to allow indenting only once. Fixes #2079.

BinPack: support indenting call sites only once

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

With optional braces, we are missing the physical indication that the formatter has come to expect with some of its optimizations.
The BestFirstSearch algorithm has an optimization which recurses into a block and doesn't backtrack. Some split policies skip matching pairs of braces when applying a single-line constraint.
In the absence of any other indicators (like Indent/Outdent tokens), we need to identify cases where braces are optional.
Fixes #2448.

FormatOps: mimic `{}` pairs with optional braces

---

docs/configuration.md
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

Also, deprecate old regex-only patterns as the new option allows both. Fixes #1648.

ProjectFiles: add `PathMatcher` patterns

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: optional braces in `= partial function`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala

Also, since the new implementation uses StyleMap, remove the check in StyleMap prohibiting overrides of this setting. Fixes #1861.

FormatTokensRewrite: migrate RewriteTrailingCommas

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Config.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala

This is to avoid duplicating information -- and to avoid deleting a setting accidentally since it's "not used" anywhere. See https://github.com/scalameta/scalafmt/issues/1644#issuecomment-578411802.

CliOptions: use config defaults from source class (and other refactors)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/scala3/RenameImportExport.stat

These two rules depend on each other and hence go hand in hand.

FormatTokensRewrite: migrate RedundantParen/Braces

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Also, add an explicit check to CliArgParser, to disallow having both `--config` and `--config-str` specified, since only one of them is actually processed.

CliOptions: parse config into a Conf object

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Unfortuntely, `include` is a hocon reserved keyword, used to include another application config. Let's rename.

ProjectFiles: rename include to includePaths

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Multiple methods use `tree` as a parameter name, and this leads to bugs when the parameter is renamed by usage is preserved. Let's rename the class field to something quite unambiguous.

FormatOps: rename `tree` field to `topSourceTree`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/binPack/ParentConstructors.stat
scalafmt-tests/src/test/resources/default/String.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/scala3/Enum.stat
scalafmt-tests/src/test/resources/scala3/Given.stat

Refactor `splitWithChain` into `binPackParentConstructorSplits`, automatically determine the intermediate or final expiration for `inits` or `derives` in a template.
That allows modifying a single rule to preserve existing breaks (in `newlines.source=keep`).
Fixes #2226.

FormatOps: use `keep` in binPackParentCtorSplits

---

build.sbt

Since 1.5.0 the syntax is being reported as deprecated, so it's better to just replace it.
I run the scalafix rule from [eed3si9n](https://eed3si9n.com/syntactic-scalafix-rule-for-unified-slash-syntax) with some modifications.

Fix deprecated sbt syntax

---

docs/configuration.md

Also, add a dedicated section for `indent.withSiteRelativeToExtends`, just like we have with `indent.commaSiteRelativeToExtends`.

Documentation: describe `indent.significant`

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/AbsoluteFile.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/FileTestOps.scala

Possibly handled differently by graalvm, the native compiler. Fixes #2493.

CliOptions: do not compute `cwd` at compile time

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/Issues.stat

Previously, it was not possible to have a single val in a block and not have braces, which is why it didn't work for Scala 3.
Now, we make sure that indentation is added always if we have a single statement, which is a Defn.

Fix indentation when using braceless block with single Defn

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala

Since Scala 2.13.6 and 2.12.14 it is possible to use `-Xsource:3`, which adds support for some of the new scala 3 syntax. ~~None of those changes should influence Scalafmt, so I think it would be good to set it as the default.~~

Add dialect to allow formatting with -Xsource:3 option

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/Debug.scala

It's much easier to find where the Split was created now. It's also possible to navigate there (at least from VSCode, do we want to modify it to work for Intellij?)
```
Debug:63 Split(line=1703 count=1=
NoSplit:[Router.scala:1703](cost=0, indents=[], PNL:[Router:1703]<28d+1)
Split(line=2249 count=1=
Newline:[Router.scala:2249](cost=1, indents=[2>x:37], NoPolicy)
Split(line=2245 count=1=
Space:[Router.scala:2245](cost=0, indents=[], NoPolicy, opt=x:37)
Debug:71 Visited x∙[37:38]: 2
Debug:71 Visited ∙val[0:3]: 1
Debug:71 Visited val∙f[3:5]: 1
Debug:90  3: val             Space:[Router.scala:2076](cost=0, indents=[], NoPolicy) 0 3 [0]
Debug:90  5: f               NoSplit:[Router.scala:1062](cost=0, indents=[], PNL:1058<17d+20) 0 5 [0]
Debug:90  6: : …
```

Display filename alongside line information when debugging

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Apparently, the `colonEol` indentation marker is slated to be supported in a variety of additional situations, not just with templates. For now, add package support. Other cases are not yet recognized by the `scalameta` parser.
https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#variant-indentation-marker-

FormatOps: add optional braces after `package a:`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/scala3/Macro.stat

Fixes #2554. Minor refactor from #2555.

RedundantBraces: keep in macro quotes/splices

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

Earlier, we would store a potential location and then later check if it should be supplied with an extra blank. Instead, do that at once.
Towards #2511.

FormatWriter: fully determine blank line indices

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Penalize instead. Some arguments cannot be formatted on a single line, such as when `unfold` is used.
Fixes #2561.

Router: don't force single-line for single-arg

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala

Metaconfig effectively renders this parameter unusable as it redirects to another one. See scalameta/metaconfig#135.

Newlines: fix copy-pasted value in DeprecateName

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Previously, we inadvertently cover cases when one Apply is a parameter to another, rather than representing the next parameter group. Fixes #2561.

TreeOps: fix bug in `getLastCall`
