build.sbt
scalafmt/src/main/scala/org/scalafmt/FormatToken.scala
scalafmt/src/main/scala/org/scalafmt/ScalaFmt.scala
scalafmt/src/main/scala/org/scalafmt/ScalaFmtLogger.scala
scalafmt/src/main/scala/org/scalafmt/Split.scala
scalafmt/src/main/scala/org/scalafmt/SplitToken.scala
scalafmt/src/main/scala/org/scalafmt/State.scala
scalafmt/src/test/scala/org/scalafmt/FormatTest.scala

Also moved classes into separate files.

Add FormatToken, fixes #9.

---

src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/ScalaFmtLogger.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/package.scala
src/test/resources/Indent.test
src/test/resources/basic.test
src/test/scala/org/scalafmt/FormatTest.scala

Most of the diff comes from improving debugging.

Use policy to unindent when leaving block, fixes #19.

---

src/main/resources/logback.xml
src/main/scala/org/scalafmt/Debug.scala
src/main/scala/org/scalafmt/FormatToken.scala
src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/ScalaFmtLogger.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/Advanced.test
src/test/resources/Test.manual
src/test/resources/TypeArgument.test
src/test/scala/org/scalafmt/FormatTest.scala
src/test/scala/org/scalafmt/ManualTests.scala

* Treat Defn/Case statements as blocks, memoize by (indentation, tree).
* Prune branches that are clearly worse than a visited alternative.

Shrink search space.

---

build.sbt
src/main/scala/org/scalafmt/Debug.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/TypeArgument.test
src/test/scala/org/scalafmt/FilesUtil.scala
src/test/scala/org/scalafmt/FormatTest.scala
src/test/scala/org/scalafmt/Report.scala

Report is written to `target/index.html`. Example output

Add heatmap over state visits.

---

src/main/scala/org/scalafmt/FormatToken.scala
src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala
src/main/scala/org/scalafmt/package.scala
src/test/resources/Advanced.test
src/test/resources/Basic.test
src/test/resources/Case.test
src/test/resources/ColumnWidth.test
src/test/resources/Import.test
src/test/resources/Package.test
src/test/scala/org/scalafmt/DiffUtil.scala
src/test/scala/org/scalafmt/FormatTest.scala
src/test/scala/org/scalafmt/UnitTests.scala

After package, imports and before objects/defs/classes it's common to use 2 newlines.

Format with 2x newlines.

---

.travis.yml

Broken build https://travis-ci.org/olafurpg/scalafmt/builds/105446529

Update Travis jdk to 8.

---

.travis.yml
build.sbt
readme.md
src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/unit/application.conf
src/test/scala/org/scalafmt/FormatTest.scala
src/test/scala/org/scalafmt/Speed.scala
src/test/scala/org/scalafmt/stats/GitInfo.scala

Removed Typesafe config + Ficus. Fixes #42

Simplify data submission.

---

src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/unit/UnaryApply.stat

Before:
format("-a") => "- a"
After:
format("-a") => "-a"

No space on ApplyUnary.

---

src/main/scala/org/scalafmt/Debug.scala
src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/unit/Comment.stat
src/test/resources/unit/Error.stat
src/test/scala/org/scalafmt/FormatTest.scala

Some dead code, some untested cases.

Bump test coverage.

---

src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/standard/Apply.stat
src/test/resources/standard/Case.case
src/test/resources/unit/TermApply.stat
src/test/scala/org/scalafmt/FormatTest.scala
src/test/scala/org/scalafmt/ManualTests.scala
src/test/scala/org/scalafmt/Report.scala

* Add tests
* fix report.
* withPolicy everywhere.
* Special case if args.length == 1
* Flush comments to right.

Add optimalAt optimization.

---

src/main/resources/logback.xml
src/main/scala/org/scalafmt/Cli.scala
src/main/scala/org/scalafmt/FormatToken.scala
src/main/scala/org/scalafmt/Modification.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala

The indentation is wrong in a few cases, but it's a nice first approximation.

Add --range flag to cli.

---

readme.md
src/main/scala/org/scalafmt/Formatter.scala
src/main/scala/org/scalafmt/ScalaFmt.scala
src/main/scala/org/scalafmt/ScalaFmtLogger.scala
src/main/scala/org/scalafmt/Split.scala
src/main/scala/org/scalafmt/State.scala
src/test/resources/readme.md
src/test/resources/standard/Advanced.stat
src/test/resources/standard/Case.case
src/test/resources/unit/Advanced.source
src/test/resources/unit/Argument.source
src/test/resources/unit/Case.case
src/test/resources/unit/Case.stat
src/test/resources/unit/Comment.stat
src/test/resources/unit/DefDef.stat
src/test/resources/unit/For.stat
src/test/resources/unit/If.stat
src/test/resources/unit/Import.source
src/test/resources/unit/Lambda.stat
src/test/resources/unit/Mod.stat
src/test/resources/unit/Template.source
src/test/resources/unit/TermApply.stat
src/test/resources/unit/TypeArgument.source
src/test/resources/unit/UnaryApply.stat
src/test/scala/org/scalafmt/DiffUtil.scala

* comments
* package
* more robust defn modifiers
* if else
* extends indentation
* def inline body
* class/object/trait indenation

Fix warts in output.

---

core/src/main/scala/org/scalafmt/Error.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/PolicySummary.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/Test.manual
core/src/test/resources/standard/Advanced.stat
core/src/test/resources/unit/If.stat
core/src/test/resources/unit/Template.source
core/src/test/scala/org/scalafmt/FidelityTest.scala

* There are only timeout exceptions now.
* make easier to debug optimizations
* Add support for try/catch
* no dequeueAll when inside single line block
* fix off by one error in policy summary
* Handle newlines in case body.
* Fix cast exception on templates.
JMH
===
[info] Benchmark                    Mode  Cnt     Score    Error  Units
[info] BaseLinker.scalafmt          avgt   10   134.951 ± 65.239  ms/op
[info] BaseLinker.scalariform       avgt   10    26.815 ±  6.342  ms/op
[info] Division.scalafmt            avgt   10   169.684 ± 15.607  ms/op
[info] Division.scalariform         avgt   10    35.659 ±  6.397  ms/op
[info] OptimizerCore.scalafmt       avgt   10  1389.404 ± 88.609  ms/op
[info] OptimizerCore.scalariform    avgt   10   256.030 ± 33.611  ms/op
[info] …

Fix all remaining output bugs.

---

benchmarks/src/main/scala/org/scalafmt/benchmarks/FormatBenchmark.scala
benchmarks/src/resources/scala-js/Primality.scala
benchmarks/src/resources/scala-js/ScalaJSClassEmitter.scala
benchmarks/src/test/scala/org/scalafmt/BenchmarkOK.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/main/scala/org/scalafmt/internal/Debug.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/internal/Split.scala
core/src/main/scala/org/scalafmt/internal/State.scala
core/src/test/resources/Test.manual
core/src/test/resources/standard/Advanced.stat
core/src/test/resources/standard/Apply.stat
core/src/test/resources/standard/Case.stat
core/src/test/resources/standard/Val.stat
core/src/test/resources/unit/Advanced.source
core/src/test/resources/unit/Argument.source
core/src/test/resources/unit/Comment.stat
core/src/test/resources/unit/DefDef.stat
core/src/test/resources/unit/TermApply.stat
core/src/test/resources/unit/TypeArgument.source
core/src/test/scala/org/scalafmt/FormatTests.scala
core/src/test/scala/org/scalafmt/UnitTests.scala
core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala
core/src/test/scala/org/scalafmt/util/Speed.scala
readme.md
run-benchmarks.sh

* Ignore singleline if obviously won't work.
* Refactor optimizations, enable by flag.
* Recurse on blocks inside no-opt zones, blocks are memoized.
* Temporary fix for comments exceeding column limit.
* Add a bunch of tests in Advanced.stat.
* Early eliminate competing solutions if there is a 0 cost solution.
```
[info] Benchmark                        Mode  Cnt     Score    Error  Units
[info] GenJsCode.scalafmt               avgt   10  1283.002 ± 77.631  ms/op
[info] GenJsCode.scalariform            avgt   10   228.591 ± 10.815  ms/op
[info] OptimizerCore.scalafmt           avgt   10  1242.236 ± 46.238  ms/op
[info] OptimizerCore.scalariform        avgt   10   230.396 ±  8.253  ms/op
[info] ScalaJSClassEmitter.scalafmt     avgt   10   308.831 ± 15.678  ms/op
[info] …
```

Various optimizations, 4 files to go Scala.js.

---

.github/ISSUE_TEMPLATE.md
build.sbt
core/src/main/scala/org/scalafmt/ScalaFmt.scala
core/src/main/scala/org/scalafmt/cli/Cli.scala
core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
core/src/test/resources/Test.manual
core/src/test/resources/default/DefDef.stat
core/src/test/scala/org/scalafmt/FormatExperiment.scala
core/src/test/scala/org/scalafmt/util/ScalaProjectsExperiment.scala
project/plugins.sbt
readme.md

* Remove maxDuration parameter to ScalaFmt.format.
* Update readme.

Publish to Maven Central.

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala

Expose --alignByArrowEnumeratorGenerator in CLI

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/spaces/Spaces.stat
core/src/test/scala/org/scalafmt/util/HasTests.scala

Little thingy that always bothers me with Scalatest matchers :)
What do you think?

Space after triple equals

---

cli/src/main/scala/org/scalafmt/cli/Cli.scala
cli/src/test/scala/org/scalafmt/cli/CliTest.scala
core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/trailing-commas/TrailingComma.stat
core/src/test/scala/org/scalafmt/util/HasTests.scala

Context:
- https://github.com/scala/scala.github.com/pull/533
- https://twitter.com/dwijnand/status/768284455136063488

Add hidden poorMansTrailingCommasInConfigStyle flag for fun

---

core/src/main/scala/org/scalafmt/ScalafmtStyle.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/newlineBeforeLambdaParams/LambdaNewline.stat
core/src/test/scala/org/scalafmt/util/HasTests.scala

Option to put a newline to be put before the parameters of a lambda

---

core/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
core/src/test/resources/rewrite/RedundantBraces.stat
core/src/test/resources/rewrite/RedundantBraces2.stat

Remove redundant braces and no other tokens!

---

cli/src/main/scala/org/scalafmt/cli/Scalafmt210.scala
cli/src/main/scala/org/scalafmt/cli/StyleCache.scala
core/src/main/scala/org/scalafmt/Error.scala

- Done at LambdaWorld hackathon with andrasp3a

Fix for https://github.com/olafurpg/scalafmt/issues/478

---

intellij/src/org/scalafmt/intellij/ScalafmtAction.scala

We print message of the exception with error on configuration error

Display error message on configuration error in IntelliJ plugin

---

core/src/main/scala/org/scalafmt/config/Align.scala
core/src/main/scala/org/scalafmt/config/Settings.scala
core/src/test/resources/dynamic/DynamicStyle.stat

In case you use defaultWithAlign but want to add one more token to
vertically align. Before you would need to define all tokens in
defaultWithAlign + your custom token.

Add syntax align.tokens.add = [foobar]

---

build.sbt
intellij/intellij.iml
intellij/resources/META-INF/plugin.xml
intellij/src/org/scalafmt/intellij/FileDocument.scala
intellij/src/org/scalafmt/intellij/OnFileSaveComponent.scala
intellij/src/org/scalafmt/intellij/Settings.scala
intellij/src/org/scalafmt/intellij/SettingsGui.scala
intellij/src/org/scalafmt/intellij/Utils.scala

I just moved the app setting at project level.
So if you want to set it globally you can set it for all your current projects in `Preferences...` and for all future projects in `File` > `Other settings` > `Default Settings...`

Move Settings at project level

---

.scalafmt.conf
metaconfig/src/main/scala/metaconfig/ConfigReader.scala
metaconfig/src/main/scala/metaconfig/Metaconfig.scala
metaconfig/src/test/scala/metaconfig/ConfigReaderTest.scala

Will help #567 stay backwards compatible.

More configurable metaconfig

---

core/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
core/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
core/src/test/resources/rewrite/RedundantParens.stat
readme/Configuration.scalatex
readme/Readme.scala

Implements rewrite requested in #533

Remove redundant braces in enumerator guard conditions

---

scalafmtSbt/src/main/scala/org/scalafmt/sbt/HasScalaFmt.scala

This should be safe to be merged anyway...

Fix #583. Avoid try to format dirs

---

readme/Installation.scalatex

Was missing sudo in the `chmod` portion.

Fix Linux installation command

---

core/src/main/scala/org/scalafmt/config/OptIn.scala
core/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
core/src/main/scala/org/scalafmt/config/Settings.scala
readme/Changelog.scalatex
readme/Changelog05.scalatex
readme/Installation.scalatex
readme/Readme.scala

Changed some settings in the default style:
- includeCurlyBraceInSelectChains, fixes #444
- breakChainOnFirstMethodDot
Wrote changelog to docs.

Prepare for 0.5 release.

---

bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala

Initialize term display logger.

---

core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/test/VerticalMultiline.stat

Fixes an issue where verticalMultilineAtDefinitionSite affected classes,
instead of just `def` sites.

Fix issue on verticalMultilineAtDefinitionSite

---

readme.md

Welcome to the team @pjrt! Feel free to merge this PR :)

Add new "Team" section in readme

---

readme.md

@ysusuk has been quite active lately with scalafmt. He has made several valuable contributions to rewrites and patches. He well deserves to have merge rights. Welcome to the team @ysusuk 🎉

Add Iurii Susuk to the team!

---

core/src/main/scala/org/scalafmt/config/FilterMatcher.scala
core/src/main/scala/org/scalafmt/config/Pattern.scala
core/src/main/scala/org/scalafmt/config/RewriteSettings.scala
core/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
core/src/main/scala/org/scalafmt/rewrite/ExpandImportSelectors.scala
core/src/main/scala/org/scalafmt/rewrite/Patch.scala
core/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
core/src/main/scala/org/scalafmt/util/TokenTraverser.scala
core/src/test/resources/rewrite/AvoidInfix.stat
core/src/test/resources/rewrite/AvoidInfix2.stat
core/src/test/resources/rewrite/AvoidInfix3.stat

- this is initial commit
- works with 2+ infix applications
- tested on akka repo

#709: Feature request: AvoidInfix rewrite

---

core/src/main/scala/org/scalafmt/config/Newlines.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/util/TokenOps.scala
core/src/test/resources/newlines/alwaysBeforeTopLevelStatements.stat
core/src/test/resources/newlines/beforeTopLevelStatements.stat
readme/Configuration.scalatex

Hi, thanks for the help in Gitter!
Here is my first try to add a  flag for adding newlines before toplevel statements

Add flag for newline before toplevel statements

---

.github/ISSUE_TEMPLATE.md

Not all issues will be in the reduced form "I obtained ...; I would like ..".
So I generalised it a little, but kept the original template.
WDYT?

Generalise and structure the issue template

---

utils/src/main/scala/org/scalafmt/util/GitOps.scala

Added a filter for git diff command that should fix #759

#759 filter out deleted files on --diff

---

core/src/main/scala/org/scalafmt/internal/FormatWriter.scala
core/src/test/resources/align/addSbtPlugin.source

Fix vertical alignment on last block of file

---

cli/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
core/src/main/scala/org/scalafmt/config/hocon/Hocon2Class.scala

Make sure to always resolve HOCON config

---

.drone.yml
.jvmopts
bin/testAll.sh
build.sbt
intellij/readme.md
readme.md
sbt

- Don't require IDEA, it's slow and only relevant for intellij plugin development
- Add downloadIdea alias for intellij/updateIdea
- Automatically set file.encoding via .jvmopts
- Document gotchas in readme

Simplify build so `sbt test` "just works"

---

core/src/main/scala/org/scalafmt/internal/FormatOps.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/test/resources/default/ApplyInfix.stat
core/src/test/resources/default/Val.stat
core/src/test/resources/unit/ApplyInfix.stat
core/src/test/resources/unit/If.stat

Polish infix indentation around assignment.

---

core/src/main/scala/org/scalafmt/config/Spaces.scala
core/src/main/scala/org/scalafmt/internal/Router.scala
core/src/main/scala/org/scalafmt/util/TreeOps.scala
core/src/test/resources/spaces/InParentheses.stat
project/project/plugins.sbt

Fix #780, add spaces in parens flag

---

project/Deps.scala
project/plugins.sbt
project/project/plugins.sbt

Needed because of a few bin compat issues with the previous versions...

Switch to coursier 1.0.0-M15-5

---

core/src/main/scala/org/scalafmt/internal/FormatWriter.scala
core/src/main/scala/org/scalafmt/util/TokenOps.scala
core/src/main/scala/org/scalafmt/util/TreeOps.scala
core/src/test/resources/newlines/alwaysBeforeTopLevelStatements.stat

Multiline top level statement, addresses #893

---

core/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
core/src/test/resources/rewrite/AvoidInfix.stat

Fix AvoidInfix for methods with empty parameters list

---

readme/Installation.scalatex

Fix coordinates for scalafmt-bootstrap

---

readme.md
readme/Installation.scalatex

Review @pauldraper
It is my great please to invite @pauldraper to the team to help out with the sbt plugin. I personally never used the sbt plugin so I feel that it never got the love that it deserved. Paul, please don't feel committed beyond what time or motivation you have. If you have any doubts or questions, don't hesitate to ask for help or contact me directly :)
cc/ https://github.com/scalameta/scalafmt/issues/923

Invite Paul Draper to the team and document neo-sbt-scalafmt!

---

readme/Configuration.scalatex

binPackParentConstructors -> binPack.parentConstructors

documentation fix

---

core/src/test/resources/newlines/OffByOneParameterlessMethod.stat
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Fixes #600
This PR was created with help from @olafurpg at the [Scala Open Source Sprees](https://github.com/scalacenter/sprees) in Copenhagen 2017.

Break line if def equals is at columns + 1

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala

Fixes an issue where git commands would act oddly if `scalafmt` is called
from where NOT at the git root.

Fix #960 and #927: Oddness with git and non-root

---

readme/Changelog10.scalatex

Document removal of bestEffortInDeeplyNestedCode.

---

readme/Installation.scalatex

A miscellaneous bag of changes. Feedback welcome.

Tweak Coursier installation instructions

---

.travis.yml
bin/runci.sh
build.sbt
project/Mima.scala
project/plugins.sbt
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

org.scalafmt.config is not supported due to case classes breaking binary
compat on every new field.

Enable mima binary checks in CI.

---

scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala

Fix new GitOpsTest on OSX

---

readme/src/main/scala/org/scalafmt/readme/Adopters.scala

See https://github.com/http4s/http4s/pull/1359

Add http4s to adopters list

---

readme/Configuration.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala

add missing wonderbar to the optIn.breakChainOnFirstMethodDot code examples

add missing wonderbar to the optIn.breakChainOnFirstMethodDot code examples

---

readme/src/main/scala/org/scalafmt/readme/Adopters.scala

On behalf of Mendix RnD I send this pull request to have Mendix included into the list of adopters.

Add Mendix to the list of adopters

---

readme.md

This ensures that the last version will be correctly shown in the badge

Point to a correct project on scaladex

---

readme/Configuration.scalatex

Hopefully this is all that is needed 😅

Add section on align.openParenDefnSite

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-intellij/src/main/scala/org/scalafmt/intellij/FileDocument.scala
scalafmt-sbt/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Closes #1075 and #574
Took a stab at this.

Adds support for formatting .sc files using sbt options.

---

readme/Changelog07.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala

`afterImplicitKWInVerticalMultiline` instead of `afterImplicitAtDefnSite`

Fix documentation

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/i1116.stat

Fix #1116, insert space in type projection when selecting symbolic members

---

readme/Installation.scalatex

The scalafmt package is a formula, not a cask.

Correct Homebrew installation terminology

---

readme/Changelog07.scalatex
readme/Installation.scalatex

Fixes https://github.com/scalameta/scalafmt/issues/1127

Example for new sbt plugin

---

readme/Configuration.scalatex

added missing comma btwn 'more' & 'most'.

Configuration doc fix

---

readme/Configuration.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RedundantBracesSettings.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-case.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-if.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-precedence.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

Disable redundantBraces.generalExpressions by default.

---

scalafmt-tests/src/test/resources/test/Unicode.stat

The bug seems fixed with the upgrade to scalameta v3.7

Add repro for #1033.

---

readme/Installation.scalatex
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala

Add more examples for standalone library usage

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala

Include more information on "error due to bug" failure

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfDecoders.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/unit/Dialect.stat

Inline is a only a keyword in Dotty
Fixes https://github.com/scalameta/scalafmt/issues/1063

Disable inline modifier by default.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/unit/ApplyInfix.stat

Fix indent for nested infix operators

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Pretty-print parse error more nicely.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/OsSpecific.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtConfigTest.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/EmptyFileTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Don't crash on isWindows check, fixes #1207

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Config.scala

Re-add fromHoconString overload to please neo-scalafmt

---

project/Dependencies.scala

v0.8 was a feature release, there were no breaking changes

Upgrade metaconfig

---

readme/src/main/scala/org/scalafmt/readme/Adopters.scala

Add foursquare to adopters list

---

readme/KnownIssues.scalatex

Reduce a bit of confusion pending #1234

Add blurb about comment wrapping

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysComments.stat

This PR fixes https://github.com/scalameta/scalafmt/issues/1238

Fix invalid rewrite of trailingCommas=always

---

website/siteConfig.js

Enable search in website

---

docs/installation.md

Related issue: https://github.com/scalameta/scalafmt/issues/1221
---

Bring back the docs for sbt-scalafmt

---

build.sbt

Address https://github.com/scalameta/scalafmt/issues/1252

Add explicit dependency on org.scala-lang/scala-reflect

---

project/Dependencies.scala

I would like a Scalameta 4 version of Scalafmt.

Scalameta 4.0.0

---

build.sbt
project/plugins.sbt

Scala 2.12.7 bring some performance improvements / fixes.

Upgrade scala to 2.12.7

---

.travis.yml
project/build.properties
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-docs/src/main/scala/website/package.scala
scalafmt-tests/src/test/scala/org/scalafmt/ManualTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtProps.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatAssertions.scala

also update sbt to 1.2.6
work around scala/bug#11125 as needed

add JDK 11 to Travis-CI matrix

---

docs/installation.md

Pushing the comments made in https://github.com/typelevel/cats/pull/2567#issuecomment-432229443 into the docs.

Justify discouraging format on compile

---

docs/configuration.md

Also, use "presets" instead of "defaults".

Switch to non-legacy align = more

---

bin/test-release.sh
docs/CHANGELOG.md
docs/contributing-scalafmt.md

The changelog is auto-generated, @tanishiking feel free to push a commit adding more details or highlighting new changes.

Update changelog and document release process

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Type.stat

Remove space for variance annotations with underscore

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/test/includeNoParensInSelectChains.stat

Fixed error with includeNoParensInSelectChains and full qualified names

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala

This is the fix for the bug reported here #1447

Suppress cli output in case  option was set

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/test/scala/tests/DynamicSuite.scala

do not cache for ever invalid configs

---

scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Add a test for https://github.com/scalameta/scalafmt/pull/1469

Tweak a test that makes sure multiple exclude flags works as expected

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/BeforeCommentWithinMethodChain.stat

Keep indentation for comments within method chain

---

.github/ISSUE_TEMPLATE.md

While raising an issue I saw that the version in template is really old and also we moved the version into config. PR for the same
@tanishiking Let me know your comments

Update ISSUE_TEMPLATE to current version support

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala

Fix #1448 
Same as `--test`, but fails after first `MisformattedFile` error.

Add --check cli option

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/BeforeCommentWithinMethodChain.stat

Partial fix for #1484. I don't know this code all that well so I'm not sure if there are other cases worth testing. Thanks!
UPDATE: I think I fixed the rest of #1484. Please take another look if this isn't your first time.

Make comment blocks line up.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.stat

Fixed alwaysBeforeTopLevelStatements for modifiers 

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/i1300.stat

With chains alignment for "new" with mixins

---

build.sbt
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ConsoleScalafmtReporter.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtReporter.java

Use coursier/interface instead of coursier-small

---

docs/faq.md

typo danglingParenthesis -> danglingParentheses

typo danglingParentheses

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/Issue1509.stat

```scala
// before
if (true)
List(1) match {
case x =>
} else {
2
}
// after
if (true)
List(1) match {
case x =>
}
else {
2
}
```
cc/ @smarter

Insert newline for else keyword, fixes #1509.

---

project/plugins.sbt

sbt-mdoc update

---

readme.md

Mikhail has made several valuable contributions to Scalafmt including
the upgrade to Scala 2.13, which I believe will result in nice
performance improvements!

Welcome Mikhail Chugunkov to the team!

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Try.stat

Fixes #350
See examples of changes in:
https://github.com/kitbellew/scala-repos/commit/6199bb327e98be07db46d43f2f4b8dffeabeba3e?w=1

Router: treat try/finally the same as if/else #350

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-case.stat

RedundantBraces: fix how we find {} in func body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Fixes #1592
NB: There are *no diffs* on `scala-repos` for this PR.

Router: dangle only if breaking in multi-line lambda

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

No behaviour is modified, formatting is as before.

Various refactoring and simplification commits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/newdefault/ColumnWidth.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat

Fixes #1543. No changes to `scala-repos`.

Router bugfix: improve optimal token for assign

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/test/i1439.stat

Fixes #1547. Follow-on to #1440.

FormatOps: check "new anonymous" in infix indent

---

docs/installation.md

This will close #1502 
Not a ton to add, but I think it's great to include a little note about the automatic support that Metals has for scalafmt. Let me know if you'd like me to add anything else!

add in a bit of documentation about Metals

---

docs/installation.md

Users who don't know what Metals is may be looking for editor-specific
headers.
cc/ @ckipp01

Add headers for each invidiual editor that Metals supports.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ExpandImportSelectors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Patch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortImports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala
scalafmt-tests/src/test/resources/rewrite/AsciiSortImports.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix2.stat
scalafmt-tests/src/test/resources/rewrite/ExpandImportSelectors.stat
scalafmt-tests/src/test/resources/rewrite/PreferCurlyForYields.stat
scalafmt-tests/src/test/resources/rewrite/PreferCurlyFors.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-if.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat
scalafmt-tests/src/test/resources/rewrite/SortImports.stat
scalafmt-tests/src/test/resources/rewrite/SortModifiers.stat

Rewrite: rewrite patchsets unless any is no-format

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatOutput.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/Report.scala

A few of the changes appear to speed up the formatting slightly (approx 5%). Additionally, they will allow in the future to add generic handling of comments in the code, similar to whitespace.
No formatting changes are introduced.

State/FormatWriter: various optimizations and simplifications

---

build.sbt
project/Dependencies.scala
scalafmt-benchmarks/src/test/scala-2.12/org/scalafmt/benchmarks/BenchmarkOK.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtConfigTest.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtRunnerTest.scala
scalafmt-core/shared/src/test/scala/org/scalafmt/ScalafmtTest.scala
scalafmt-dynamic/src/test/scala/tests/DynamicSuite.scala
scalafmt-dynamic/src/test/scala/tests/ScalafmtVersionSuite.scala
scalafmt-tests/src/main/scala/org/scalafmt/util/DiffAssertions.scala
scalafmt-tests/src/test/scala-2.12/org/scalafmt/ScalafmtProps.scala
scalafmt-tests/src/test/scala/org/scalafmt/CommentTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/EditionTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/EmptyFileTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/FidelityTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/LineEndingsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/RangeTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/CanRunTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/ErrorTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatAssertions.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/GitOpsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

Until https://github.com/scalameta/munit/issues/47, https://github.com/scalameta/munit/issues/48 resolution

MUnit reverted to ScalaTest

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

This makes instantiating policies with the partial function look a bit
cleaner.

Policy: add apply() with partial func in 2nd group

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

FormatOps: extract methods to get func/case arrow

---

readme.md

Work around GitHub caches. May help with actual version info. Related to https://github.com/scalameta/scalafmt/issues/1659#issuecomment-586929897

Dummy parameter against github caches

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/FormatEvent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/src/test/scala/org/scalafmt/Debug.scala
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/CanRunTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Also, print debug after each test, not after all.

Test debug: create a debug instance per test

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat

RedundantBraces: don't rewrite to parens if nested typed func

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Type.stat

Fixed AST changes after formatting variant types with symbolic name

---

docs/CHANGELOG.md

Fixes #1775 
We need keep in mind website changelog when releasing: https://scalameta.org/scalafmt/docs/contributing-scalafmt.html#releasing

Changelog updated

---

build.sbt
project/Dependencies.scala
scalafmt-tests/src/test/resources/test/i1245.stat

Scalameta update

---

docs/configuration.md

Scalafmt has powerful config overriding feature but nobody knows about it :(
Helps with #1534

Document config overriding functionality

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

Fixes #1787. Follow-on to #1749.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/21a3a27b7e9fbf47cd2f44cdc89f5d049cb02e55

Router bugfix: handle implicit consistently

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat

Fixes #1809. Helps with #1627.

#1627 [14]: Router: single-line Defn lambda for fold only

---

scalafmt-tests/src/test/resources/test/i1527.stat

Tests for already fixed SearchStateExploded error (#1527)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfigException.scala

#1627 [16]: ScalafmtConfig: refactor checking source errors

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Use it for various existing traversal methods.

FormatOps: implement recursive findToken method

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Follow-on to #1846. Must have been interaction with another PR, showed up in `scala-repos` late.

Router bugfix: regression in statement/comments

---

docs/configuration.md

#1627 [15]: Documentation: describe newlines.source

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala

Error.NoMatchingFiles: don't display a stack trace

---

docs/configuration.md

Documentation: explain `newlines.topLevelStatements`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/RedundantBracesSettings.scala
scalafmt-tests/src/test/resources/default/Lambda.stat

RedundantBraces: re-enable general expressions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix3.stat

AvoidInfix: simplify, fix incorrect rewrites

---

docs/contributing-scalafmt.md

- build artifacts
- execute new artifacts

Docs: Assembling and Executing New CLI Artifacts

---

docs/configuration.md

Documentation: clarify glob pattern in the example

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-docs/src/main/scala/website/package.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtTest.scala

ScalafmtConfig: move default40 into the test suite

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: exclude nested partial function

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

#1627 [20]: Router bugfix: binPack call rules: overflow, dangling parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat

AvoidInfix: correctly determine when to wrap LHS

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat

#1627 [21]: Router: improve source=fold formatting of val/def

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-tests/src/test/resources/binPack/TermNameList.stat

Binpack literals: allow simple expressions, too

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: fix handling of tuples

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ContinuationIndent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/ContinuationIndent.stat

ContinuationIndent: add ability to control "with"

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/default/Comment.stat

FormatWriter: match on any horizontal whitespace

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/align/ArrowEnumeratorGenerator.stat

Pretty format multiline expressions in enumerator with align.arrowEnumeratorGenerator

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/ValidationOps.scala
scalafmt-tests/src/test/resources/default/Advanced.stat
scalafmt-tests/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/src/test/resources/default/Case.stat
scalafmt-tests/src/test/resources/default/For.stat
scalafmt-tests/src/test/resources/default/If.stat
scalafmt-tests/src/test/resources/newdefault/CaseNoAlign.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scalajs/Advanced.stat
scalafmt-tests/src/test/resources/scalajs/If.stat
scalafmt-tests/src/test/resources/unit/For.stat
scalafmt-tests/src/test/resources/unit/If.stat

DanglingParentheses: add ctrlSite flag

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ContinuationIndent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Class.stat

ContinuationIndent: add granularity to defnSite

---

readme.md

Discord link fixed (#1942)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

This didn't include multiline blocks.

FormatWriter: flush alignment blocks on blank line

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtSessionFactory.java

- the interface should have a single responsibility

interface ScalafmtSessionFactory shouldn't extend Scalafmt interface

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Indent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: shift lines after StateColumn align

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat
scalafmt-tests/src/test/scala/org/scalafmt/CommentTest.scala

FormatWriter: allow folding scaladoc to one line

---

docs/configuration.md
scalafmt-docs/src/main/scala/docs/DefaultsModifier.scala
scalafmt-docs/src/main/scala/docs/ScalafmtModifier.scala

mdoc DefaultsModifier: allow multiple defaults

---

docs/configuration.md
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-core/shared/src/main/scala-2.11/org/scalafmt/CompatCollections.scala
scalafmt-core/shared/src/main/scala-2.11/org/scalafmt/CompatParCollections.scala
scalafmt-core/shared/src/main/scala-2.12/org/scalafmt/CompatCollections.scala
scalafmt-core/shared/src/main/scala-2.12/org/scalafmt/CompatParCollections.scala
scalafmt-core/shared/src/main/scala-2.13/org/scalafmt/CompatCollections.scala
scalafmt-core/shared/src/main/scala-2.13/org/scalafmt/CompatParCollections.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Comments.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-docs/src/main/scala/website/package.scala
scalafmt-tests/src/main/scala/org/scalafmt/util/DiffAssertions.scala
scalafmt-tests/src/test/resources/unit/Comment.stat
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtProps.scala
scalafmt-tests/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatAssertions.scala

FormatWriter: implement wrapping of long comments

---

docs/configuration.md

Helps with https://github.com/scalameta/scalafmt/issues/1976 and https://github.com/scalameta/scalafmt/issues/1523

Spaces configuration documented

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Prepares for docstring formatting.

FormatWriter: minor refactoring of comment formatting code

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: don't rewrite nested Defn

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/StripMargin.stat

FormatWriter: fix empty 1st part of interpolation

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

TokenOps fix: blank line between mod and scaladoc

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Router bugfix: respect config style for tuples

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

FormatWriter: fold long oneline javadoc if no wrap

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Comment.stat

Router: break between comma and multiline comments

---

.scalafmt.conf
project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ImportSelectors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/TrailingCommas.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LiteralOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtConfigTest.scala

Dependency updates

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfDecoders.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-tests/src/test/resources/unit/Dialect.stat

Dependency: upgrade scalameta to 4.3.18

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/Scalafmt210.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Formatted.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicError.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflectConfig.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtVersion.scala
scalafmt-tests/src/test/resources/readme.md
scalafmt-tests/src/test/resources/test/Dialect.source
scalafmt-tests/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/ManualTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/dynamic/ScalafmtVersionSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/DiffTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Router: don't format #! lines in sbt files

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

Router: don't handle implicit for unsafeDefnSite

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Case.stat
scalafmt-tests/src/test/resources/newdefault/CaseNoAlign.stat
scalafmt-tests/src/test/resources/unit/Case.stat

Helps with #150. Helps with #2099.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/ac0b3d833e1fe685aceec02d58a9fb610eb8f862

Router: minor adjustments to handling of case clause and body

---

.github/workflows/ci.yml

Job for automatic native images uploading (#1711)

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RedundantBracesSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces-if.stat

Dedicated setting for redundant braces in if-else (#2038)

---

bin/install-scalafmt-native.sh

Github action for auto-uploading artifacts to releases can't zip them. So native images from v2.7.0 will be downloaded as is.
Another way is to zip them on CI but it requires not obvious to me yaml machinery

Install script compatibility with auto-uploaded artifacts

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala

The primary difference is that, unlike `PenalizeAllNewlines`, this new policy has an explicit start point and doesn't have an exclude option (i.e., `PenalizeAllNewlines` could potentially be represented as one or more `PenalizeNewlinesInRange` policies via a logical _or_).

PolicyOps: add new PenalizeNewlinesInRange policy

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/TokenRange.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala

Policy: refactor, change how exclusion is represented

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: fix align container logic for multiline alignment

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala

Cli: add an option to read file names from stdin

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

IndentOperator: move topLevelOnly and document

---

docs/configuration.md

Thanks for the project I really appreciate

[documentation] fix brace in example

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/DefDef.stat

Newlines: rename {never,avoid}InResultType

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/FileOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala
scalafmt-tests/src/test/resources/test/Dialect.source

Scalafmt: support `@`-reloaded Ammonite scripts

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Fixes #2175.
`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/59bc7a22cc12553cd38c8240546bf4a4db77b1bb

Router: attached comment as optimal in def body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

FormatOps: no simple space split in unfolded body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: remove unused FormatToken parameter

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: don't rewrite expression of match

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Rewrite: interpolate, new, new anon as simple expr

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-tests/src/test/resources/test/Dialect.source

Scalafmt: require space after `@` ammonite reload

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/ValidationOps.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

FormatWriter: force blank first line in docstrings

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/release.yml

I also added the dependabot file to make the process automatic.

Update actions versions to fix CI

---

.github/workflows/release.yml
project/build.properties

revert #2272 #2277

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/dotty/Enum.stat
scalafmt-tests/src/test/resources/test/Enum.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

The first change related to #2216. 
We've discussed with @tgodzik that it would be reasonable to introduce consecutive features in separate PRs so that it simplifies both the review process and introduction of further changes. Let me know if you prefer me to do this differently.
Here I attempted to support the enum in the exact same way that the class keyword is implemented right now.

Support enum in dotty

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala

StyleMap: warn if rewrite settings are overridden

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Follow up from https://github.com/scalameta/scalameta/pull/2207

Use recently added CaseTree instead of Tree for cases

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-tests/src/test/resources/scala3/GivenPatterns.stat
scalafmt-tests/src/test/resources/scala3/ImportingGivens.stat

Scala 3: given imports, pattern-bound givens

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/spaces/InterpolatedStringCurlyBraces.stat

Implements #2228
Previous misunderstandings with @olafurpg over CoC were resolved in Discord chat.
Please review again @kitbellew

Add spaces.inInterpolatedStringCurlyBraces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/AlignToken.scala
scalafmt-tests/src/test/resources/scala3/Enum.stat

More info about enums here: https://dotty.epfl.ch/docs/reference/enums/enums.html

[Scala 3] Allow enums to be aligned with classes, objects and traits

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

The release added support for Scala 2.13.5.

Update scalameta to 4.4.10

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/LineEndings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/TrailingCommas.scala
scalafmt-tests/src/test/resources/newlines/afterCurlyLambdaPreserve.stat
scalafmt-tests/src/test/resources/test/JavaDoc.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat

Config: allow "keep" where "preserve" is used

---

docs/configuration.md

Documentation: docstring.style=keep since v3.0.0

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: keep around some new anonymous expressions with select

---

docs/configuration.md

Documentation: reduce nesting, reword, caution on all defaults

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/default/Apply.stat

State: don't overflow single-line interpolations

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Make patches easier to apply -- patch(1p)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/unit/Comment.stat

FormatWriter: make sure comments start with `"// "`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat

Router: keep break for single-arg assign, dangling close

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Router: don't align `"( // comment"`

---

docs/configuration.md

Documentation: describe `importSelectors`

---

project/Dependencies.scala

Started making those PRs separate in order to make sure that the changes haven't broken anything

Update scalameta to 4.4.11

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

This method is only applied when `newlines.beforeMultiline` is classic, which in reality means both this parameter and `newlines.source` are not explicitly specified.
Hence, append `Classic` to the name and remove non-classic logic. Use the original method name to put the overall logic.
Also, merge the two similar rules, for `def a = ...` and `val a = ...`.

Router: simplify and refactor `getSplitsValEquals`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

This approach will also find the "colon at end of line".

FormatOps: simplify looking for template "curly"

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Also, abide by `newlines.source` for optional braces.

Router: handle `then/else/do/try/finally` with optional braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Make it easier to debug rule behaviour.

FormatOps: keep source line for optional braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/default/Class.stat
scalafmt-tests/src/test/resources/default/Comment.stat
scalafmt-tests/src/test/resources/default/DefDef.stat
scalafmt-tests/src/test/resources/test/JavaDoc.stat
scalafmt-tests/src/test/resources/unit/Package.source
scalafmt-tests/src/test/scala/org/scalafmt/CommentTest.scala

Docstrings: change wrap default to yes

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala

TermDisplay: don't invoke tput if TERM is not set

---

docs/configuration.md

Documentation: point to ScalaFiddle, AST Explorer

---

build.sbt
project/Dependencies.scala
scalafmt-tests/src/test/resources/scala3/Issues.stat

Update scalameta to 4.4.15

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/Issues.stat

Fixes https://github.com/scalameta/scalafmt/issues/2479

Use only the last non-comment token for binpack expire

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Class.stat
scalafmt-tests/src/test/resources/scala3/Given.stat

Newlines: define templateBody parameters

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysAlignMore.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultipleAlignMore.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNeverCommentsAlignMore.stat

Fixes #2449. Also improves alignment by detecting longer blocks of lines.

FormatWriter: do not overflow when aligning

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: `NoSuchElementException` for right brace

---

scalafmt-tests/src/test/resources/scala3/InlineTransparent.stat

Fixes https://github.com/scalameta/scalafmt/issues/2478

Add tests for #2478

---

scalafmt-tests/src/test/resources/scala3/Issues.stat

Fixes https://github.com/scalameta/scalafmt/issues/2480

Add tests for #2480

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/Issues.stat

Fixes https://github.com/scalameta/scalafmt/issues/2512

Fix issues with QuotedMacroType

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteScala3Settings.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

It would start with the default version rather than the current one.

RewriteScala3Settings: fix the decoder

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteScala3Settings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatWriter: insert optional-braces end markers

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ExpandImportSelectors.scala
scalafmt-tests/src/test/resources/scala3/RenameImportExport.stat

Fixes https://github.com/scalameta/scalafmt/issues/2535

Make sure ExpandImportSelectors uses correct dialect

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: remove single-block-within-block

---

scalafmt-tests/src/test/resources/scala3/Issues.stat

Fixes https://github.com/scalameta/scalafmt/issues/2522

[Scala 3] Add tests for indented curried params

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

FormatOps: matchingOpt unless tok from FormatToken

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Type.stat

Fixes https://github.com/scalameta/scalafmt/issues/2560

Fix issues with +_ type lambdas

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/default/Class.stat
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.stat

FormatWriter: additional changes in handling top-level-stat blanks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Fixes https://github.com/scalameta/scalafmt/issues/2559

Add end marker after the last token of a tree

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

FormatWriter: implement granular blanks control

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

FormatWriter: fix bugs around blank lines in top-level stats

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ExpandImportSelectors.scala
scalafmt-tests/src/test/resources/rewrite/ExpandImportSelectors.stat

ExpandImportSelectors: fix check for rename `=>`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: handle `newlines.beforeOpenParenXxxSite`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

FormatWriter: handle blank lines before end marker

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: fix tuples in optional-braces blocks

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/If.stat
scalafmt-tests/src/test/resources/default/Select.stat
scalafmt-tests/src/test/resources/scala3/TraitParams.stat
scalafmt-tests/src/test/resources/unit/Comment.stat

Router: implement alignment of closing paren

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Indents.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/If.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Indents: add a setting for ctrlSite (if/while/for)

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/TypeLambda.stat

Router: support align/danglingParens for tuples

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Newlines: beforeOpenParenXxx take fold/unfold/keep

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: allow single-line unfold for and/or types

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Indents.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: use extra indent with beforeOpenParenDefnSite

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

If conditions can now be included within an indented block after the if keyword.

[Scala 3] Add support for indented block after if keyword

---

scalafmt-tests/src/test/resources/scala3/TraitParams.stat

Fixes https://github.com/scalameta/scalafmt/issues/2597

[Scala 3] Add test for trait context bounds

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

I think most of the bigger issues were fixed, there still some things leftover, but nothing that should influence Scalafmt.
I think we should be good to do `3.0.0`

Update Scalameta to 4.4.24

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatWriter: fix `given` end marker label

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/default/String.stat

Newlines: implement `avoidForSimpleOverflow=[slc]`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Newlines: use `selectChains` instead of `source`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/binPack/ParentConstructors.stat

Router: preserve on `extends` if `binPack.parentConstructors=keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Router: apply `, {` rule to binPack case as well

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

Docstrings: allow a different maxColumn to wrap

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

BinPack: implement logic for unsafeXxxSite=Oneline

---

project/Dependencies.scala
scalafmt-tests/src/test/resources/scala3/InlineTransparent.stat

Scalameta: upgrade to v4.4.26

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: improve align container computation

---

docs/configuration.md

... and how the parameters are used.

Documentation: explain how alignment works

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: keep NL for opt braces in partial func

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/src/test/resources/rewrite/ExpandImportSelectors.stat
scalafmt-tests/src/test/resources/rewrite/Imports.source

Imports: if expanding only, do not group imports

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SyntacticGroupOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix2.stat

AvoidInfix: apply to left-associative only

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/TypeArguments.stat

Router: use {binPack,align}.bracketXxxSite options

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBracesStrInterpolation.stat

RedundantBraces: restore stringInterpolation flag

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/TrailingCommas.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala

Deprecate and copy existing value into that section. Helps with #2755.

RewriteSettings: add a trailing commas section

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultiple.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultipleComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat

FormatWriter: fix NL search after trailing comma

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/TrailingCommas.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultiple.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultipleComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat

Router: allowFolding for trailingCommas != never

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: in alignment, handle empty body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: skip Mod to find align container

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/src/test/resources/rewrite/Imports.source

Imports: in groups, match longest pattern first

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteScala3Settings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatWriter: other counting of end marker lines

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflectConfig.scala

ScalafmtReflect: don't pass classloader to Config

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

Newlines.topLevelStatementBlankLines: add minNest

---

docs/configuration.md

Documentation: describe `optIn.annotationNewlines`

---

docs/CHANGELOG.md

Changelog: refer to the github releases page

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala

Since the version is now guaranteed to be consistent with the package version, instead of trying multiple methods, we can call the right one directly.

ScalafmtReflect: use version to choose right call

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala

Since we added the `createSession` into the main Scalafmt interface, we no longer need to account for cases without this method.

ScalafmtDynamicRunner: remove custom session class

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala

Might help an IDE which caches config file contents.

ScalafmtReflect: add parseConfigFromString

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Fixes #2019. Fixes #1463. Fixes #1222.

FormatWriter: add braces if span exceeds threshold

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala
scalafmt-tests/src/test/resources/binPack/ParentConstructors.stat
scalafmt-tests/src/test/resources/default/TypeWith.stat

TreeExtractors: use Type.Apply in Type.With chain

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: another fix to break on wrong `} catch`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: fix optional braces in `if/while` cond

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat

Follow-on to #2415. Fixes #3013.

Router: fix for-do like while-do before

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/FormatOff.stat

Router: if format:off and NL, keep only NL splits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: check for placeholder in Apply

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/unit/Apply.stat

We fixed the invalid part earlier but incompletely.

TreeOps: adjust the followedBySelectOrApply logic

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Indents.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/Match.stat

Indents: implement matchSite

---

docs/configuration.md

Configuration: mention parameters for visit limits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

FormatWriter: allow code without leading space

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Config.scala

Config: in dynamic, allow stable or actual version

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

Router: use PenalizeNewlines to avoidInResultType

---

project/Dependencies.scala

Scalameta: upgrade to v4.5.4

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/src/test/resources/rewrite/Imports.source

Imports: put `given` at end of sorted selectors

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicError.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtModuleLoader.scala

CorruptedClassPath: pass URL instances, not String

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicError.scala

UnknownConfigError: improve the error message

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicError.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicSession.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtProperties.scala

ScalafmtDynamicError: use instead of UnknownError

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Contains a few parsing fixes around scala3 functionality backported to scala2.

Scalameta: upgrade to v4.5.5

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Later, it will add special handling of Term.ApplyInfix.

TreeOps: implement isCallSiteLeft

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: don't rewrite cond in do-while

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/src/test/resources/rewrite/Imports.source

Imports: handle case when importer ref is empty

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: keep around Assign within Apply

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: skip lbrace rule for partial initial expr

---

project/Dependencies.scala
scalafmt-config/shared/src/main/scala/org/scalafmt/config/ConfParsed.scala

Metaconfig: upgrade to v0.11.1

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Class.stat

Router: allow empty parameter list to align

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/default/Val.stat

FormatOps: don't format infix as patterns for val

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Type.stat

Router: fix handling of `+_` for scala3

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

In scalameta v4.6.0, it will no longer be empty but point to the token which comes before the parameter starts.

TreeOps: improve implicit `implicit` search

---

docs/configuration.md

Doc: mention dialect overrides in syntax rewrite

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

ConvertToNewScala3Syntax: only simple Repeated

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: always skip shebang line

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: handle tuple in unsafeDefnSite case

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/src/test/resources/rewrite/Imports.source

Imports: handle empty grouping labels

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Also, rename or refactor some methods.

FormatTokens: use getHead/Last, not tree tokens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: bugfix, detect end of annotation better

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: don't format lambda in classes/objects

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: exclude ArgClause under Init

---

project/Dependencies.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

Scalameta: upgrade to 4.7.3

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: add extra indent to fewer-braces apply

---

scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

Add tests for interleaved definitions

---

scalafmt-tests/src/test/resources/default/Class.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

Test class definitions with explicit implicits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

FormatOps: move opensImplicitParamList to TreeOps

---

scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Test non-vert-mult, interleaved, with implicits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps vertical multiline: fix interleaved defs

---

docs/configuration.md

Configuration: `fileOverride` is an absolute match

---

scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Add tests with no select after fewer braces apply

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: import mutable namespace only

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: force break on multi-stat try blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/Extension.stat

Router: `extension` is probably also a keyword

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: refactor applying rules

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: undo entire indent for fewerBraces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: apply fewer braces to new anonymous, too

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/FileOps.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

CLI: add instructions when version is missing

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: don't remove parens in Init args

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala
scalafmt-tests/src/test/resources/rewrite/SortModifiersScala3.stat

SortModifiers: do not sort `using`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: fewer-braces func not just in apply

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala

CliArgParser: clarify `--stdin` description

---

scalafmt-tests/src/test/scala/org/scalafmt/CustomStructureTest.scala

Add a full structure test for intermittent failure

---

scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

HasTests: locations could be null

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/test/Dialect.source
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatAssertions.scala

Scalafmt: don't parse shebang line as scala

---

project/Dependencies.scala
project/plugins.sbt

mdoc depends on metaconfig, so these must come together.

Update: metaconfig to v0.12.0, mdoc to v2.4.0

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala

Error: include doc url in SearchStateExploded msg

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala

Cli: version is necessary, may not be sufficient

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/FilterMatcher.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala

Regex: use pattern.matcher.find, not findFirstIn

---

scalafmt-tests/src/test/resources/rewrite/AvoidInfix2.stat

AvoidInfix: add tests for `of`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala

ProjectFiles: refactor getting parent dirs

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

ProjectFiles: implement Layout.withLang

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala

ProjectFiles: shorten len in recursive getLang

---

scalafmt-tests/src/test/scala/org/scalafmt/config/StandardProjectLayoutTest.scala

StandardProjectLayoutTest: rename to fix typo

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/AvoidInfixSettings.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix2.stat

AvoidInfixSettings: add `behavior.of` to default

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/AvoidInfixSettings.scala

AvoidInfixSettings: refactor defaults

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/AvoidInfixSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

RewriteSettings: rename `forSbt` to `forSbtOpt`

---

docs/configuration.md

Docs: increase `maxColumn` to showcase alignment

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/AvoidInfixSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat

AvoidInfixSettings: use scalatest ops in test only

---

project/Dependencies.scala
scalafmt-tests/src/test/resources/scala3/FewerBraces_unfold.stat

Scalameta: update to v4.8.15

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: exclude case of trailing commas

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Fixes a follow-up issue reported in #3653.

FormatOps: force NL for non-single-expr in finally

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Use to generalize a few cases, to avoid making assumptions about the underlying argument or just make them future-proof.

TreeOps: define `SingleArgInBraces` tree matcher

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Also, start using new methods available in that version.

Scalameta: update to 4.9.0

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_unfold.stat

FormatOps: fix fewer-braces lambda argument

---

docs/configuration.md

Documentation: add min version for `styleGuide`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala

In `onRight`, we will add a new case matching on RightParen which will need the same check for next token as is currently used for RightBrace.
Therefore, extract that check and apply it early. Helps with #3812.

RemoveScala3OptionalBraces: move next token check

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: "claim" index in `tokens`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala

FormatTokens: getDelimsIfEnclosed

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala

FormatTokens: import TokenOps._

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

This includes removing claims if the rewrite is abandoned, and adding a claim on the right token with its replacement. Helps with #3812.

FormatTokensRewrite: update claims in `onRight`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

TreeOps: extract both braces in SingleArgInBraces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala

FormatTokens: modify getHead/getLast

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: find only enabled rules

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala

Rewrite rules: pass FormatTokens as implicit

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala

LoggerOps: use Token.structure for logging

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala

RewriteTrailingCommas: take over check, refactor

---

scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_unfold.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysSingleLine.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatAssertions.scala

Test preserving non-folding trailing comma

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: token index in Replacement

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

Helps with #3812. Follow-on to #3828.

FormatTokensRewrite: obtain rule from Replacement

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

We just need to check that this index is not occupied by another format token, which could happen if a rule staked claim for this format token previously. Helps with #3812.

FormatTokensRewrite: reuse index claimed earlier

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

FormatTokensRewrite: pass FormatToken to resurrect

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

FormatWriter: trailing comma with a removed paren

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: simplify claiming on right

---

.scalafmt.conf

scalafmt: upgrade version v3.8.1

---

.scalafmt.conf

scalafmt: group parameters

---

.scalafmt.conf

scalafmt: avoid simple overflow

---

.scalafmt.conf
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala

scalafmt: enable RedundantParens rewrite

---

.scalafmt.conf
scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Patch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala
scalafmt-dynamic/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/config/ScalafmtConfigTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/Report.scala

scalafmt: don't ignore newlines in syntax

---

docs/configuration.md

Documentation: advise reading entire page first

---

docs/configuration.md

Documentation: add more context for `source=keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala

BinPack: remove stale warning about unsafeXxxSite

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/StyleMap.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

BinPack: drop `unsafe` prefix in call/defn sites

---

scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Test binPack.xxxSite with configStyleArguments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: refactor nlPolicy for binpack.callSite

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ConfigStyle.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

FormatOps: separate config style: exists or forced

---

readme.md
website/core/Footer.js

The discord invite possibly pointed to a different channel. Also, remove gitter from readme as it isn't used anymore.

Add or update discord links

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: simplify, add to empty block only

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: inline getAlignContainer(fmt loc)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

FormatWriter: don't insert braces in annotation

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: add style, get overflow in AlignLine

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: minor refactor, rename variables

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Newlines: add more keepBreak overloads

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: use FormatToken.Meta in ExtractFromMeta

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

{Format,Tree}Ops: use token index instead of hash

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

ScalafmtConfig: shorten the allowed maxColumn

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: refactor, replace formatToken/tok with ft

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

DanglingParentheses: bundle defnSite with excludes

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: add hasBreak, noBreak, hasBlankLine

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

DanglingParentheses: add bracketSite versions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: binpack defnsite: rename mustUseNL->nlOnly

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: binpack callsite: Spc for attached comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: binpack defnsite: generalize slb indicator

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: binpack callsite: move no-split indents

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

It could contain a multi-line comment.

FormatOps: extend body indent to end of line

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala

All the other combinations are already present.

PolicyOps: add `decideNewlinesOnlyBeforeToken`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

The local variable `beforeLhs` that it replaces shadowed an instance val which has a different meaning.

FormatOps: add InfixSplits.isAfterOp flag

---

scalafmt-core/shared/src/main/scala-2.12/scala/collection/mutable/package.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Add a scala-2.12 specialization since that method is only available in scala-2.13.

FormatWriter: use `HashMap.updateWith`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/spaces/NeverAroundInfixTypes.stat

Spaces: add `aroundSymbolicInfixOperators` params

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

Error: add reason to `SearchStateExploded`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: optional braces if ends in lone comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

RedundantBraces: don't remove if annotated

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: Ctrl body can be tuple in removed block

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: disambiguate end marker in keyword rules

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: combine two `case` splits via policies

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala

Split: expose `mod` via `modExt` in Split/State

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/TrailingCommas.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

FormatWriter: move parens rewrite checks elsewhere

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Rather than saving the location of the right brace in a lookup table, modify both left and right brace state immediately. Helps with #4133.

FormatWriter: modify brace-to-paren rewrite steps

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat

FormatTokens: get last skipping attached comments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatWriter: insert end marker after semicolon

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: don't break within comment in ctrl body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Otherwise, this might potentially lead to non-idempotent formatting as costs in subsequent attempts might be different. Helps with #4133.

Router: align costs to ignore current break

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: define chain splits as dedicated variables

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

 FormatOps: find optional braces in nested blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: define OptionalBraces.isJustBeforeXxx

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: check optional braces NL before comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Also, for Equals case, handle block directly. Helps with #4133.

FormatOps: refactor opt-braces rules with stats

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

TreeOps: check single element for multi-value tree

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps/RemoveScala3OptionalBraces: remove nested blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: preserve blank lines around control body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: adjust indent on open paren for end marker

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

FormatOps: force break after semicolon in CtrlBody

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: expand defn of multi-line top-level stat

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: move `indentedPackage` to FormatOps

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: no spaces.inParentheses if redundant paren

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: refactor template formatting slightly

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: remove redundant check

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: consolidate multiple align cases

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: refactor control-blocks single-line policy

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: slightly refactor setting blanks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: dedicated opt-braces rule for `with`

---

scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/unit/Package.source

Test nested catch within match, trailing comments, docstrings etc.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: adjust ctrl body expiration, NL forcing

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: verify that for-yield body is in braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: skip optimal in apply parens for `keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

FormatOps: pass current format token as implicit

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtOptimizer.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala

BestFirstSearch: invert {always -> possibly}Better

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

FormatOps: get ClauseSiteFlags fields implicitly

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala

TokenClasses: add matches/apply, to join unapply

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Newlines: define shortcuts for source kind

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: cosmetic, change import level

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Rename, return FormatToken, add a few simple conditions (like blank). Helps with #4133.

FormatOps: refactor endOfSingleLineBlock

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat

Router: preserving close break if source=keep

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: use isInfixRhs in startsNewBlockOnRight

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: extract state logic

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: also traverse past 0-cost parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/scala3/RenameImportExport.stat

Scala3 syntax: remove braces around single import

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/src/test/resources/default/String.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

BestFirstSearch: kill opt if failed single-line

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: do not penalize breaks in closing parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

Router: killOnFail in last binpack arg/parameter

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/default/Case.stat

Router: `recurseOnly` in `case if` when excluding

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: if excluding opt-braces, skip comments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

FormatWriter: don't wrap malformed scaladoc

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: add optimal token in pattern alternatives

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat

Check dialect to rewrite infix as part of `try`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: keep around select without dot

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

FormatOps: a "top-level" block is one with braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

FormatOps: no NL before infix op unless dialect OK

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: fix enclosed case body w/ paren after NL

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala

ScalafmtCoreRunner: print stack trace to stderr

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/Output.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/FileTestOps.scala

CliOptions: move NoopOutputStream to new Output

---

scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala

CliOptionsTest: expand, add tests, use System.out

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala

ScalafmtCliReporter: use info for downloader

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: keep NL policy before `if` guard if `keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBracesStrInterpolation.stat

Helps with #4133. Follow-on to #4276.

RedundantBraces: keep if they separate xml tokens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-if.stat

RedundantBraces: keep unrelated thenp/elsep apart

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala

BestFirstSearch: extract check for SLB policy

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: fix bug, possible infinite loop

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala

Policy: check if policy will apply to future token

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: extract processing optimal token

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: define getNext()

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala

Policy: allow checking if a sub-policy exists

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat

BestFirstSearch: state w/ SLB policy isn't `best`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scalajs/Advanced.stat

Router: extend SLB after scala.js right paren

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

This will allow us to determine more easily whether to kill on fail. Helps with #4133.

BestFirstSearch: shortestPath return failing state

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/scalajs/Advanced.stat

Router: kill on fail for select as infix rhs

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat

FormatOps: extend optimal token past left bracket + Type.Select is also SelectLike

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: don't compare Option and Binpack.Site

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/TreeSyntacticGroup.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/resources/test/JavaDoc.stat

Scalameta: upgrade to v4.10.0

---

build.sbt

SBT: upgrade scala 2.13 to patch 15

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests-community/src/test/scala/org/scalafmt/community/TestStyles.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/util/HasTests.scala

ScalafmtRunner: turn maxVisits into Option[Int]

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/default/Advanced.stat
scalafmt-tests/shared/src/test/resources/default/SearchState.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat

BestFirstSearch: recurse within parens as well

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/default/Apply.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/shared/src/test/resources/unit/Lambda.stat

FormatOps: consider scalajs tucking in getSlbEnd

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: can't remove after semicolon

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

The first token in a param clause with an `implicit` doesn't belong to the first param but to the param clause itself, so map it to that first param instead. Helps with #4133.

FormatOps: add first param to arguments with mod

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala

Split: separate original cost and later penalty

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-if.stat

RedundantBraces: `else-if` always ok if opt-braces

---

scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunityBuild.scala
scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunitySuite.scala

CommunitySuite: support excluding some styles

---

scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunityScala2Suite.scala

CommunitySuite: add tests for scala2 versions

---

scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunityScala3Suite.scala

CommunitySuite: add tests for scala3 versions

---

scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityScalaCliSuite.scala

CommunitySuite: add tests for scala-cli versions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat

Router: extract single stat from rewritten block

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat

RemoveScala3OptionalBraces: not with no-NL select

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: extend slb end past select for `keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: fix consistency based on src NL existence

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat

BestFirstSearch: arg clause an opt-zone for keep

---

scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala

CommunitySparkSuite: add more spark versions

---

scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityScalaJsSuite.scala

CommunitySuite: test scala.js version 1.17.0

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-if.stat

RedundantBraces: keep some around PartialFunction

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/rewrite/AvoidInfix.stat

TreeOps: ignore single block stat for NL optimizn

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala

CommunitySparkSuite: add spark v3.5.3

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat

FormatOps: ignore removed block in select chains

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

 Router: increase penalty for NL before colon

---

scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityAkkaSuite.scala

CommunitySuite: add versions of Akka

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

Router: extend SLB optimal for `(...`

---

scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityZioSuite.scala

CommunitySuite: add versions of zio

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/shared/src/test/resources/unit/FormatOff.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: add dedicated rule for formatOff

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala

ProjectFiles: add `.mill` to the default glob list

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-tests/shared/src/test/resources/rewrite/Imports.source
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

 Rewrite: remove one NL even if found many

---

scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityPlayFrameworkSuite.scala

CommunitySuite: add versions of playframework

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: no conflict b/w preferNoSplit/skipNoSplit

---

scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityMunitSuite.scala
scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityPlayFrameworkSuite.scala
scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityScalaCliSuite.scala
scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityScalazSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala

Let's try to have one or two versions of each repo, ideally differing major releases or currently in active use.

CommunitySuite: remove some versions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/TokenRange.scala
scalafmt-tests/shared/src/test/resources/default/Apply.stat
scalafmt-tests/shared/src/test/resources/default/Idempotency.stat
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: change lambda space splits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

FormatOps: extend SlbEnd to lbrace, colon, comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala

State: delay penalty if `avoid` in interpolation

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/shared/src/test/resources/default/Apply.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

State: don't penalize punct overflow

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfDecoders.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunityBuild.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunityRepoSuite.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunitySuite.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/TestStats.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/Debug.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/util/HasTests.scala

CommunitySuite: check the total states visited

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: fix handling of comment-space-dot chain

---

.github/workflows/ci.yml
build.sbt
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunitySuite.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala

CommunitySuite: add Intellij Scala plugin code

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

State: fix logic allowing punctuation overflow

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala

Extend information for FormatToken, Tree and State.

LoggerOps: expand logging

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-if.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

If the comment is standalone, possibly after removing previous tokens, keep the brace.

RedundantBraces: revise keeping brace post comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

Specifically, if there's no optimal-token constraint and the policy has no SLB component.

BestFirstSearch: memorize failed search sometimes

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

If the value is true, it works, as before, as both a no-opt zone and a possible recurse-block candidate.
If the value is false, it will only work as a recurse-block candidate.

BestFirstSearch: turn noOptZones into a Map

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

FormatOps: recognize optional-braces partial func

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

It has already been done for folded and classic.

FormatOps: adjust block body in CtrlBody.unfolded

---

scalafmt-tests/shared/src/test/resources/test/JavaDoc.stat

Also, clarify test names (adding `oneline=` prefix to its value).

test/JavaDoc: fix test config according to title

---

docs/installation.md

see: https://github.com/com-lihaoyi/mill/issues/3959

Fix broken link.

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/shared/src/test/resources/test/JavaDoc.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

FormatWriter: 2nd try to fold oneline after format

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: add ParamClause as well, to Unit/ArgClause

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Force break unless fewer-braces expression is enclosed.

Router: refactor handling fewer braces in select

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: for/infix before select like fewer-braces

---

.github/ISSUE_TEMPLATE.md

Issue template: direct parsing issues to scalameta

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

It was iterative on `}` and not on `,`.

RedundantBraces: check `}` removal consistently

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/default/Apply.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

It occasionally leads to an impossible solution.

BestFirstSearch: memorize SLB states separately

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/shared/src/test/resources/trailing-commas/trailingCommasMultipleDanglingParens.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Simplify by disposing of other constraints. Also, check trailing comma on right brace in RedundantBraces.

RewriteTrailingCommas: remove for any close delim

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/shared/src/test/resources/test/JavaDoc.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Scalameta: upgrade to v4.12.6

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

RedundantBraces: not every Ident continues Infix

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/intellij/shared/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/shared/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/shared/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/shared/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: use only possible split if `( comment NL`

---

docs/configuration.md

Configuration: document how imports sorting works

---

project/Dependencies.scala
scalafmt-tests/shared/src/test/resources/test/JavaDoc.stat

Scalameta: upgrade to v4.13.0

---

scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/TermDisplay.scala

We only need a couple of simple counters rather than concurrent maps and download buffers that were used in the original coursier code.

TermDisplay: simplify, remove url stuff

---

scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/TermDisplay.scala

The only difference is whether we reposition the cursor after that.

TermDisplay: use the same format in fallback

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala

Infix bugs: fix getting single arg, next operator

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests-community/intellij/shared/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/shared/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/shared/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/shared/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/default/ApplyInfix.stat
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Splits: refactor handling infix before left brace

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-tests-community/intellij/shared/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/shared/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/shared/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/shared/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Splits: keep NL after comma if source=keep

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/scala3/PolyFunction.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Splits: fix handling before left bracket

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala

Splits: no optimal single line if cost positive

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Instead of parent traversal, let's just check if the eol owner is within the position of a row owner.

FormatWriter: compare eol owner tree positions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Now that the owner is always right owner of the stop FormatToken, we no longer need to store it explicitly.

FormatWriter: in AlignStop, store isSlc, not owner

---

.github/workflows/release.yml

CI: separate publishing docusaurus

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Do not concatenate newlines with spaces to append to string buffer, and DRY with respect to delayedAlign usage. Also, avoid using `return`.

FormatWriter: refactor appendWhitespace

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/shared/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

FormatWriter: add align shift to multiline strings

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-tests-community/scala2/shared/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/shared/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/shared/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Splits: apply infix splits between lhs and comment
