scalameta/scalafmt

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Router: fix inconsistent indentation for `: tpe`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/src/test/resources/unit/FormatOff.stat

When `format:off` lines exceed `maxColumn`, some splits will be penalized for exceeding `maxColumn` and others will be penalized for violating the `format:off` marker.
Make sure that `format:off` violations have higher penalty. Fixes #2596.

BestFirstSearch: increase `format:off` penalty

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat

SingleLineBlock leads to fewer paths to explore so use it instead of PenalizeNewlines when in reality the latter should lead to equivalent formatting.
In this case, a 10000 penalty on any newlines without any exclude ranges with an available lower-cost alternative will in most cases be the same as using single-line format.
Exceptions include cases with multiline constants as arguments, and some rare cases of previously suboptimal formatting, due to complexity of preceding code.

Router: minor optimization for apply

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

This is a follow up from https://github.com/scalameta/scalafmt/pull/2594#pullrequestreview-685371567

[Scala 3] Allow `then` and `if` at the end of indentation under danglingParentheses = false

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Also, in Router, only unindent single-arg binpack apply. Fixes #2612.

FormatOps: look up the format token for tree head

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala

It was using `files` which is never empty, instead of `customFiles`.

ScalafmtRunner: fix bug with diff and custom files

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/AlignToken.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

This PR adds `:=` to the default list of aligned tokens. The reason why `:=` is being added is because its used frequently in sbt files and if you are writing something like
```scala
ThisBuild / scalaVersion := "2.13.6"
ThisBuild / version := "0.1.0-SNAPSHOT"
```
And you are doing vertical alignment of tokens it makes sense to align `:=` just like you would with `=` i.e. so you would end up with
```scala
ThisBuild / scalaVersion := "2.13.6"
ThisBuild / version      := "0.1.0-SNAPSHOT"
```
I can verify this works locally with the following `.scalafmt.conf` configuration
```
align.tokens.add = [
{code = ":=", owner = "Term.ApplyInfix"}
]
```
This PR should do the equivalent as a default.

Add := as a default AlignToken

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat
scalafmt-tests/src/test/scala/org/scalafmt/CommentTest.scala

Prior to this fix, ScalaDoc headings were rewritten to numeric values if `docstrings.wrap` was set to `yes`. The specific version I was using locally was `3.0.0-RC5`. Examples of what I was seeing:
- `==Foo==` became `122Foo122`
- `===Foo===` became `183Foo183`
The delimiter calculation was multiplying a char by a number, which resulted in a numeric value.
Haven't contributed here before - sorry if I've missed anything! I added a test which showed the old behavior and verified the fix, ran all of the tests afterwards, ran scalafmt on my changeset.

Fixing ScalaDoc heading output.

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

This might also help with obscure file resolution issues around our native builds. Fixes #2616.

CliOptions: store paths as File, resolve on demand

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtVersion.scala
scalafmt-tests/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

Previously, we'd parse the configuration file into a `typesafe.config` object, then convert it to a HOCON string and invoke the formatter config parser on it. If there's a parsing error with that string, the formatter wouldn't know where it came from and refer to `<input>` as the source of the configuration.
Instead, pass the path to the config file directly to the new method allowing parsing configuration from a file. Fixes #2631.

Scalafmt: parse configuration directly from file

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Since `oneArgPerLineSplits` is not empty, the newline split is always unused.
Follow-on to #1763.

Router: fully remove the dead comma split

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

Reduces the number of states and thus "Search state exploded" failures. Fixes #2633.

BestFirstSearch: use full search in nested blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/VerticalMultilineDefnSite.stat

The rule mistakenly matched the wrong `(` and led to a binpack-like formatting of default parameters containing an Apply.

FormatOps: fix bug with vertical multiline

---

docs/configuration.md

I tried for a while to use the `mdoc:scalafmt` approach to document this, but it was a snake eating its tail, so I resorted to this basic version for the sake of getting _something_ out there for users.

Add documentation for Markdown formatting

---

docs/configuration.md

It's minor, but still, they are different.

configuration.md: rename "argument" to "parameter" in the definition position

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Match the right end marker and allow comments before it.

FormatWriter: improve end marker handling

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

- The regular code blocks contain full leading whitespace while markdown block are relative to the opening fence thus handle them differently.
- Fix an off-by-1 margin calculation applicable to all code blocks.
- Allow top-level terms in scaladoc.

FormatWriter: print markdown code blocks relative

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-tests/src/test/resources/rewrite/PreferCurlyFors.stat

PreferCurlyFors: count non-Guards, not Generators

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

FormatOps: find stmt starts after redundant parens

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/src/test/resources/rewrite/Imports.source

Imports: implement contiguousGroups logic

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Fixes https://github.com/scalameta/scalafmt/issues/2725

Respect newlines parameter in extension methods with a single param

---

.gitignore
scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Previously, in case if there an error in configuration the error was suppressed and the exit code was `0`.
That's affected scalafmt [upgrade in scalameta/scalameta](https://github.com/scalameta/scalameta/runs/3392476513#step:4:37) where we didn't notice that our config is wrong.

Cli `--test` - return non zero exit code

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Remove the overall guard on significant indentation. Fixes #2730.

ConvertToNewScala3Syntax: guard on dialect flags

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveEmptyDocstrings.scala

Fixes #2039. Follow-up to #2733.

RemoveEmptyDocstrings: implement as a rewrite rule

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatWriter: valid syntax for end marker labels

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: fix alignment of multiline defns

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scalajs/Class.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

It was also present in isDefnSite.

TreeOps: classify Type.Apply only as isCallSite

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala

This simplifies the case when both left and right are comments. Helps with #2755.

Router: rule for comment left before comment right

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Addresses non-idempotent formatting in #2781.

TreeOps: fix statement start for rewritten lambda

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala

Otherwise, it conflicts with HOCON reserved keyword. Fixes #2840.

IndentOperator: rename `include` to `includeRegex`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala

Just to synch it with docs https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects.

Use a lower case for runner dialects in the error message

---

.github/workflows/ci.yml
.github/workflows/release.yml

This is required, as explained in: https://github.com/dwijnand/sbt-dynver#setup
Without it, our tests running in CI end up with "0.0.0" as the version.

Workflows: be sure to fetch tags with --unshallow

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-tests/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

Because the -dynamic module doesn't include the necessary -core.
This is follow-up to #2839; prior to that change, current had been used for CliTest with "core" option but that was fixed in #2873 to detect the current build and use the core runner.

ScalafmtDynamic: download even current build

---

build.sbt
scalafmt-dynamic/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

Around version release time, the tag points to the new version but it hadn't yet been published and hence not availalble, hence we can't use the stable version.

DynamicSuite: use previous stable instead

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/newlines/alwaysBeforeTopLevelStatements.source

First, ignore Template when computing nest since it has the same nesting level as its parent.
Second, start with 0 to avoid an off-by-1 error.
Fixes #2888.

FormatWriter: bug fix when computing nest

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtConfigTest.scala

1. Since the caller uses a wrapped similar to Try, makes no sense to throw here.
2. To allow proper path name matching, we need to have the full path.

 ScalafmtConfig: getConfigFor returns Try, uses AbsoluteFile

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflectConfig.scala

Previously, it was sufficient to check that `rules` was non-empty; but it is no longer enough as some rewrites are triggered via other params.

ScalafmtConfig: add methods to detect rewrites

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/NamedDialect.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/resources/test/Dialect.source

ScalafmtConfig: allow `fileOverride` shortcuts, set cross-build dialects

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala

When handling of `.md` files was added to `Scalafmt.formatCode` method (see #2563), `ScalafmtDynamic.tryFormat` should have added support for versions before 3.0.0-rc7 (which came out with that change), instead of 2.6.3 which added support for `.sbt` and `.sc`.
The logic in `ScalafmtDynamic` needs to complement (rather than mirror) the logic in `Scalafmt.formatCode`.

ScalafmtDynamic: fix handling of .md files

---

scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtException.java
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtReporter.java

For cases when the tool is invoked inside an IDE, this provides a better context for the error than a vanilla runtime exception.

ScalafmtReporter: use ScalafmtException to wrap

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/BatchPathFinder.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/GitOps.scala

Since not all means to locate files actually use git, it seemed like a
suboptimal location.

BatchFileMode: move file search logic from GitOps

---

scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/GitOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/sysops/GitOpsTest.scala

If we try to format files based on git output, and git fails, scalafmt will silently do nothing because a git failure is returned as an empty list of files, as if no files are present or have been modified.

GitOps: do not mask exceptions, propagate instead

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Apparently, scaladoc doesn't allow newlines for this specific tag. Fixes #2940.

FormatWriter: format `@usecase` tag on one line

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

Workaround for scalameta/scalameta#2516.

FormatWriter: fix alignment for incorrect `//` pos

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Pattern.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat

ScalafmtConfig: set default infix exclude for sbt

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala

That style uses either config style (which preserves or forces dangling regardless of the setting) or binpacking without dangling. Currently, binpacking ignores the dangling setting but is about to use it.

ScalafmtConfig: no dangling parens for scala.js

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala

Do not check this repeatedly in many places as redundant.

Split: centralize noIndent handling

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Comment.stat

Since we can potentially reformat a long single-line comment into a multi-line comment, we can't attach anything that followed the MLC after a break.

Router: do not attach comma after a comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

The current rule could occasionally lead to overflow since it didn't use a `killall` (remove path on failure) optimal token, and then would arrive at a point where other viable alternatives would have been set aside.

Router: binpack defn single-line to avoid overflow

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/unit/Comment.stat

Remove special case for binpacked comments, allow standalone comments.
For trailing-wrapped comments, rather than waiving penalty completely, use the column that opening "/*" occupies.

State: fix overflow of trailing comments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/default/String.stat
scalafmt-tests/src/test/resources/unit/Comment.stat

Since we can support cases of inactive overflow (comments which would later be wrapped, or cases when minor overflow is allowed), we should not look at the column to detect this.

BestFirstSearch: improve active overflow detection

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/default/String.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

Using cost and delayed penalty proved to be insufficient. Fixes #3012.

State: keep explicit penalty to detect overflow

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat
scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat
scalafmt-tests/src/test/resources/unit/DefDef.stat

Since we now can rewrite single-line comments as multi-line, the latter need to be treated the same, or idempotence will arise.

Router: treat multi-line comment before NL as SLC

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/default/Advanced.stat

If the case body contains more than one statement, with infix being the last one, then infix is considered to be part of a top-level Block.
Hence, we need to treat the standalone infix the same, for consistency.

FormatOps: consider infix case body as top level

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

This makes formatting with or without an end marker consistent. Follow-on to #3021.

FormatOps: ignore end marker for ctrl body purpose

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

We will be formatting with term indent as a parameter, to support nested terms, hence let's remove this method lest it get used incorrectly by mistake.

FormatWriter: remove appendWithMargin for scaladoc (part 2)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

For relative-indent-sensitive markdown elements like this, starting on the first line might lead to non-idempotent formatting.

FormatWriter: do not start "```" on top line (part 7)

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: handle then and do similar to else/yield

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat

Router: preserve break after `while` if `keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

We were handling it differently in some cases, and inconsistent with `while` and other `for`.

FormatOps: unfold yield correctly and consistently

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

We currently handle `while` with multi-stat expression differently than with a single-stat expression. Lets use the same approach with `for`. Follow-on to #3037.

Router: handle `for-do/yield` the same as `while`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

Prepare for scalameta upgrade to next version (v4.4.32) which supports nested terms in scaladoc lists and tags.

FormatWriter: refactor scaladoc formatting, escape text a-la code fence

---

scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/AbsoluteFile.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/FileOps.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/GitOps.scala

Otherwise, the formatter won't be able to use a symlinked configuration file.

FileOps: support symlinked files or directories

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: indent, handle comma in repeated enum cases

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

Fix bug in binpack=oneline implementation:
- handling of the first arg is different from subsequent ones (which
uses a single-line block no-split policy)
- the single-line block policy must also exclude multiline strings.

Router: disallow breaks in args in binpack=oneline

---

docs/installation.md

The slim version of scalafmt has not been 15 KiB for a long time; the size of 2.7.5 in October 2020 was 27Kb while 3.3.3 is 123Kb.

Installation: update package sizes as of 2022

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/String.stat

Router: implement newlines.inInterpolation logic

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/test/IndentOperator.stat

current `topLevelOnly` was likely intended to implement https://github.com/scala-js/scala-js/blob/main/CODINGSTYLE.md#long-expressions-with-binary-operators but the result is not as described.
the new `enclosedAlone` option attempts to do that instead, but needs confirmation from scalajs developers.

FormatOps: implement indentOperator.exemptScope

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/test/JavaDoc.stat

Previsoly in some cases there were additional unwated spaces inside code
lines.

Preserve indentation inside codeblocks

---

project/Dependencies.scala

Solves transitive dependency issue with pprint. Fixes #3098.

Dependency: upgrade metaconfig to 0.10.0

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/test/StripMargin.stat

Fixes #3090.
- For strings, didn't use the parameter to `.stripMargin` call to detect the right strip margin character.
- For interpolations, didn't handle strip margin at all

State: correctly compute line widths in strings and interpolations with strip margin

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/binPack/ParentConstructors.stat
scalafmt-tests/src/test/resources/scala3/Enum.stat
scalafmt-tests/src/test/resources/scalajs/Class.stat

FormatOps: improve binpacking parentConstructors

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/String.stat

Router: no `inInterpolation=allow` if scala3 `if`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala

Apply it both for primary infix expression as well as possible infix on the left-hand side.

AvoidInfix: extract isWrapped, checkMatchingInfix

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat

FormatOps: handle `if` as if no `else` when `keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

No tests, only manifests via dynamic loading, for some reason, but tested locally using the repository created for the attached issue. Fixes #3185.

Router: handle empty return type (procedure decl)

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala

This leads to a confusing "unknown error" message while masking the real problem. Helps with #3192.

ScalafmtReflect: don't wrap in UnknownError

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: for scala3, move NL before macro to after

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: fix bug with block in if/while cond

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala

In case open paren in a infix expression is not part of the arg but precedes it (as will be done in scalameta 4.5.5), handle it, too.

RedundantParens: handle infix arg if not enclosed

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/default/Lambda.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

This now allows us to use a single approach which is no longer overly sensitive to whether the scalameta parser includes the parentheses as part of the enclosed or enclosing tree. Required for #3200.

RedundantParens: detect enclosed trees properly

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala

This method will apply only to parens, not just any matching delimiters, and will in the future also include those just outside the tree.

FormatTokens: implement isEnclosedInParens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Will be needed when we upgrade scalameta to v4.5.6.

TreeOps: move findEnclosedXxx from RedundantParens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Follow on to #3207. Fixes #3215.

RedundantParens: fix bugs introduced in v3.5.3

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

In scalameta v4.5.6, some enclosed trees do not actually contain the enclosing parentheses, hence check for these cases.

FormatTokens: check outside parens for enclosed

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: only scala3 match-as-operator

---

project/Dependencies.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

Fixes parsing of additional anonymous functions. Fixes #3241.

Scalameta: upgrade to v4.5.9

---

bin/install-scalafmt-native.sh

The install script would fail when the `$INSTALL_LOCATION` variable included spaces (and probably other characters as well).
This change quotes all the variables containing paths to avoid the above issue.

Fix native install script when using spaces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-tests/src/test/resources/rewrite/ExpandImportSelectors.stat
scalafmt-tests/src/test/resources/rewrite/Imports.source

Rewrite: check BOF/EOF when looking for LF

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat

FormatOps: force config style for all call sites

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Depending on how scalameta parses the code, the left brace could be just before the multistat block (previously covered) or at the head of it. Fixes #3276.

FormatOps: check for left brace in multistat block

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Newlines: add forceBeforeAssign

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: bugfix, check else for opening brace

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

ConvertToNewScala3Syntax bugfix: `_` only in types

---

docs/configuration.md

Also, add the entry describing type wildcards.

Documentation: describe `convertToNewSyntax` flags

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Some trees (like Init) have multiple sets of arguments, and we need to identify the right group -- and the open paren/bracket for it. Fixes #3309.

FormatOps: force config style on token, not tree

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Indents.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ModExt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/test/IndentOperator.stat
scalafmt-tests/src/test/resources/test/IndentOperatorFormatInfix.stat

State: extend indent if relativeToLhsFirstLine

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/FileFetchMode.scala

CLI: add --mode diff-ref, deprecate --diff-branch

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat

Apply it only if there are no breaks before start of exclude range.

PolicyOps: unindent correctly in binpacking

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/For.stat
scalafmt-tests/src/test/resources/rewrite/AvoidInfix3.stat
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

That is done in some places and missed in others; and there's always a space between a comment and a `)`.

Router: always add space between `(` and comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/ErrorTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatAssertions.scala

The formatter's job is not to validate code but to format it.

ScalafmtRunner: always allow top-level terms

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/src/test/resources/test/IndentOperator.stat

State: relativeToLhsLastLine on same-line comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

This will allow passing a different tree as childTree.

FormatOps: refactor findEnclosingInfix

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

This approach deals better with zero-span trees (e.g., Name.Anonymous).

TreeOps: improve findEnclosedBetweenParens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Indent.scala

Also, no need anymore to check for Empty specifically.

Indent: don't switch between identical indents

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/unit/Lambda.stat

Doing so was actually preventing folding of the first lambda, since the block rules force a newline.

TreeOps: don't look for nested lambda in block

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Regardless of how `scalameta` treats enclosing parens (whether owned by the tree they enclose, or by its parent), let's assign the enclosed tree as the owner. Exceptions include cases where parens are an integral part of the parent (tuple, if/while conditions etc.)

FormatOps: enclosing parens owned by enclosed tree

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

`Defn.Macro` in most cases should behave exactly like `Defn.Def`, and so should `Decl.Def` for method signature formatting. These additions cover somewhat obscure cases (since macros are generally rare and their bodies are simply a proxy for another method), but let's add them for completeness -- and correctness - sake.

Defn.Def: add Decl.Def and Defn.Macro as needed

---

.github/workflows/ci.yml
.github/workflows/release-drafter.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

Set permissions for GitHub actions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

- exclude only last right paren (control expressions like if/while/for)
- ignore empty tokens (Xml.End, Interpolation.End)
- allow procedure-syntax Decl.Def (no type)
- detect top-level invocation directly, not via elemIdx

TreeOps: fix ownership of enclosed trees

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Since parens surrounding function parameters are actually part of the entire function tree, let's fix two problems:
- for parens around function parameters, fix the LHS depth computation to consider only the parameter trees, not the entire function
- for parens around the entire function, don't force one-arg-per-line logic since it is only intended for the parameters
Helps with #3417.

Router: improve handling of parens in functions

---

docs/faq.md

There is a stray brace at https://scalameta.org/scalafmt/docs/faq.html#which-configuration-options-minimize-diffsconflicts-in-version-control. This PR removes it.

Documentation: Remove stray closing brace

---

.github/workflows/release.yml

Otherwise any tool running on JDK 8 will fail.

chore: Release scalafmt on JDK 8

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Indent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: handle fewer braces and refined types

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Ensure that `allOwners` not only exclude the current paren owner but all the previous ones, too, making sure they are correctly sorted by their position.
Then reverse their order for Policy.Relay, thus ensuring that the left, or `before`, part of every relay is a simple policy, with the complex Relay in the `after` position.
Helps with #3466.

FormatOps vertical multiline: improve relay policy

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Handles `using/implicit` after a secondary bracket clause (possible with interleaved parameter clauses), if `implicitParamListModifierForce=before` was set, consistently with how they are handled after a paren clause.
For that, separates rules for bracket and paren cases. Helps with #3466.

FormatOps vertical multiline: fix implicit force

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala
scalafmt-tests/src/test/resources/vertical-multiline/VerticalMultilineDefnSite.stat
scalafmt-tests/src/test/resources/vertical-multiline/excludeDanglingInDef.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

The case of implicitParamListModifierPrefer=after setting (default) was incorrectly handled with vertical multiline. The test changes show that it wasn't working for cases with multiple parameters in a group.
Helps with #3466.

FormatOps vertical multiline: fix implicit prefer

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Follow-on to https://github.com/scalameta/scalafmt/pull/3469, where some single-param implicit groups were handled incorrectly.
Earlier, if implicitParamListModifierForce=after was used, we would only prohibit single-line formatting for multi-param groups, thus excluding single-param groups.
Helps with #3466.

FormatOps vertical multiline: one-param implicits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Class.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

Previously, we would handle the first `implicit` differently if none of the params have an explicit `implicit` keyword.
In reality, we should relax the check and do this if not all params have an explicit keyword. The idea being, if they all do, then the initial one belongs to the first parameter rather than the group.
Helps with #3466.

TreeOps: fix handling implicit group keyword

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

Specifically, implicitParamListModifierForce=after should not apply when `implicit` is explicit rather than applies once to the entire group. Helps with #3466.

FormatOps vertical multiline: explicit implicits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Since the entire line shares the same container, no need.

FormatWriter: remove container from AlignStop

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Class.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/src/test/resources/vertical-multiline/verticalMultiline.stat

Specifically, scala syntax prohibits repeated modifiers (in this case, repeated `implicit` on the first parameter) and requires `val` or `var` on parameters with explicit modifiers. The respective parser change will come in scalameta v4.7.5.

FormatOps: don't support invalid param modifiers

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: minor refactor in `.select` handling rule

---

scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Add tests with/without select after `.match`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Exclude the trailing comment. Fixes #3497.

Router: fix `beforeOpenParenDefnSite = unfold`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/vertical-multiline/VerticalMultilineDefnSite.stat

Specifically how it interacts with `newlineAfterOpenParen`. Fixes #3509.

FormatOps: fix `verticalMultiline.arityThreshold`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala

We now need to extend this functionality, and the existing simple Either is no longer sufficient.
Towards #3496.

FormatTokensRewrite: turn Replacement into class

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

The original code happened to accomplish the same but this approach is more explicit, and will allow a fix later.
Towards #3496.

RedundantBraces: move `{` for func body blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat

FormatOps: handle `.match` as select + apply

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

And don't indent select after them, as that's not yet supported by the compiler. Fixes #3489.

Router: don't add extra indent for fewer braces

---

build.sbt

Use Resolver.sonatypeOssRepos instead of Resolver.sonatypeRepo

---

docs/configuration.md

Docs: clarify implicitParamListModifierForce

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

TreeOps: get the whole implicit clause, not values

---

docs/configuration.md

The line I changed wasn't updated after renaming (`exclude` -> `excludeRegex`, `include` -> `includeRegex`) since v3.1.0.
I also changed the order of them in this line to follow the same order that they were explained in this document.

Fix docs/configuration.md indentOperator section

---

project/Dependencies.scala

Fixing https://github.com/scalameta/scalafmt/issues/2793, which was fixed in coursier 2.1.0-RC2.

Bump coursier version to 2.1.2.

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala

Follow up to https://github.com/scalameta/scalafmt/pull/3544, the proposed version string looks something like:
`version = '3.7.4'`
While scalafmt only accepts strings formatted like:
`version = 3.7.4`
Curiously enough, the original issue (https://github.com/scalameta/scalafmt/issues/3543) had it right 😅

Fix proposed version syntax

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Indents.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Now that dotty compiler supports indented fewer-braces chains since v3.3.1-RC1, let's implement this formatting. For #3489.

Router: handle parameter `indent.fewerBraces`

---

scalafmt-config/jvm/src/main/scala/org/scalafmt/config/PlatformConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/AlignToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Comments.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/NamedDialect.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtParser.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/SortModifiers.scala

Causes warnings in recent versions of 2.13 compiler.

Use explicit type annotation in implicit defs

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-tests/src/test/resources/scala3/Match.stat

Addresses rewrite failure found by @lenguyenthanh in lichess-org/lila#13160.

RemoveScala3OptionalBraces: not match if infix lhs

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Instead of handling a specific owner of the left brace (previously, it was a Term.Match only), let's instead look for infix when we encounter the right brace instead, and ensure that the next token is not the op of an infix.
This also handles the case when Term.Match was not an LHS but in the middle of an infix chain.
Follow-on to #3573.

RemoveScala3OptionalBraces: handle infix on rbrace

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala

In older versions of scalameta, `extends` was not part of template, and we had to identify the tree just preceding it.
Also, make sure to handle cases when the template is empty (in that case there's no reason to break before a non-existent `extends`).
Fixes #3580.

Router: use template to break before `extends`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Historically, the parser returns `Type.Name("Unit")` for declarations or definitions using the procedure syntax (i.e., no explicit `: type`).
However, that tree occupies no tokens and hence needs to be ignored.

TreeOps: skip empty types in defDefReturnType

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Indents.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Indents: ignore fewerBraces if indentation is 1

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala

It was deprecated in scalameta 4.3.0, used since 2.3.0-RC2.

Remove use of deprecated PlatformTokenizerCache

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Previously, self-type ends just before the `=>` but in the next version of scalameta it will end on `=>` instead. Let's handle both cases.

Router: handle self-type whether it ends in `=>`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala

Alignment logic accumulates alignment shift for matching lines, with the assumption that the extra space will definitely be added.
However, we don't add extra spaces to no-split cases, instead attempting to delay them until the next token... but if the next token is also a no-split, then the extra alignment space is lost, leading to incorrect formatting.
One such example is `(` which typically has no spaces before or after.
Helps with #3614.

FormatWriter: accumulate align shift correctly

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: implement `align.delayUntilSpace`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/unit/Apply.stat
scalafmt-tests/src/test/resources/unit/ApplyInfix.stat

Router: implement `spaces.beforeXxxArgInParens`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-tests/src/test/resources/default/String.stat
scalafmt-tests/src/test/resources/test/StripMargin.stat

Specifically, for PenalizeAllNewlines and SingleLineBlock policies. Fixes #3608.

PolicyOps: use `newlines.ignoreInSyntax`

---

docs/configuration.md
docs/installation.md

Installation: document COURSIER_REPOSITORIES

---

docs/installation.md
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/CoursierDependencyDownloader.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtProperties.scala
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/RepositoryCredential.java
scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/Scalafmt.java

It will presumably help solve scalameta/sbt-scalafmt#108.

Interfaces: add credentials to public interface

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: fix Defn as optional braces block

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysSingleLine.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasNeverSingleLine.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat

RewriteTrailingCommas: allow tuples as well

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenClasses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala

Scalameta is gradually phasing out macros, so let's stop using custom classifiers.
Also, let's switch to using standard scalameta token branches instead of custom ones defined within scalafmt:
- Trivia -> Token.Trivia
- Whitespace -> Token.Whitespace
- Delim -> Token.Symbolic
- Literal -> Token.Literal
- rename Keyword as Reserved and represent it as Token.Keyword and false/true/null
- remove Modifier since it's covered by Reserved and used only once, where Reserved applies already

TokenClasses: don't use classifiers

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-config/shared/src/main/scala/org/scalafmt/config/ConfParsed.scala

ConfParsed: don't mask parsing/retrieval errors

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala

difflib could return an empty string when the only difference is in the line endings of the strings being compared, which currently leads to a "silent" error (because the empty diff is output).
Instead, let's explicitly clarify that that is what happened.
Fixes #3675.

InputMethod: check for empty diff

---

.github/workflows/ci.yml

Now that scalameta supports jdk21, and scalafmt uses mdoc-parser, let's start validating the formatter with jdk21 in pre-commit checks.

YML: Add java21 to the build

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Config.scala
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtReflect.scala
scalafmt-dynamic/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

Also, restore that same class in the repository so older versions of the dynamic ScalafmtReflect will continue functioning even if they won't be using the class. Helps with #3689.

ScalafmtReflect: lazily load obsolete class

---

build.sbt
scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala
scalafmt-dynamic/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

This will allow us to avoid the problem that we saw with 3.7.16, when we introduced a bug with dynamic loading but only discovered it after the release. Fixes #3689.

DynamicSuite: test nightly version via local build

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/NeverInfixPattern.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala

Do not use FilterMatcher as it will be insufficient soon. Helps with #3699.

NeverInfixPattern: implement own matching method

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/NeverInfixPattern.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix2.stat

NeverInfixPattern: allow to match lhs as well

---

docs/configuration.md

improvement: Warn users not to use an example config without discussion

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/AvoidInfixSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-tests/src/test/resources/rewrite/AvoidInfix.stat

AvoidInfixSettings: consolidate AvoidInfix params

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

The current issue is that the span is computed using `leftLineId` of the token just before and the token at the end. However, `leftLineId` refers to the beginning of the token, thus multiline comments are incorrectly accounted.
Instead, use the token at the beginning of the span and increase by 1. Fixes #3731.

FormatWriter: fix end marker handling

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_unfold.stat

When a fewer braces call is used before an infix operator, that operator may not be indented as it will otherwise be interpreted as part of the fewer-braces argument.
This fix leaves a few cases (notably, many for newlines.source=unfold) still broken, but that requires a change to the parser which will be released in the new version of scalameta.
Helps with #3720.

FormatOps: outindent after fewer braces in infix

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-dynamic/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Previously, we would just get a stack trace:
```
Exception in thread "main" java.lang.IllegalArgumentException
at sun.nio.fs.UnixFileSystem.getPathMatcher(UnixFileSystem.java:286)
at org.scalafmt.config.ProjectFiles$FileMatcher$Nio.<init>(ProjectFiles.scala:74)
at org.scalafmt.config.ProjectFiles$FileMatcher$.$anonfun$nio$1(ProjectFiles.scala:70)
at scala.collection.immutable.List.map(List.scala:250)
at scala.collection.immutable.List.map(List.scala:79)
at org.scalafmt.config.ProjectFiles$FileMatcher$.create(ProjectFiles.scala:69)
at org.scalafmt.config.ProjectFiles$FileMatcher$.nio(ProjectFiles.scala:70)
at org.scalafmt.config.ProjectFiles$FileMatcher$.apply(ProjectFiles.scala:64)
at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$2(ScalafmtCoreRunner.scala:27)
at …
```

bugfix: Show exception from path matcher correctly

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

That way, a rule could check whether any previous token had been handled by another rule.

FormatTokensRewrite: claim current token as well

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

FormatOps: set indent correctly for enclosed body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat

TreeOps: relax when trailing comma paren possible

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Also, now it can be used in Router after `=>`.

FormatOps: fix `functionExpire` when rewritten

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Remove this method and create a reusable FormatToken at invocation site.

FormatOps: getMustDangleForTrailingCommas(Token)

---

docs/configuration.md

Documentation: expand section on `SortModifiers`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/SortSettings.scala

These variables can later be re-used for alternative orderings. Helps with #3788.

SortSettings: create a variable for each modifier

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/SortSettings.scala
scalafmt-tests/src/test/resources/rewrite/SortModifiers1.source

SortSettings: implement the `styleGuide` preset

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-tests/src/test/resources/scala3/Issues.stat

Apply this default unless another dialect, different from the primary one, was explicitly specified through `fileOverride`. Fixes #3787.

ScalafmtConfig: use Sbt dialect for .sbt files

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeExtractors.scala

For instance, Term.Block or Term.PartialFunction.

`:` could be from the single term in ArgClause

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteScala3Settings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala

Let's turn it into a class, with separate setting fields, rather than a single enum. Helps with #3812.

RewriteScala3Settings: expand RemoveOptionalBraces

---

scalafmt-dynamic/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

The versions being replaced lead to exceptions when running against current library.

DynamicSuite: test newer versions without problems

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala

Specifically, make sure that remove-optional-braces comes after redundant-braces and redundant-parens.

FormatTokensRewrite: sort rule factories

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

That way, within one rule we'll be able to invoke a different one, and the replacement value will indicate which rule actually processed the substitution.

FormatTokensRewrite: move Rule into Replacement

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

We will need it to check configuration of the left token when processing the right token via a different rule. Helps with #3812.

FormatTokensRewrite: ScalafmtConfig in Replacement

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

Previously, we'd handle the case of `foo(x => { ... })` by:
1. replacing the `(` with a `{`
2. "pretending" to replace the `{` with a `(`
3. upon encountering the `}` for a fake `(`, removing the `(` and changing on the owner of the `}`
4. then removing the `)`
Instead, let's modify steps 2, 3 and 4 as follows:
2. remove `{`
3. remove `}`
4. replace the closing `)` with a `}` moving it to the position of the `}` in step 3, along with token ownership.

RedundantBraces: fix "moving" braces around func

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Previously, we didn't allow it as the scalameta library didn't provide a way to check when it was actually possible. Helps with #3812.

RemoveScala3OptionalBraces: allow leading infix op

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

It makes sure that the replacement stored at that index refers to the same format token. The opposite could happen if a rule staked claim for this format token previously.
Helps with #3812.

FormatTokensRewrite: add getClaimed method

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala

FormatTokensRewrite: define `Replacement.isRemove`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Exclude expressions enclosed in braces or parens. Helps with #3812.

TreeOps: rename, improve `endsWithFewerBraces`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

Hence, point right token to next index instead. Helps with #3812.

FormatTokensRewrite: token map expects left token

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: `claim` implicit FormatToken

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: onRight proxy in Replacement

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: return index, vs rule applied

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala

Since the code aims to remove the parens assuming the next brace is not mutated by another rule, let's explicitly stake claim to that brace. Helps with #3812.

RedundantBraces: claim left brace inside parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_keep.stat

Specifically, just like after fewer braces, we shouldn't indent leading infix before fewer braces either. Helps with #3812.

FormatOps: fix leading infix before fewer braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_unfold.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat

Other cases already implement this. Helps with #3812.

Router: break on `(lambda` to keep trailing comma

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/FewerBraces_unfold.stat

RedundantBraces: remove parens and trailing comma

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

FormatTokensRewrite: track source index explicitly

---

docs/configuration.md

Do it like everywhere else in the doc.

Docs: use parens, not brackets for `since vX.Y.Z`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtOptimizer.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Use `MinSpan` instead, for consistency with similar `fewerBracesXxxSpan` parameters under `rewrite.scala3.removeOptionalBraces`.

ScalafmtOptimizer: rename forceConfigStyleOnOffset

---

project/Dependencies.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala

Scalameta: upgrade to v4.9.3

---

.scalafmt.conf
scalafmt-core/shared/src/main/scala/org/scalafmt/config/FormatEvent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala

scalafmt: enable SortModifiers with `styleGuide`

---

.scalafmt.conf
readme/src/main/scala/org/scalafmt/readme/Readme.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/CliArgParser.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/NamedDialect.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Patch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala
scalafmt-dynamic/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala
scalafmt-tests/src/test/scala/org/scalafmt/CommentTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/CustomStructureTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/RangeTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtProps.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtRunnerTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/ScalafmtTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/UnitTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/FileTestOps.scala
scalafmt-tests/src/test/scala/org/scalafmt/config/ScalafmtConfigTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/HasTests.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/Report.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/StyleMapTest.scala

scalafmt: align strip margins

---

.scalafmt.conf
project/Dependencies.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala

scalafmt: enable AvoidInfix rewrite

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

The tests added were either non-idempotent or showed a bug in `fold` formatting which produces different output depending on breaks in input (which is contrary to what `fold` is supposed to do).

FormatOps: can't look at breaks for fold/unfold

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

In the usually unreachable default case, let's use the built-in toString method rather than the more verbpse (but harder to read) LoggerOps.log2. Inspired by #3891.

Router: use built-to FormatToken.toString

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

We used two separate rules depending on whether there had been a break, which is prohibited for either fold or unfold, and in case of fold, the two rules were inconsistent.

Router: fix fold bug after semicolon

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: rename location to floc, consistency

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Use it also as an indicator of absence of single-line comment. Helps with #3465.

FormatWriter: add non-SLC owner to AlignStop

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: move logic to getAlignNonSlcOwner

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: add `ft` method to AlignStop

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

Current assumption is that stops in each line of an align block match positionally, that is, first stop of every line matches the first new shifted column, etc.
However, later on we will break this assumption, by adding intermediate (nested) stops in some lines.
Therefore, each stop will need to contain reference to its own shifted column, via a wrapped-integer object.
Helps with #3465.

FormatWriter: share shifted columns between lines

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala

FormatWriter: match columns in tryAppendToBlock

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Since we changed this method to return the type of config style rather than a simple boolean, we used this type to make other format choices. However, Force should always take precedence as it doesn't depend on the formatting choices in the original code.

FormatOps: prefer ConfigStyle.Force over Source

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat

Previously, how we handle `binpack.callSite=true` depended only on `optIn.configStyleArguments`, and `danglingParentheses.callSite` was ignored completely.
Also, the declared `scala.js` style, which purported to depend on the existence of a break before closing parenthesis, wasn't properly done.
Both opening and closing parentheses were output tucked in all cases but one, when both of them were dangling in the input (and the choice of whether to dangle or tuck depended solely on `configStyleArguments`).
Now let's introduce a small modification, so that we can express more formatting alternatives, and fix `scala.js` style.
Specifically, associate the two variants above with dangling parentheses in the disabled state.
When it's enabled, determine whether to tuck or dangle on break before …

Router: fix scala.js style for binPack.callSite

---

.github/workflows/ci.yml

Latest version is now 14 but it doesn't include sbt.

Github actions: explicitly use macOS-12

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

State column is unlikely to exceed 24 bits (or 16+ mln bytes), but even in cases when it might, a given token (that is, at a given State depth) cannot conceivably be formatted at two different column values which are a multiple of 2^24 bytes apart.
Hence, let's form state key by keeping indentation (just like before) at 8 bits, limiting column to 24 bits and combining with depth in the remaining 32 bits (and this combining is what ensures no hash conflict).

BestFirstSearch: switch to Long as State key

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/OptIn.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Currently, the `optIn.configStyleArguments` parameter applies both to call-site as well as defn-site clauses.
Instead, let's move it to `newlines.configStyle.xxxSite` and separate the two.
Helps with #3954.

Config-style: separate control for call/defn sites

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Currently, the `runner.optimizer` parameters always force config-style formatting when `newlines.configStyle.xxxSite.prefer` is true, even though they were intended primarily to affect the route search.
On the other hand, there could be cases when a user wouldn't enable the `newlines.configStyle.xxxSite.prefer` flag for regular operation (for instance, it makes no sense for `newlines.source=fold/unfold`) but would still be interested in forcing config-style.
Therefore, let's add the sibling `xxxSite.forceConfigStyleIfOptimized` flag to decide when to force.
Helps with #3954.

Config-style: control over forcing vs optimization

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtOptimizer.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Initially, we would only optimize around call-site argument clauses. Now let's add defn-site parameter clauses as well.
Also, let's rename the optimizer parameters to clarify the fact that they don't necessarily _force_ config-style formatting.
Helps with #3954.

Config-style: allow optimizing defn site clause

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

FormatOps: use token index instead of hash

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/scala3/Extension.stat

FormatTokens: add more methods around comments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Also, for trailing commas, presume close break; the same logic is used in all other cases. Helps with #3954.

FormatOps: pass close-break indicator for cfgstyle

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: binpack: refactor policies, newline split

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

In particular, we should relax the nlOnly requirement in that case. Helps with #3954.

Router: binpack callsite: fix literalsSingleLine

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/DanglingParentheses.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

It will collect together defn-vs-call-site-specific configuration flags. Helps with #3954.

FormatOps: create auxilliary class ClauseSiteFlags

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/binPack/TermNameList.stat
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat
scalafmt-tests/src/test/resources/scalajs/Class.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultiple.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultipleComments.stat

The `scalaJs` modification of `ScalafmtConfig` is, among other things, defined as having config style enabled and dangling parens disabled.
Earlier, we accidentally swapped the two flag values, so let's fix it. Helps with #3954.

FormatOps: fix scala.js style implementation

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

Router: treat infix argument clause like any other

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/For.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultiple.stat
scalafmt-tests/src/test/resources/vertical-multiline/excludeDanglingInDef.stat

Here, in case dangling is off, rely only on close-delimiter breaks to detect desire for config-style formatting, scala.js-style. Helps with #3954.

FormatOps: expand config-style source detection

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Router: clause site: refactor dangle indicators

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ConfigStyle.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/binPack/LiteralList.stat
scalafmt-tests/src/test/resources/binPack/ParentConstructors.stat
scalafmt-tests/src/test/resources/binPack/TermNameList.stat
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/TypeArguments.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat
scalafmt-tests/src/test/resources/scalajs/Class.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlwaysComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultiple.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasMultipleComments.stat
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasPreserve.stat
scalafmt-tests/src/test/resources/unit/Comment.stat

Also, modify it so that it matches configuration parameters better. In most cases, it will either preserve formatting (which tests may not show as they operate on non-formatted code) or can easily be configured to match existing formatting.
This change partially restores some of formatting changes introduced in recent commits, by making their results more consistent with new logic.
Fixes #3954.

Router: Align binpack.{call,defn}Site behaviour

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

We can't force a newline before closing parenthesis because the policies for intervening splits might actually disable that, and for scala.js it would also require forcing a newline after the opening parenthesis.

Router: fix handling of binpack=oneline

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

Otherwise, we might get a return type for a definition starting with a delimiter of a middle parameter, while the intention is normally for a final parameter instead.

Router: get return type only on colon

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

In fact, FuncParamClause uses a paren, not a bracket.

FormatOps: process all clauses together

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scalajs/Class.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

This now allows us to handle bracketed arguments.

FormatOps: add all arguments to `argumentStarts`

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

Otherwise, it was leading to widespread non-idempotency problems.

FormatOps: use src=keep to open break for scala.js

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/TypeArguments.stat
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

Include comma and any attached comments after it.

Router: extend single line for bp.defnsite=oneline

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

Previously, the code was computing splits differently for tokens with a break and without one. Since we could potentially have no-break in the source but format with one, this could introduce non-idempotency.

FormatOps: in CtrlBodySplits, add consistency

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat
scalafmt-tests/src/test/resources/scalajs/DefDef.stat

For NoSplit, we intend to penalize all newlines up to the closing paren of the argument clause, but we failed to add this policy for oneline, possibly because it was forcing a single line - but to the first comma, not the closing paren.

Router: fix bp.callsite=oneline penalty bug

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala

Similar to many other policies, add a `conv` method.

Policy: use common logic for all methods in Or/And

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/PolicySummary.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala

Also, emphasize that the `FormatToken` parameter is for the token after the split, not at the split.

Policy: add a Split parameter to `unexpired()`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat

First, the subsequent break we should force is before a Dot which comes from a Select, not a Comma.
Second, we should cancel forcing of that break if there's another break which is output after the argument and before the dot or parenthesis.

Router: fix bp.callsite=oneline post-comma policy

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala
scalafmt-tests/src/test/resources/rewrite/PreferCurlyFors.stat

If we are not rewriting parentheses, we shouldn't remove semicolons as they are required. Exclude the `if` guards, however, as they can come without a newline or semicolon.

PreferCurlyFors: don't rewrite semicolon only

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala

The BestFirstSearch algorithm doesn't allow this anyway.

Split: block optimal token with non-zero cost

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/scalajs/Apply.stat

With binpack.callSite=oneline, we are assuming that we can always break before a select dot; for source=keep, it wasn't true so let's fix it. However, penalize this newline split so that it's only used sparingly.

Router: add NL split in select chain for src=keep

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ReaderUtil.scala

Also, apply it to `BinPack` presets.

ReaderUtil: refactor, expose custom value parsing

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

Also, add a method to tell when a break before select is possible.

FormatOps: refactor GetSelectLike

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

In addition, make sure to use the `bracketXxxSite` versions as needed.

Router: refactor handling of binpack comma args

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

The policy was almost always the same, so we simply need to propagate the boolean decision, and add the special case of `fold` and `yield` at the end.

Router: refactor single-line block logic

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RewriteTrailingCommas.scala
scalafmt-tests/src/test/resources/trailing-commas/trailingCommasAlways.stat

Don't check equality of owners of comma and closing delimiter, it's no longer guaranteed. Also, inconsistent with the check in FormatWriter so that could lead to further non-idempotency. Fixes #4058.

RewriteTrailingCommas: handle optional braces case

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/String.stat

Router: increase NL penalty within interpolation

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

It is already checked for any removed braces, while the original `body` is not and hence could lead to non-idempotent formatting.

FormatOps: in folded ctrl body, use `adjustedBody`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala

This will allow us to support CRLF and any multi-newline sequences such as LFLF.

Token.LF: replace all references with Token.AtEOL

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/scala/org/scalafmt/util/FormatAssertions.scala

Now that the parser supports shebang tokens, there's no need to handle this as a special case anymore.

Scalafmt: remove special case of shebang prefix

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatToken.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/scala/org/scalafmt/EmptyFileTest.scala
scalafmt-tests/src/test/scala/org/scalafmt/LineEndingsTest.scala

Now that the parser supports both line ending types in input directly, we can generate the right output rather than do a post-conversion.

Scalafmt: move line ending choice to FormatWriter

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Previously, and still for other values of `newlines.source`, we force breaks over the entire `else` chain. Also, in FormatOps, treat `else<NL>` as opt-braces. Fixes #4104.

Router: src=keep force NL only for matching `else`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-tests/src/test/resources/default/DefDef.stat

TokenOps: backquoted tokens don't "end" in symbol

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: don't rewrite `try { (a, b) }`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

In reality, it's unclear why ApplyUnary extends Term.Ref, but since Term.Select does, too, let's introduce a special-case handling for it. Fixes #4116.

RedundantParens: don't rewrite unary within select

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

It was accidentally removed in #4096, was handled by an annotation rule.

Router: restore Shebang token handling

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat

RedundantParens: don't rewrite `Init`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala

`newlinesBetween` returns the number of actual newlines, but not the number of newline-representing tokens (which could be fewer if MultiNL is used). Leads to allocating too many and ending up with a null.

FormatTokensRewrite: fix MultiNL copy bug

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Also, skip cur token when searching for next `=`.

Router: move up rule for def/val `=`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat

It was incorrectly forcing a newline in some cases.

Router: fix `annotationNewlines=false`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

When optional braces are not enabled, there may not be a newline at all.
When optional braces are enabled, a newline after extension declaration must come with a significant indentation.

Router: fix extensions with/out optional braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/src/test/resources/rewrite/Imports.source

Fixes playframework/playframework#12822.

Imports: improve blank line detection

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Also, make sure a lone catch case is formatted as multi-line (i.e., has a break between `catch` and `case`), or else the next expression at the same indent level will be interpreted as the body. Helps with #4133.

Router: no space after `=>` if empty body

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat

Router: apply src=keep around `: return-type`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/default/String.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Fixes non-idempotence and incorrect handling of avoidForSimpleOverflow containing only `tooLong` (which applies only when there's no possible alternative which doesn't overflow). Helps with #4133.

Router: extend optimal token to include comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

FormatOps: fix cond between `while` and `do`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

There are only limited contexts where it is OK (`case` being one, but it is handled elsewhere). Helps with #4133.

RedundantBraces: don't remove empty blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Let's not use the Space split when we know that it will be removed along with the brace being change to paren.
This will allow us to avoid non-idempotent formatting problems as these spaces might cause the code to overflow the line narrowly, which would not happen without the spaces.
Helps with #4133.

Router: no space around `{` to be changed to `(`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: use optimal token for brace-ending chains

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

FormatTokens: move `getBraces` from TreeOps

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

No need to call the `maybe`-block method. Helps with #4133.

FormatOps: definite NL in OptionalBraces.BlockImpl

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

As a generalization of `isTreeSingleExpr`. Helps with #4133.

TreeOps: implement `getTreeSingleExpr`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/src/test/resources/align/DefaultWithAlign.stat

FormatWriter: align on actual splits, not original

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Literals.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LiteralOps.scala
scalafmt-tests/src/test/resources/literals/binary.stat

Add formatting to handle binary literals, which were added in Scala 3.5.0.
Those are of the form 0b111 or 0b111L and so are susceptible to both literals.binPrefix and literals.long.
The 3.5.0 release uses 0B111 in its examples, but the original SIP 42 uses 0b111. I chose 0b as the default, as it looks a lot nicer to me.
There is a new test file (`binary.stat`) and the documentation was updated (it's missing a `since` comment).
The changes address my own feature request: fixes #4176.

Add literal.binPrefix setting to format binary literals.

---

scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicSession.scala

Otherwise, it might lead to a NullPointerException.

ScalafmtDynamicSession: check config has a parent

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

Add simplified special case for optional braces, no need to check that it contains statements. Helps with #4133.

BestFirstSearch: refactor recursing on blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SyntacticGroupOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

FormatOps: don't use unapply on various trees

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat

For some reason, the earlier implementation would only recurse after the first non-brace character. Logically, if we want to process a block as a unit, we should start with the left brace and end with the right. Helps with #4133.

BestFirstSearch: recurse right after opening brace

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

With our rewrite rules, end markers can be added later and hence cannot be consulted at this point. Also, turns out the fix in #4171 was to add the match on NewAnonymous and not the end marker. Helps with #4133.

Router: ignore end marker for open paren indent

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala

FormatOps: opt-braces `catch` uses newlines.source

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Unfortunately, checking the owner of a comment is not reliable as the parser deals only with positions of non-trivial tokens. Let's instead simply look for the dot which separates components of a select. Helps with #4133.

Router: modify select-like detection for comments

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: keep `then` NL cost at 1 even if no space

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala

FormatOps: move `isJustBeforeTree` to FormatTokens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

Instead of doing it first, and then having to undo later. Helps with #4133.

BestFirstSearch: only update `best` at the end

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala
scalafmt-tests/src/test/resources/scalajs/Apply.stat

In addition to prioritizing states by cost and depth, let's also prefer optionally states with fewer lines, using them for fold and keep values of newlines.source. Helps with #4133.

State: add lineId and use it in state ordering

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Decision.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-tests/src/test/resources/rewrite/RedundantParens.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Sometimes it will have to be tucked, and a conflicting policy will also remove all newlines, leading to no available splits remaining. Helps with #4133.

FormatOps: don't force break before right paren

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

That is, if a token marked optimal results in non-zero cost, even before recursing, only queue it if killOnFail is not set.
Also, don't recurse if optimal token is the immediate next token. Helps with #4133.

BestFirstSearch: properly use optimal/killOnFail

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala

If set, it will simply cause this split to jump ahead to optimal token but not kill other splits. Helps with #4133.

OptimalToken: add flag not to exclude other splits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat

Router: recurse only SLB in ctrl body for `keep`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat

Router: tune optimal/killOnFail in binpack parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Router: add missing single-line policy for .select

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/default/Apply.stat
scalafmt-tests/src/test/resources/newlines/source.source
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/src/test/resources/scala3/OptionalBraces_unfold.stat

Previously, we would only allow that in triple-quote strings. However, for classic/keep try to avoid break if one wasn't present. Helps with #4133. Fixes #4187.

Router: allow breaks in any double-quote strings

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/scala3/Extension.stat

Move all significant-indentation formatting to OptionalBraces, and keep only non-significant-indentation case in Router. Helps with #4133.

FormatOps: fix extension formatting

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: keep block w/ standalone comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/src/test/resources/newlines/source_classic.stat
scalafmt-tests/src/test/resources/newlines/source_fold.stat
scalafmt-tests/src/test/resources/newlines/source_keep.stat
scalafmt-tests/src/test/resources/newlines/source_unfold.stat

Currently, the rule when break was present results in NL-only splits but those splits are different than the NL splits which would have been used had the break been absent. Fixes non-idempotency. Helps with #4133.

FormatOps: in CtrlBody, be consistent about src NL

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/WriteMode.scala

CliOptions: clean-up determining when out is used

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/Output.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala

CliOptions: turn info into a stream+writer wrapper

---

scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/Output.scala
scalafmt-tests/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala

Currently, info is written to out if out is not used for result output, and to err otherwise.
Let's enhance this approach as follows: if out is not used, then we'll write into to out, as before; otherwise, before resorting to err, check if the console is available and use it then.
Fixes #4156.

CliOptions: write info to console instead of err

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBracesStrInterpolation.stat

Otherwise, two adjacent but separate xml elements might get merged into one if the separating braces are removed. Helps with #4133.

RedundantBraces: keep braces around Term.Xml

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat

Fix redundant braces around infix (top-level, and using `return`)

---

build.sbt
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala
scalafmt-macros/shared/src/main/scala/org/scalafmt/config/DialectMacro.scala
scalafmt-tests/src/test/scala/org/scalafmt/config/ConfigDialectOverrideTest.scala

Necessary for cross compilation with Scala Native, since it does not offer any reflection functionalities.
Instead of the previous method, we create a mapping between strings (pointed out by the dialectOverride in scalafmt.conf) and methods that allow us to replace dialect values.
With that we still have the previous dialectOverride functionality that we do not have to manually maintain/expose and we avoid java reflection (which should make things faster even on the JVM).
Part of the Scala Native cross compilation effort (#4279)

Replace java reflection with a macro-based solution

---

build.sbt
project/Dependencies.scala
scalafmt-cli/src/main/scala/org/scalafmt/cli/InputMethod.scala

* Replace diffutils library with munit-diff: munit-diff is a reimplementation of the diffutils, necessary for cross compilation with Scala Native.
* Upgrade mdoc to 2.6.1: needed for mdoc-parser specifically, which only since 2.6.0 is available for Scala Native
Part of the Scala Native cross compilation effort (https://github.com/scalameta/scalafmt/pull/4279) (whichever PR gets merged first, I will be sure to rebase the other one).

Update libraries needed for cross compilation with Scala Native

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: keep between `return` and comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat

TreeOps: statements don't start on a comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: extract queues into a new class

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtOptimizer.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

ScalafmtOptimizer: allow to do only no-slow-states

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

BestFirstSearch: extract stats into separate class

---

scalafmt-core/jvm/src/main/scala/org/scalafmt/internal/RegexCompat.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/cli/FileTestOps.scala

Part of the Scala Native cross compilation effort (https://github.com/scalameta/scalafmt/pull/4279)

Separate regex patterns to jvm-only directory in preparation for Scala Native

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scalajs/Apply.stat

Router: skip braces when looking for binpack comma

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat

Router: merge rhsOptimalToken+endOfSingleLineBlock

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/default/TypeArguments.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat

It makes it consistent with how the rest of the arguments are handled, in the "comma" rule below. Helps with #4133.

Router: bp=defnsite `(` use first comma as optimal

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests/shared/src/test/resources/default/String.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat

BestFirstSearch: optimal has low-penalty NL split

---

scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunityMunitSuite.scala
scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunityRepoSuite.scala
scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunityScala2Suite.scala
scalafmt-tests-community/src/test/scala/org/scalafmt/community/CommunityScala3Suite.scala

CommunityRepoSuite: add common abstract superclass

---

.github/workflows/ci.yml
build.sbt
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunityBuild.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunityRepoSuite.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunitySuite.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/TestHelpers.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/TestStats.scala
scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/TestStyles.scala
scalafmt-tests-community/other/src/test/scala/org/scalafmt/community/other/CommunityMunitSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala

The tests run too long, so let's split them apart so we can run them in parallel. Helps with #4133.

CommunityTests: split into separate projects

---

scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/TestHelpers.scala

Otherwise, we'd need to add the directory to .gitignore.

CommunitySuite: check out projects under target/

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/SplitTag.scala
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scalajs/Advanced.stat
scalafmt-tests/shared/src/test/resources/scalajs/DefDef.stat

Revises #4021 and #4214. Helps with #4133.

Route: hide NL before dot for keep via a splittag

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat

RedundantBraces: keep around do-while within for

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

This allows us to handle tokens which occupy no space, such as Xml.End or Xml.Start. Helps with #4133.

TreeOps: get owners via token range, not position

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

That will require that the regular no-NL split is produced, as well. Helps with #4133.

Router: check if "NL" for `(` is actually not NL

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala

Also, ensure that lambda split on `{` uses the correct optimal token.

Router: consolidate splits around lambda

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

Also, in Router, fix indent after `yield` w/ NL+comment. Helps with #4133.

FormatOps: no blank within infix if not enclosed

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

Follow-on to #4366. Helps with #4133.

Router: price sole NL split in `=> <NL>` at 1

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/default/Idempotency.stat
scalafmt-tests/shared/src/test/resources/default/Lambda.stat
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

Don't call a statement:
- a single PartialFunction case
- a single function in braces, or its body
Follow-on to #4367. Helps with #4133.

TreeOps: revise NL-optimization around functions

---

scalafmt-tests-community/common/src/main/scala/org/scalafmt/community/common/CommunitySuite.scala

This avoids race conditions when global config is locked by another.

CommunitySuite: set longpaths in clone directory

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

Fix non-idempotence caused by handling RedundantBraces rewrite. Follow-on to #4375. Helps with #4133.

TreeOps: also ignore single-stat rewritten blocks

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

The behaviour is non-idempotent since splits depend on source formatting but might produce different breaks. Helps with #4133.

BestFirstSearch: stop using State.allAltAreNL

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/resources/unit/Comment.stat

FormatOps: use optimal slb end in binpacked `(...`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat

Otherwise, leads to non-idempotent formatting. Helps with #4133.

FormatOps: ignore source NL in binpacking ctors

---

.github/workflows/ci.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml

This part was omitted when the branch was renamed.

Workflows: change `master` to `main`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/resources/trailing-commas/trailingCommasPreserve.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: require NL before `}` if non-SLB `({`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Terminate the single-line block policy on `yield` if the body is not a block. Also, use that token as optimal, instead of the last body token. Helps with #4133.

FormatOps: fix ForYield as CtrlBody

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/OptimizationEntities.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala

OptimizationEntities: move TreeOps.statementStarts

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source.source
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

- Router: go inside AnonymousFunction to match body
- Router: no optimal on `(...` if use exclude blocks
Helps with #4133.

Router: fix performance of chained apply calls, with anon functions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: no NL after `<-` in `()` enums for scala3

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/ConvertToNewScala3Syntax.scala
scalafmt-tests/shared/src/test/resources/scala3/Vararg.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

ConvertToNewScala3Syntax: remove `:_`/`@_` as unit

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

It might have been overridden by `newlines.forceBeforeAssign` param. Follow-on to #4219.

Router: move up check for no NL after `<-` enums

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala

It doesn't affect formatting nor does it decrease the number of states visited. Helps with #4133.

BestFirstSearch: remove a useless optimization

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: remove optimal if avoid interpolation NL

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Follow-on to #4389. Helps with #4133.

Router: don't penalize NL before `:` if keeping

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/default/Advanced.stat
scalafmt-tests/shared/src/test/resources/default/Lambda.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

FormatOps: simplify logic of defnSiteLastToken

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Router: apply space.inParens consistently

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Instead, remove block(s) containing that partial function.

RedundantBraces: keep partial function braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

If we simply remove the parenthesis, then the comment will end up before the brace, unlike originally. Let's replace instead.

RedundantBraces: replace paren w/ brace if comment

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Imports.scala
scalafmt-tests/shared/src/test/resources/rewrite/Imports.source
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

This leads to re-ordering of `given` and `_`, which is incorrect. Revealed in scalameta/sbt-scalafmt#332.

Imports: do not expand nor sort import wildcards

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ModExt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Add SpaceOrNoSplit, handle State etc.
This new modification would serve as a space unless we encounter, on the same line, a terminating token, in which case it will become a NoSplit.
This will allow us to re-implement conversion of braces to parens for one-line apply without having to worry about possibly non-idempotent additional formatting rules.

Router: use SpaceOrNoSplit instead of custom rule

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

A fix for incorrectly merged #4463.

State: don't delay penalty with pending spaces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/default/String.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Check for empty blocks, or for non-blocks.

Router: fold `else` only after non-empty block

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/default/Advanced.stat
scalafmt-tests/shared/src/test/resources/default/Apply.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

When inserting or replacing tokens, we'd use the same start but the end could encroach onto the next one, so let's not use it.

Policy: compare starts, not ends

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Modification.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/AvoidInfix.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/LoggerOps.scala

Syntax might not include backticks which could be present in the code.

Use Token.text instead of Token.syntax

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

If the token spans multiple lines, let's use the maximum of first and last line length, as a vertical projection, instead of full length.

BestFirstSearch: use visual token width to recurse

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/default/Advanced.stat
scalafmt-tests/shared/src/test/resources/default/Apply.stat
scalafmt-tests/shared/src/test/resources/newlines/source.source
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

An optimal token would succeed if all splits cost 0, and there are no disallowed overflow tokens. In practice, this means that the span before the optimal token can't be way much longer than the line length.

BestFirstSearch: skip processOptimal if too long

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala

We don't need to use it before the opening brace, only after.

Router: inline braces-to-parens policy

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/default/Idempotency.stat
scalafmt-tests/shared/src/test/resources/unit/Apply.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

The usual NL split is forced through NB policy used with `{`.

Router: use single non-NL default split before `}`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

For `fold` case, using zero cost for the closing brace leads to cases of non-idempotence; lets increase the cost of the opening brace in those cases only, to account for that.

Router: penalize break after `{` in args

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

- merge the no-exclude SLB split into the lambda split
- set cost of NL split to align with one for `(...`
- this helps with cases when braces are rewritten to parens
- also, when computing tree depth, skip blocks (could be rewritten)
- fix NL penalties for `{...` and `=>...`
- align them for functions in braces and in parens

Router: refactor lambda splits for `{...`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBracesStrInterpolation.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

RedundantBraces: keep braces if splice is `$`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

This will give slight preference NOT to rewrite and avoid non-idempotent formatting.

Router: lower NL penalty for braces-to-parens case

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/TokenRange.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

This fixes a non-idempotency bug and leads to a massive improvement in state traversal.

PolicyOps: expire SLB exclude On in apply/select

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Instead of penalizing the split, set its cost to zero.
Also, do the same even for parens, to avoid non-idempotence.

Router: zero cost for dot NL in braces-to-parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Otherwise, it looks like a "fewer braces" invocation and will be parsed as such.

Router: no break after `=>` in lambda w/ type

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Docstrings.scala
scalafmt-tests/shared/src/test/resources/test/JavaDoc.stat

Docstrings: `blankFirstLine=fold` takes precedence

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala

In reality, that's what has been happening so far since we used an exact comparison on `stop`.

BestFirstSearch: allow block close go past range

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Indent.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/ModExt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala

This way, the checks are more precise, and we reduce the probability of comparing with a token that has been removed.

Use FormatToken in policies, indents etc.

---

docs/configuration.md

BinPack.ParentCtors: describe each option in doc

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

While it works, it might appear as if only `keep` is supported. Helps with #4542.

BinPack: use binPack.parentCtors=source explicitly

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/BinPack.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/binPack/ParentConstructors.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

FormatOps: implement binPack.parentCtor=ForceBreak

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Depending on the dialect, `a + ()` might parse the argument as an empty ArgClause or a single-arg Lit.Unit, which might lead to differences in formatting rules considered.

Router: handle Lit.Unit and empty ArgClause

---

build.sbt

Addresses build warning stipulating that these are not used.

SBT: remove buildInfoSettings from macros

---

scalafmt-dynamic/jvm/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala
scalafmt-dynamic/native/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala
scalafmt-interfaces/native/src/main/java/org/scalafmt/interfaces/Scalafmt.scala

DynamicSuite: test Scalafmt interface class loader

---

docs/contributing-scalafmt.md
readme.md

Small PR - fixes the `test/resources/readme.md` reference.

Update `test/resources/readme.md` reference

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Simplify the code a little bit, this penalty was completely superseded by the lambda penalty execution path.

Router: remove `{` nlPenalty computation

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/resources/scalajs/Apply.stat
scalafmt-tests/shared/src/test/resources/trailing-commas/trailingCommasAlwaysDanglingParens.stat
scalafmt-tests/shared/src/test/resources/trailing-commas/trailingCommasMultipleDanglingParens.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Increase arrow penalty on break after left brace or paren, and penalize arrows on break before preceding dot.

Router: penalize lambda arrow break further

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-dynamic/jvm/src/test/scala/org/scalafmt/dynamic/DynamicSuite.scala

- Error: use nested error message in WithCode
- DynamicSuite: use non-RC version for `latest`

Scalafmt: expand Error.WithCode in external format

---

project/Dependencies.scala

Otherwise, it was necessary manually to keep `Dependencies.scala` and `plugins.sbt` in sync.

SBT: get mdoc version from its plugin

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala

Also, remove it from other places if unused, and shorten to `fl` when still needed.

Policy: remove implicit FileLine from Relay

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantParens.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

RedundantParens: keep parens in `given` infix type

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/State.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala

Not just SingleLineBlock policy can lead to an impossible solution, so add this explicit field and use it in additional policies.

Policy: add terminal, use in BestFirstSearch

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Policy.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

They assume the policy is enclosed in a Delay or Expire and simplify itself by removing redundant components.
This also potentially leads to checks such as `terminal` and `maxEndPos` returning a different value and possibly leading to a different format.

Policy: add methods `asAfter` and `asUntil`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Instead of removing outer braces after checking that an inner expression will provide own, let's keep outer braces and remove them in the inner if appropriate.

RedundantBraces: remove inner braces in argclause

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Previously, we only allowed the braces to replace the parens on their immediate left, but now will also remove them if the block contains a simple expression.

RedundantBraces: remove braces in block in parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/RewriteSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

If the body is single-stat, instead of moving them to replace parens, just remove them.

RedundantBraces: remove func body braces in parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala

This one doesn't count opening or closing delimiters and is helpful in rewrite rules manipulating parens and braces.

FormatTokens: add a third way to compute offset

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantParens.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Check now that it's not enclosed in braces instead.

FormatOps: allow blank around infix if in parens

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests-community/intellij/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-ParenLambdas.stat
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

It appears that the check around opening brace is not important but the check around closing brace should take into account whether there's a trailing comma or if the infix continues after the right brace.

RedundantBraces: improve check around infix

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatTokens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Rewrite.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TokenTraverser.scala

Also, construct the default values without explicitly using the full string, as otherwise Intellij seems to detect it in the source file which contains it, despite it not being in a comment.

ScalafmtConfig: make format-on/off configurable

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests/shared/src/test/resources/vertical-multiline/verticalAlignMultilineOperators.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Also, remove assignmentOnly field and use notAssign scope. Follow-on to #4681.

FormatOps: use `exemptScope = notAssign`

---

docs/configuration.md

The documentation contains examples which were written for span in lines rather than characters, let's adjust span ranges for these examples to work.

Documentation: fix `redundantBraces.oneStatApply`

---

.github/workflows/ci.yml

Also, do not run CI when tagging; when the final commit of a release is merged, currently CI is invoked 3 times:
- upon commit merge into main (triggered by push to branch main)
- upon release (triggered by release published)
- upon tagging along with release (triggered by push to tag `vX.Y.Z`)
Let's remove the last trigger and run only native-image (which uploads release artifacts) on release trigger, as all the rest of the checks would have been run on the same commit when it had been originally pushed to main.

Workflow: run CI only native-image upon release

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

 FormatOps: `{` of refined type is optimal for defn

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantParens.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RemoveScala3OptionalBraces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests-community/scala2/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Newlines: split `afterInfix` into `infix.{term,type,pat}Site`

---

scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-tests/shared/src/test/resources/test/IndentOperator.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Don't use ExtraName as that will not take effect if other sections are moved to within `indent`. Fixes #4717.

ScalafmtConfig: rename continuationIndent->indent

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Apparently, break after forces an indented region and fails to compile. Fixes scalacenter/scalafix#2174.

Router: break before `=>` in new given

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/util/PolicyOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

- Router: check noSyntaxNL at the end of RHS
- PolicyOps: check NL in syntax on the right

Format strings and interpolated strings consistently

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/config/Spaces.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
scalafmt-tests/shared/src/test/resources/spaces/BeforeContextBoundColonIfMultipleBounds.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

It considers only context bounds, unlike the earlier ifMultipleBounds which looks at all bounds.

Spaces: add new IfMultipleContextBounds label

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

RedundantBraces: check comment in scala3 ArgClause

---

.github/workflows/ci.yml

scala-native doesn't need to run on push since we don't need to upload artifacts, and building is already verified as part of `test`.

CI: run `scala-native` only on release

---

.github/workflows/ci.yml

dockerize used to run on tag push but we have disabled this trigger; also, since it downloads an artifact, we simply need to run it after the artifact is uploaded, i.e. on release.
Hopefully, the change to "metadata-action" to extract tags works exactly as chatgpt promised.
Possibly fixes #4761.

CI: enable `dockerize` on release

---

scalafmt-core/native/src/main/scala/org/scalafmt/internal/RegexCompat.scala

It fixes horizontal whitespace patterns before doing so.

RegexCompat[native]: add method to compile pattern

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces2.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

We continue removing blocks nested within another block, assuming that at least one outer block is preserved if necessary.
Therefore, before removing an outer block, make sure it doesn't contain a deeply nested multi-stat expression.

RedundantBraces: fix removing blocks

---

scalafmt-benchmarks/src/main/scala/org/scalafmt/benchmarks/MicroBenchmark.scala
scalafmt-cli/jvm/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-cli/shared/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-cli/shared/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-cli/shared/src/test/scala/org/scalafmt/cli/FileTestOps.scala
scalafmt-sysops/jvm/src/main/scala/org/scalafmt/sysops/PlatformCompat.scala
scalafmt-sysops/native/src/main/scala/org/scalafmt/sysops/PlatformCompat.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/AbsoluteFile.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/BatchPathFinder.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/FileOps.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/FileStat.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/GitOps.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/PlatformFileOps.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/PlatformRunOps.scala
scalafmt-sysops/shared/src/test/scala/org/scalafmt/sysops/DeleteTree.scala
scalafmt-sysops/shared/src/test/scala/org/scalafmt/sysops/FileOpsTest.scala
scalafmt-sysops/shared/src/test/scala/org/scalafmt/sysops/GitOpsTest.scala
scalafmt-tests-community/common/shared/src/test/scala/org/scalafmt/community/common/TestHelpers.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FidelityTest.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/ManualTests.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/UnitTests.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/util/HasTests.scala

Put some shared code in `jvm-native/` and some in `jvm/` or `native/`.

sysops: refactor platform-specific code

---

scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/shared/src/test/scala/org/scalafmt/cli/CliOptionsTest.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/FileOps.scala

Scala.js doesn't support NoSuchFileException etc.

Use platform-agnostic exception classes

---

build.sbt
project/Dependencies.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/config/ScalafmtConfigTest.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/config/StandardProjectLayoutTest.scala

Now that JS NodeNIOPath works on Windows, re-enable the tests.

Scalameta: upgrade to v4.13.1

---

build.sbt
scalafmt-cli/jvm/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-sysops/js/src/main/scala/org/scalafmt/sysops/PlatformFileOps.scala
scalafmt-sysops/js/src/main/scala/org/scalafmt/sysops/PlatformRunOps.scala
scalafmt-sysops/jvm-native/src/main/scala/org/scalafmt/sysops/PlatformFileOps.scala
scalafmt-sysops/jvm-native/src/main/scala/org/scalafmt/sysops/PlatformRunOps.scala
scalafmt-sysops/jvm/src/main/scala/org/scalafmt/sysops/GranularPlatformAsyncOps.scala
scalafmt-sysops/native/src/main/scala/org/scalafmt/sysops/GranularPlatformAsyncOps.scala
scalafmt-tests-community/common/shared/src/test/scala/org/scalafmt/community/common/TestHelpers.scala

Previously, we simply wrapped a Future around a blocking file I/O both on JVM and Native; while we still keep this approach on Native, let's implement actual asynchronous file I/O on JVM, just like on JS.
Also, modify runners to use this async writing and a different thread pool for that, so that it does not clash with formatting tasks.

PlatformFileOps: read/write files asynchronously

---

build.sbt

This causes the nativeLink task to be executed for all the modules and it doesn't make sense to do that for non app modules.

bugfix: Don't use aggregate in Scala Native

---

scalafmt-cli/jvm/src/main/scala/org/scalafmt/cli/CliUtils.scala
scalafmt-cli/jvm/src/main/scala/org/scalafmt/cli/ScalafmtDynamicRunner.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/Cli.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/TermDisplay.scala
scalafmt-cli/shared/src/test/scala/org/scalafmt/cli/CliTest.scala
scalafmt-sysops/js/src/main/scala/org/scalafmt/sysops/PlatformRunOps.scala
scalafmt-sysops/jvm-native/src/main/scala/org/scalafmt/sysops/PlatformRunOps.scala
scalafmt-sysops/jvm/src/main/scala/org/scalafmt/sysops/GranularPlatformAsyncOps.scala
scalafmt-sysops/native/src/main/scala/org/scalafmt/sysops/GranularPlatformAsyncOps.scala
scalafmt-sysops/shared/src/main/scala-2.12/org/scalafmt/sysops/GranularDialectAsyncOps.scala
scalafmt-sysops/shared/src/main/scala-2.13/org/scalafmt/sysops/GranularDialectAsyncOps.scala
scalafmt-tests-community/common/shared/src/test/scala/org/scalafmt/community/common/CommunitySuite.scala
scalafmt-tests-community/common/shared/src/test/scala/org/scalafmt/community/common/TestHelpers.scala

- in both core and dynamic runners, reading and writing is done the same way, with the only difference being formatting; hence, let's move I/O to shared runner
- to avoid reading all files first and only then formatting and writing them, let's create separate input and output execution contexts and use the former for reading and formatting, and the latter for writing
- finally, let's define parasitic execution context (one which executes immediately, without putting the task in a queue), for short tasks such as triggering `.onComplete` or updating task progress

ScalafmtRunner: use separate execution contexts

---

scalafmt-sysops/jvm/src/main/scala/org/scalafmt/sysops/GranularPlatformAsyncOps.scala

Instead of creating an async channel in current thread, schedule it as a future, which moves execution to a worker and captures exceptions as well.
Also, use attachable contexts in handler methods.

GranularPlatformAsyncOps: modify read/write async

---

scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/Cli.scala

Since `main` is now async, it will not automatically exit the process on failure and will instead hang. Let's exit explicitly.

Cli: do not forget to exit on failure as well

---

scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/InputMethod.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtCliReporter.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/Error.scala

Now that we don't need to `recover` this error in ScalafmtRunner, adjust that logic as well.

InputMethod: handle misformatted file, don't throw

---

scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala

Apparently, Future.foldLeft stops on first failure, so let's make sure that all tasks result in "success" and then flatten the result.

ScalafmtRunner: don't stop on first failure

---

scalafmt-core/js/src/main/scala/org/scalafmt/internal/RegexCompat.scala
scalafmt-core/jvm/src/main/scala/org/scalafmt/internal/RegexCompat.scala
scalafmt-core/native/src/main/scala/org/scalafmt/internal/RegexCompat.scala
scalafmt-tests/shared/src/test/resources/default/String.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

RegexCompat: keep multiline-string trailing spaces

---

scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/CliOptions.scala
scalafmt-cli/shared/src/main/scala/org/scalafmt/cli/ScalafmtCoreRunner.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RunnerSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala
scalafmt-docs/src/main/scala/website/package.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/config/ConfigDialectOverrideTest.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/config/RunnerSettingsTest.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/util/FormatAssertions.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/util/HasTests.scala

ScalafmtRunner is also a base class in cli package, let's disambiguate.

RunnerSettings: rename from ScalafmtRunner

---

.github/workflows/ci.yml
.github/workflows/release-native.yml

Without the change it seems it's not possible to use scalafmt on older ubuntu images due to older gcc version. This should not be an issue normally as users can just update. For windows it's just a precaution since that is also the latest image and windows-2019 seems way too old.

improvement: Pin image versions

---

scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/NamedDialect.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/RunnerSettings.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/config/package.scala
scalafmt-docs/src/main/scala/docs/ScalafmtModifier.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/config/StandardProjectLayoutTest.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/util/HasTests.scala

Also:
- remove local copies of dialects: they are completely identical to the originals and they also convey the impression that their type is NamedDialect when it is just Dialect
- replace NamedDialect with sourcecode.Text[Dialect]: this will allow passing a properly named variable containing just a dialect to a method expecting a "named dialect"

Config: make `withDialect` a public method

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

We don't allow break after `=>` in lambda when the parameter might look like a fewer-braces apply. However, if the parameter has an `implicit`, there's no danger of that.

TreeOps: fix lambda param check a-la fewer-braces

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Splits: ensure break between `yield` and `case`

---

docs/configuration.md
docs/installation.md

At the moment, the "Get started" button on the homepage links to the Installation documentation, but doesn't include instructions on setting Scalafmt up for a project. I have observed that this creates significant friction for engineers that are new to Scala.
It's tough to discover that there are two required pieces of configuration, and what the values of these should be. Even on the configuration page (which addresses more complex examples) there's no clear of example of a minimal working config definition that teams can start from. This means Scalafmt is only accessible to engineers that already know how it works, or that have somewhere else to copy a working config file from.
This change adds a note to the top of the Installation documentation, because:
1. this page is linked from …

Add working "get started" example

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-tests-community/intellij/shared/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/shared/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/shared/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/shared/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Previously, we'd assume that a brace within `if` or `while` contains the entire condition and let the brace rules handle it; however, this brace could enclose only a part of the condition and hence needs to be handled differently then.
Additionally, we ignored the danglingParentheses.ctrlSite parameter in these cases as well.
Helps with #4859.

Splits: handle braces within if/for/while better

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/newlines/source_keep.stat
scalafmt-tests/shared/src/test/resources/newlines/source_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

We already do that for `danglingParentheses.ctrlSite = true` but now fix also the other case.

Splits: don't indent enclosed cond in if/while

---

scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
scalafmt-tests/shared/src/test/resources/trailing-commas/trailingCommasAlways.stat
scalafmt-tests/shared/src/test/resources/trailing-commas/trailingCommasPreserve.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

TreeOps: no trailing commas for extended instance

---

build.sbt
scalafmt-sysops/shared/src/main/scala-2.12/org/scalafmt/CompatCollections.scala
scalafmt-sysops/shared/src/main/scala-2.13/org/scalafmt/CompatCollections.scala
scalafmt-tests/jvm/src/test/scala-2.12/org.scalafmt/TestCompatCollections.scala
scalafmt-tests/jvm/src/test/scala-2.13/org/scalafmt/TestCompatCollections.scala
scalafmt-tests/jvm/src/test/scala/org/scalafmt/ScalafmtProps.scala

We use Futures everywhere, except ScalafmtProps test.

ParConverters: move from sysops to tests

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala

That is, handle only those comments which are provisioned for select rather than attached to, say, case body.
Helps with #4897.

Splits: refine comment handling within select

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Splits.scala
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Splits: prefer before-dot over after-arrow rule

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
scalafmt-tests-community/intellij/shared/src/test/scala/org/scalafmt/community/intellij/CommunityIntellijScalaSuite.scala
scalafmt-tests-community/scala2/shared/src/test/scala/org/scalafmt/community/scala2/CommunityScala2Suite.scala
scalafmt-tests-community/scala3/shared/src/test/scala/org/scalafmt/community/scala3/CommunityScala3Suite.scala
scalafmt-tests-community/spark/shared/src/test/scala/org/scalafmt/community/spark/CommunitySparkSuite.scala
scalafmt-tests/shared/src/test/resources/newlines/source_classic.stat
scalafmt-tests/shared/src/test/resources/newlines/source_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_keep.stat
scalafmt-tests/shared/src/test/resources/scala3/FewerBraces_unfold.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Instead of forcing possibly inconsistent before-comment splits after the comment, use the natural splits but slightly modify them. That will make sure that any policies they come with are correctly preserved.
Fixes #4897.

FormatOps: modify ctrl-body comment splits

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/shared/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Since an infix chain usually looks like one expression, especially when spanning multiple lines, let's get the outer one.

FormatWriter: traverse align owner up infix chain

---

docs/configuration.md
scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/shared/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Keep the owner unchanged but apply this special logic mapping operator (Term.Name) to parent infix tree (Term.ApplyInfix) only when checking if the operator token is to be aligned using configured matchers.
If an infix expression starts with a multiline subexpression but ends with a single line of tokens to be aligned, then subsequent single-line statements are properly aligned with it.
However, in the opposite case, when an infix expression starts with a single line of tokens to be aligned and continues with a multiline part, then it was not aligned with previous statements.
By keeping the owner, we fix this inconsistency.
Includes undo of #4904.

FormatWriter: again fix infix align owner

---

scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala
scalafmt-tests/shared/src/test/resources/align/DefaultWithAlign.stat
scalafmt-tests/shared/src/test/resources/newlines/afterCurlyLambdaNever.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_fold.stat
scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces_keep.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Remove EOL owner position check in `isMatchPossible` and simply rely on reference row being before current row. For multiline statements, that would not hold true.

FormatWriter: fix inconsistent multiline alignment

---

scalafmt-tests/shared/src/test/scala/org/scalafmt/FidelityTest.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/util/FormatAssertions.scala

Previously, we would read files while setting up test cases.

FidelityTest: read file async and within test body

---

docs/configuration.md
docs/contributing-scalafmt.md

- readme/Readme.scalatex is removed in a105e65926b04e8d5179826e837bab4baa1cd39c
- configuration should be `rewrite.scala3.newSyntax` instead of `rewrite.scala.newSyntax`, referring to test case https://github.com/scalameta/scalafmt/blob/831b891411022deaab0081a20f0965ec4bc96dea/scalafmt-tests/shared/src/test/resources/scala3/OptionalBraces.stat#L1540

Fix wrong config name and outdated path in doc

---

scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/RedundantBraces.scala
scalafmt-tests/shared/src/test/resources/rewrite/RedundantBraces-case.stat
scalafmt-tests/shared/src/test/scala/org/scalafmt/FormatTests.scala

Match the logic applied in RedundantParens, allow postfix expressions.

RedundantBraces: remove in if-guard sometimes

---

scalafmt-dynamic/jvm/src/main/scala/org/scalafmt/dynamic/CoursierDependencyDownloader.scala

Also, use `addRepositories` instead of `withRepositories`, as that will preserve the default repositories so we can skip adding them explicitly.

CoursierDependencyDownloader: remove legacy OSS

---

build.sbt
scalafmt-dynamic/jvm/src/main/scala/org/scalafmt/dynamic/CoursierDependencyDownloader.scala

This requires using the full coursier library as it loads credentials from COURSIER_CREDENTIALS env var, just like any default repositories have been loaded from COURSIER_REPOSITORIES.

CoursierDependencyDownloader: support credentials

---

scalafmt-sysops/js/src/main/scala/org/scalafmt/sysops/PlatformFileOps.scala
scalafmt-sysops/jvm-native/src/main/scala/org/scalafmt/sysops/PlatformFileOps.scala
scalafmt-sysops/shared/src/main/scala/org/scalafmt/sysops/FileOps.scala
scalafmt-sysops/shared/src/test/scala/org/scalafmt/sysops/FileOpsTest.scala
scalafmt-tests/shared/src/test/scala/org/scalafmt/FidelityTest.scala

Unfortunately, Files.find has no way to handle exceptions during tree traversal, including those it generates itself (such as when reading the file attributes).
Instead, let's add ability to use Files.walk, with a more fine-grained visitor handler.

FileOps: implement walkFiles with granular control
